// Code generated by MockGen. DO NOT EDIT.
// Source: svc.go
//
// Generated by this command:
//
//	mockgen -source svc.go -destination mock_chat_import_svc/mock_chat_import_svc.go
//

// Package mock_chat_import_svc is a generated GoMock package.
package mock_chat_import_svc

import (
	context "context"
	reflect "reflect"

	chat_import_svc "github.com/agentre-hub/agentre/internal/service/chat_import_svc"
	gomock "go.uber.org/mock/gomock"
)

// MockChatImportSvc is a mock of ChatImportSvc interface.
type MockChatImportSvc struct {
	ctrl     *gomock.Controller
	recorder *MockChatImportSvcMockRecorder
	isgomock struct{}
}

// MockChatImportSvcMockRecorder is the mock recorder for MockChatImportSvc.
type MockChatImportSvcMockRecorder struct {
	mock *MockChatImportSvc
}

// NewMockChatImportSvc creates a new mock instance.
func NewMockChatImportSvc(ctrl *gomock.Controller) *MockChatImportSvc {
	mock := &MockChatImportSvc{ctrl: ctrl}
	mock.recorder = &MockChatImportSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatImportSvc) EXPECT() *MockChatImportSvcMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockChatImportSvc) Cancel(ctx context.Context, req *chat_import_svc.CancelImportRequest) (*chat_import_svc.CancelImportResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, req)
	ret0, _ := ret[0].(*chat_import_svc.CancelImportResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cancel indicates an expected call of Cancel.
func (mr *MockChatImportSvcMockRecorder) Cancel(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockChatImportSvc)(nil).Cancel), ctx, req)
}

// Import mocks base method.
func (m *MockChatImportSvc) Import(ctx context.Context, req *chat_import_svc.ImportRequest, onProgress chat_import_svc.ProgressFunc) (*chat_import_svc.ImportResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Import", ctx, req, onProgress)
	ret0, _ := ret[0].(*chat_import_svc.ImportResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Import indicates an expected call of Import.
func (mr *MockChatImportSvcMockRecorder) Import(ctx, req, onProgress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Import", reflect.TypeOf((*MockChatImportSvc)(nil).Import), ctx, req, onProgress)
}

// ListCandidates mocks base method.
func (m *MockChatImportSvc) ListCandidates(ctx context.Context, req *chat_import_svc.ListCandidatesRequest) (*chat_import_svc.ListCandidatesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCandidates", ctx, req)
	ret0, _ := ret[0].(*chat_import_svc.ListCandidatesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCandidates indicates an expected call of ListCandidates.
func (mr *MockChatImportSvcMockRecorder) ListCandidates(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCandidates", reflect.TypeOf((*MockChatImportSvc)(nil).ListCandidates), ctx, req)
}

// Preview mocks base method.
func (m *MockChatImportSvc) Preview(ctx context.Context, req *chat_import_svc.PreviewRequest) (*chat_import_svc.PreviewResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Preview", ctx, req)
	ret0, _ := ret[0].(*chat_import_svc.PreviewResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Preview indicates an expected call of Preview.
func (mr *MockChatImportSvcMockRecorder) Preview(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Preview", reflect.TypeOf((*MockChatImportSvc)(nil).Preview), ctx, req)
}

// MockTxRunner is a mock of TxRunner interface.
type MockTxRunner struct {
	ctrl     *gomock.Controller
	recorder *MockTxRunnerMockRecorder
	isgomock struct{}
}

// MockTxRunnerMockRecorder is the mock recorder for MockTxRunner.
type MockTxRunnerMockRecorder struct {
	mock *MockTxRunner
}

// NewMockTxRunner creates a new mock instance.
func NewMockTxRunner(ctrl *gomock.Controller) *MockTxRunner {
	mock := &MockTxRunner{ctrl: ctrl}
	mock.recorder = &MockTxRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxRunner) EXPECT() *MockTxRunnerMockRecorder {
	return m.recorder
}

// RunInTx mocks base method.
func (m *MockTxRunner) RunInTx(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTx indicates an expected call of RunInTx.
func (mr *MockTxRunnerMockRecorder) RunInTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTx", reflect.TypeOf((*MockTxRunner)(nil).RunInTx), ctx, fn)
}
