// Code generated by MockGen. DO NOT EDIT.
// Source: hook.go
//
// Generated by this command:
//
//	mockgen -source hook.go -destination mock_hook_repo/mock_hook.go
//

// Package mock_hook_repo is a generated GoMock package.
package mock_hook_repo

import (
	context "context"
	reflect "reflect"

	hook_entity "github.com/agentre-hub/agentre/internal/model/entity/hook_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockHookRepo is a mock of HookRepo interface.
type MockHookRepo struct {
	ctrl     *gomock.Controller
	recorder *MockHookRepoMockRecorder
	isgomock struct{}
}

// MockHookRepoMockRecorder is the mock recorder for MockHookRepo.
type MockHookRepoMockRecorder struct {
	mock *MockHookRepo
}

// NewMockHookRepo creates a new mock instance.
func NewMockHookRepo(ctrl *gomock.Controller) *MockHookRepo {
	mock := &MockHookRepo{ctrl: ctrl}
	mock.recorder = &MockHookRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHookRepo) EXPECT() *MockHookRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockHookRepo) Create(ctx context.Context, h *hook_entity.Hook) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, h)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockHookRepoMockRecorder) Create(ctx, h any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockHookRepo)(nil).Create), ctx, h)
}

// Delete mocks base method.
func (m *MockHookRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockHookRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockHookRepo)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockHookRepo) Find(ctx context.Context, id int64) (*hook_entity.Hook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*hook_entity.Hook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockHookRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockHookRepo)(nil).Find), ctx, id)
}

// FindByName mocks base method.
func (m *MockHookRepo) FindByName(ctx context.Context, name string) (*hook_entity.Hook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].(*hook_entity.Hook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockHookRepoMockRecorder) FindByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockHookRepo)(nil).FindByName), ctx, name)
}

// List mocks base method.
func (m *MockHookRepo) List(ctx context.Context) ([]*hook_entity.Hook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*hook_entity.Hook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockHookRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockHookRepo)(nil).List), ctx)
}

// ListDue mocks base method.
func (m *MockHookRepo) ListDue(ctx context.Context, now int64) ([]*hook_entity.Hook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDue", ctx, now)
	ret0, _ := ret[0].([]*hook_entity.Hook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDue indicates an expected call of ListDue.
func (mr *MockHookRepoMockRecorder) ListDue(ctx, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDue", reflect.TypeOf((*MockHookRepo)(nil).ListDue), ctx, now)
}

// Update mocks base method.
func (m *MockHookRepo) Update(ctx context.Context, h *hook_entity.Hook) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, h)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockHookRepoMockRecorder) Update(ctx, h any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockHookRepo)(nil).Update), ctx, h)
}

// MockHookEventRepo is a mock of HookEventRepo interface.
type MockHookEventRepo struct {
	ctrl     *gomock.Controller
	recorder *MockHookEventRepoMockRecorder
	isgomock struct{}
}

// MockHookEventRepoMockRecorder is the mock recorder for MockHookEventRepo.
type MockHookEventRepoMockRecorder struct {
	mock *MockHookEventRepo
}

// NewMockHookEventRepo creates a new mock instance.
func NewMockHookEventRepo(ctrl *gomock.Controller) *MockHookEventRepo {
	mock := &MockHookEventRepo{ctrl: ctrl}
	mock.recorder = &MockHookEventRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHookEventRepo) EXPECT() *MockHookEventRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockHookEventRepo) Create(ctx context.Context, e *hook_entity.HookEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockHookEventRepoMockRecorder) Create(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockHookEventRepo)(nil).Create), ctx, e)
}

// FindByDedupeKey mocks base method.
func (m *MockHookEventRepo) FindByDedupeKey(ctx context.Context, hookID int64, key string) (*hook_entity.HookEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByDedupeKey", ctx, hookID, key)
	ret0, _ := ret[0].(*hook_entity.HookEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByDedupeKey indicates an expected call of FindByDedupeKey.
func (mr *MockHookEventRepoMockRecorder) FindByDedupeKey(ctx, hookID, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByDedupeKey", reflect.TypeOf((*MockHookEventRepo)(nil).FindByDedupeKey), ctx, hookID, key)
}

// ListByHook mocks base method.
func (m *MockHookEventRepo) ListByHook(ctx context.Context, hookID int64, limit int) ([]*hook_entity.HookEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByHook", ctx, hookID, limit)
	ret0, _ := ret[0].([]*hook_entity.HookEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByHook indicates an expected call of ListByHook.
func (mr *MockHookEventRepoMockRecorder) ListByHook(ctx, hookID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByHook", reflect.TypeOf((*MockHookEventRepo)(nil).ListByHook), ctx, hookID, limit)
}

// ListRecent mocks base method.
func (m *MockHookEventRepo) ListRecent(ctx context.Context, limit int) ([]*hook_entity.HookEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecent", ctx, limit)
	ret0, _ := ret[0].([]*hook_entity.HookEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecent indicates an expected call of ListRecent.
func (mr *MockHookEventRepoMockRecorder) ListRecent(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecent", reflect.TypeOf((*MockHookEventRepo)(nil).ListRecent), ctx, limit)
}
