// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source ports.go -destination mock_agentruntime/mock_ports.go
//

// Package mock_agentruntime is a generated GoMock package.
package mock_agentruntime

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	devicefp "github.com/agentre-hub/agentre/pkg/wire/devicefp"
	gomock "go.uber.org/mock/gomock"
)

// MockDaemonClientPort is a mock of DaemonClientPort interface.
type MockDaemonClientPort struct {
	ctrl     *gomock.Controller
	recorder *MockDaemonClientPortMockRecorder
	isgomock struct{}
}

// MockDaemonClientPortMockRecorder is the mock recorder for MockDaemonClientPort.
type MockDaemonClientPortMockRecorder struct {
	mock *MockDaemonClientPort
}

// NewMockDaemonClientPort creates a new mock instance.
func NewMockDaemonClientPort(ctrl *gomock.Controller) *MockDaemonClientPort {
	mock := &MockDaemonClientPort{ctrl: ctrl}
	mock.recorder = &MockDaemonClientPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDaemonClientPort) EXPECT() *MockDaemonClientPortMockRecorder {
	return m.recorder
}

// Call mocks base method.
func (m *MockDaemonClientPort) Call(ctx context.Context, method string, params, result any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Call", ctx, method, params, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// Call indicates an expected call of Call.
func (mr *MockDaemonClientPortMockRecorder) Call(ctx, method, params, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Call", reflect.TypeOf((*MockDaemonClientPort)(nil).Call), ctx, method, params, result)
}

// Close mocks base method.
func (m *MockDaemonClientPort) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDaemonClientPortMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDaemonClientPort)(nil).Close))
}

// Closed mocks base method.
func (m *MockDaemonClientPort) Closed() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Closed")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Closed indicates an expected call of Closed.
func (mr *MockDaemonClientPortMockRecorder) Closed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Closed", reflect.TypeOf((*MockDaemonClientPort)(nil).Closed))
}

// Handle mocks base method.
func (m *MockDaemonClientPort) Handle(method string, fn func(context.Context, json.RawMessage) (any, error)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Handle", method, fn)
}

// Handle indicates an expected call of Handle.
func (mr *MockDaemonClientPortMockRecorder) Handle(method, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockDaemonClientPort)(nil).Handle), method, fn)
}

// Notify mocks base method.
func (m *MockDaemonClientPort) Notify(method string, params any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", method, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockDaemonClientPortMockRecorder) Notify(method, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockDaemonClientPort)(nil).Notify), method, params)
}

// MockSessionCursorPort is a mock of SessionCursorPort interface.
type MockSessionCursorPort struct {
	ctrl     *gomock.Controller
	recorder *MockSessionCursorPortMockRecorder
	isgomock struct{}
}

// MockSessionCursorPortMockRecorder is the mock recorder for MockSessionCursorPort.
type MockSessionCursorPortMockRecorder struct {
	mock *MockSessionCursorPort
}

// NewMockSessionCursorPort creates a new mock instance.
func NewMockSessionCursorPort(ctrl *gomock.Controller) *MockSessionCursorPort {
	mock := &MockSessionCursorPort{ctrl: ctrl}
	mock.recorder = &MockSessionCursorPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionCursorPort) EXPECT() *MockSessionCursorPortMockRecorder {
	return m.recorder
}

// LoadCursor mocks base method.
func (m *MockSessionCursorPort) LoadCursor(ctx context.Context, sessionID int64, daemonFingerprint devicefp.Carrier) (int64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadCursor", ctx, sessionID, daemonFingerprint)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// LoadCursor indicates an expected call of LoadCursor.
func (mr *MockSessionCursorPortMockRecorder) LoadCursor(ctx, sessionID, daemonFingerprint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadCursor", reflect.TypeOf((*MockSessionCursorPort)(nil).LoadCursor), ctx, sessionID, daemonFingerprint)
}

// SaveCursor mocks base method.
func (m *MockSessionCursorPort) SaveCursor(ctx context.Context, sessionID int64, daemonFingerprint devicefp.Carrier, seq int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCursor", ctx, sessionID, daemonFingerprint, seq)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCursor indicates an expected call of SaveCursor.
func (mr *MockSessionCursorPortMockRecorder) SaveCursor(ctx, sessionID, daemonFingerprint, seq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCursor", reflect.TypeOf((*MockSessionCursorPort)(nil).SaveCursor), ctx, sessionID, daemonFingerprint, seq)
}
