// Code generated by MockGen. DO NOT EDIT.
// Source: replacement_recovery.go
//
// Generated by this command:
//
//	mockgen -source replacement_recovery.go -destination mock_chat_repo/mock_replacement_recovery.go
//

// Package mock_chat_repo is a generated GoMock package.
package mock_chat_repo

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReplacementRecoveryCleanupRepo is a mock of ReplacementRecoveryCleanupRepo interface.
type MockReplacementRecoveryCleanupRepo struct {
	ctrl     *gomock.Controller
	recorder *MockReplacementRecoveryCleanupRepoMockRecorder
	isgomock struct{}
}

// MockReplacementRecoveryCleanupRepoMockRecorder is the mock recorder for MockReplacementRecoveryCleanupRepo.
type MockReplacementRecoveryCleanupRepoMockRecorder struct {
	mock *MockReplacementRecoveryCleanupRepo
}

// NewMockReplacementRecoveryCleanupRepo creates a new mock instance.
func NewMockReplacementRecoveryCleanupRepo(ctrl *gomock.Controller) *MockReplacementRecoveryCleanupRepo {
	mock := &MockReplacementRecoveryCleanupRepo{ctrl: ctrl}
	mock.recorder = &MockReplacementRecoveryCleanupRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReplacementRecoveryCleanupRepo) EXPECT() *MockReplacementRecoveryCleanupRepoMockRecorder {
	return m.recorder
}

// DeleteReplacementRecovery mocks base method.
func (m *MockReplacementRecoveryCleanupRepo) DeleteReplacementRecovery(ctx context.Context, sessionID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReplacementRecovery", ctx, sessionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteReplacementRecovery indicates an expected call of DeleteReplacementRecovery.
func (mr *MockReplacementRecoveryCleanupRepoMockRecorder) DeleteReplacementRecovery(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReplacementRecovery", reflect.TypeOf((*MockReplacementRecoveryCleanupRepo)(nil).DeleteReplacementRecovery), ctx, sessionID)
}
