// Code generated by MockGen. DO NOT EDIT.
// Source: message.go
//
// Generated by this command:
//
//	mockgen -source message.go -destination mock_chat_repo/mock_message.go
//

// Package mock_chat_repo is a generated GoMock package.
package mock_chat_repo

import (
	context "context"
	reflect "reflect"

	chat_entity "github.com/agentre-hub/agentre/internal/model/entity/chat_entity"
	chat_repo "github.com/agentre-hub/agentre/internal/repository/chat_repo"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageRepo is a mock of MessageRepo interface.
type MockMessageRepo struct {
	ctrl     *gomock.Controller
	recorder *MockMessageRepoMockRecorder
	isgomock struct{}
}

// MockMessageRepoMockRecorder is the mock recorder for MockMessageRepo.
type MockMessageRepoMockRecorder struct {
	mock *MockMessageRepo
}

// NewMockMessageRepo creates a new mock instance.
func NewMockMessageRepo(ctrl *gomock.Controller) *MockMessageRepo {
	mock := &MockMessageRepo{ctrl: ctrl}
	mock.recorder = &MockMessageRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageRepo) EXPECT() *MockMessageRepoMockRecorder {
	return m.recorder
}

// AppendSubagentChildren mocks base method.
func (m *MockMessageRepo) AppendSubagentChildren(ctx context.Context, sessionID int64, parentToolCallID, childBlocksJSON string, childIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendSubagentChildren", ctx, sessionID, parentToolCallID, childBlocksJSON, childIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendSubagentChildren indicates an expected call of AppendSubagentChildren.
func (mr *MockMessageRepoMockRecorder) AppendSubagentChildren(ctx, sessionID, parentToolCallID, childBlocksJSON, childIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendSubagentChildren", reflect.TypeOf((*MockMessageRepo)(nil).AppendSubagentChildren), ctx, sessionID, parentToolCallID, childBlocksJSON, childIDs)
}

// Create mocks base method.
func (m_2 *MockMessageRepo) Create(ctx context.Context, m *chat_entity.Message) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMessageRepoMockRecorder) Create(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMessageRepo)(nil).Create), ctx, m)
}

// DeleteFromSeq mocks base method.
func (m *MockMessageRepo) DeleteFromSeq(ctx context.Context, sessionID int64, fromSeq int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFromSeq", ctx, sessionID, fromSeq)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFromSeq indicates an expected call of DeleteFromSeq.
func (mr *MockMessageRepoMockRecorder) DeleteFromSeq(ctx, sessionID, fromSeq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFromSeq", reflect.TypeOf((*MockMessageRepo)(nil).DeleteFromSeq), ctx, sessionID, fromSeq)
}

// FillBlocks mocks base method.
func (m *MockMessageRepo) FillBlocks(ctx context.Context, msgs []*chat_entity.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FillBlocks", ctx, msgs)
	ret0, _ := ret[0].(error)
	return ret0
}

// FillBlocks indicates an expected call of FillBlocks.
func (mr *MockMessageRepoMockRecorder) FillBlocks(ctx, msgs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FillBlocks", reflect.TypeOf((*MockMessageRepo)(nil).FillBlocks), ctx, msgs)
}

// FillBlocksByType mocks base method.
func (m *MockMessageRepo) FillBlocksByType(ctx context.Context, msgs []*chat_entity.Message, types []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FillBlocksByType", ctx, msgs, types)
	ret0, _ := ret[0].(error)
	return ret0
}

// FillBlocksByType indicates an expected call of FillBlocksByType.
func (mr *MockMessageRepoMockRecorder) FillBlocksByType(ctx, msgs, types any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FillBlocksByType", reflect.TypeOf((*MockMessageRepo)(nil).FillBlocksByType), ctx, msgs, types)
}

// Find mocks base method.
func (m *MockMessageRepo) Find(ctx context.Context, id int64) (*chat_entity.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*chat_entity.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockMessageRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockMessageRepo)(nil).Find), ctx, id)
}

// FindAssistantBySubagentToolCallID mocks base method.
func (m *MockMessageRepo) FindAssistantBySubagentToolCallID(ctx context.Context, sessionID int64, toolCallID string) (*chat_entity.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAssistantBySubagentToolCallID", ctx, sessionID, toolCallID)
	ret0, _ := ret[0].(*chat_entity.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAssistantBySubagentToolCallID indicates an expected call of FindAssistantBySubagentToolCallID.
func (mr *MockMessageRepoMockRecorder) FindAssistantBySubagentToolCallID(ctx, sessionID, toolCallID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAssistantBySubagentToolCallID", reflect.TypeOf((*MockMessageRepo)(nil).FindAssistantBySubagentToolCallID), ctx, sessionID, toolCallID)
}

// FindSubagentState mocks base method.
func (m *MockMessageRepo) FindSubagentState(ctx context.Context, sessionID int64, toolCallID string) (string, string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSubagentState", ctx, sessionID, toolCallID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// FindSubagentState indicates an expected call of FindSubagentState.
func (mr *MockMessageRepoMockRecorder) FindSubagentState(ctx, sessionID, toolCallID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSubagentState", reflect.TypeOf((*MockMessageRepo)(nil).FindSubagentState), ctx, sessionID, toolCallID)
}

// FlipSubagentStatus mocks base method.
func (m *MockMessageRepo) FlipSubagentStatus(ctx context.Context, sessionID int64, toolCallID, status, summary string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FlipSubagentStatus", ctx, sessionID, toolCallID, status, summary)
	ret0, _ := ret[0].(error)
	return ret0
}

// FlipSubagentStatus indicates an expected call of FlipSubagentStatus.
func (mr *MockMessageRepoMockRecorder) FlipSubagentStatus(ctx, sessionID, toolCallID, status, summary any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlipSubagentStatus", reflect.TypeOf((*MockMessageRepo)(nil).FlipSubagentStatus), ctx, sessionID, toolCallID, status, summary)
}

// LatestAssistant mocks base method.
func (m *MockMessageRepo) LatestAssistant(ctx context.Context, sessionID int64) (*chat_entity.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestAssistant", ctx, sessionID)
	ret0, _ := ret[0].(*chat_entity.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestAssistant indicates an expected call of LatestAssistant.
func (mr *MockMessageRepoMockRecorder) LatestAssistant(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestAssistant", reflect.TypeOf((*MockMessageRepo)(nil).LatestAssistant), ctx, sessionID)
}

// List mocks base method.
func (m *MockMessageRepo) List(ctx context.Context, sessionID int64) ([]*chat_entity.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, sessionID)
	ret0, _ := ret[0].([]*chat_entity.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMessageRepoMockRecorder) List(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMessageRepo)(nil).List), ctx, sessionID)
}

// ListMeta mocks base method.
func (m *MockMessageRepo) ListMeta(ctx context.Context, sessionID int64) ([]*chat_entity.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMeta", ctx, sessionID)
	ret0, _ := ret[0].([]*chat_entity.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMeta indicates an expected call of ListMeta.
func (mr *MockMessageRepoMockRecorder) ListMeta(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMeta", reflect.TypeOf((*MockMessageRepo)(nil).ListMeta), ctx, sessionID)
}

// NextSeq mocks base method.
func (m *MockMessageRepo) NextSeq(ctx context.Context, sessionID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextSeq", ctx, sessionID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextSeq indicates an expected call of NextSeq.
func (mr *MockMessageRepoMockRecorder) NextSeq(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextSeq", reflect.TypeOf((*MockMessageRepo)(nil).NextSeq), ctx, sessionID)
}

// PatchSubagentProgress mocks base method.
func (m *MockMessageRepo) PatchSubagentProgress(ctx context.Context, sessionID int64, toolCallID string, p chat_repo.SubagentProgress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchSubagentProgress", ctx, sessionID, toolCallID, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// PatchSubagentProgress indicates an expected call of PatchSubagentProgress.
func (mr *MockMessageRepoMockRecorder) PatchSubagentProgress(ctx, sessionID, toolCallID, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchSubagentProgress", reflect.TypeOf((*MockMessageRepo)(nil).PatchSubagentProgress), ctx, sessionID, toolCallID, p)
}

// Update mocks base method.
func (m_2 *MockMessageRepo) Update(ctx context.Context, m *chat_entity.Message) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMessageRepoMockRecorder) Update(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMessageRepo)(nil).Update), ctx, m)
}

// UpdateErrorText mocks base method.
func (m *MockMessageRepo) UpdateErrorText(ctx context.Context, id int64, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateErrorText", ctx, id, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateErrorText indicates an expected call of UpdateErrorText.
func (mr *MockMessageRepoMockRecorder) UpdateErrorText(ctx, id, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateErrorText", reflect.TypeOf((*MockMessageRepo)(nil).UpdateErrorText), ctx, id, text)
}

// UpdateUsage mocks base method.
func (m *MockMessageRepo) UpdateUsage(ctx context.Context, id int64, u chat_repo.MessageUsage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUsage", ctx, id, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUsage indicates an expected call of UpdateUsage.
func (mr *MockMessageRepoMockRecorder) UpdateUsage(ctx, id, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUsage", reflect.TypeOf((*MockMessageRepo)(nil).UpdateUsage), ctx, id, u)
}
