// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source ports.go -destination mock_handlers/mock_ports.go -package mock_handlers
//

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	context "context"
	reflect "reflect"
	time "time"

	handlers "github.com/agentre-hub/agentre/internal/daemon/handlers"
	state "github.com/agentre-hub/agentre/internal/daemon/state"
	agent_backend_entity "github.com/agentre-hub/agentre/internal/model/entity/agent_backend_entity"
	llm_provider_entity "github.com/agentre-hub/agentre/internal/model/entity/llm_provider_entity"
	agentrewire "github.com/agentre-hub/agentre/pkg/wire/agentrewire"
	gomock "go.uber.org/mock/gomock"
)

// MockStatePort is a mock of StatePort interface.
type MockStatePort struct {
	ctrl     *gomock.Controller
	recorder *MockStatePortMockRecorder
	isgomock struct{}
}

// MockStatePortMockRecorder is the mock recorder for MockStatePort.
type MockStatePortMockRecorder struct {
	mock *MockStatePort
}

// NewMockStatePort creates a new mock instance.
func NewMockStatePort(ctrl *gomock.Controller) *MockStatePort {
	mock := &MockStatePort{ctrl: ctrl}
	mock.recorder = &MockStatePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatePort) EXPECT() *MockStatePortMockRecorder {
	return m.recorder
}

// Mutate mocks base method.
func (m *MockStatePort) Mutate(arg0 func(*state.State)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Mutate", arg0)
}

// Mutate indicates an expected call of Mutate.
func (mr *MockStatePortMockRecorder) Mutate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mutate", reflect.TypeOf((*MockStatePort)(nil).Mutate), arg0)
}

// Save mocks base method.
func (m *MockStatePort) Save() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save")
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockStatePortMockRecorder) Save() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockStatePort)(nil).Save))
}

// Snapshot mocks base method.
func (m *MockStatePort) Snapshot() state.State {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot")
	ret0, _ := ret[0].(state.State)
	return ret0
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MockStatePortMockRecorder) Snapshot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*MockStatePort)(nil).Snapshot))
}

// MockNotifierPort is a mock of NotifierPort interface.
type MockNotifierPort struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierPortMockRecorder
	isgomock struct{}
}

// MockNotifierPortMockRecorder is the mock recorder for MockNotifierPort.
type MockNotifierPortMockRecorder struct {
	mock *MockNotifierPort
}

// NewMockNotifierPort creates a new mock instance.
func NewMockNotifierPort(ctrl *gomock.Controller) *MockNotifierPort {
	mock := &MockNotifierPort{ctrl: ctrl}
	mock.recorder = &MockNotifierPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifierPort) EXPECT() *MockNotifierPortMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockNotifierPort) Notify(notification *agentrewire.RpcNotification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockNotifierPortMockRecorder) Notify(notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockNotifierPort)(nil).Notify), notification)
}

// Request mocks base method.
func (m *MockNotifierPort) Request(ctx context.Context, method string, params, result any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request", ctx, method, params, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// Request indicates an expected call of Request.
func (mr *MockNotifierPortMockRecorder) Request(ctx, method, params, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockNotifierPort)(nil).Request), ctx, method, params, result)
}

// MockJournalPort is a mock of JournalPort interface.
type MockJournalPort struct {
	ctrl     *gomock.Controller
	recorder *MockJournalPortMockRecorder
	isgomock struct{}
}

// MockJournalPortMockRecorder is the mock recorder for MockJournalPort.
type MockJournalPortMockRecorder struct {
	mock *MockJournalPort
}

// NewMockJournalPort creates a new mock instance.
func NewMockJournalPort(ctrl *gomock.Controller) *MockJournalPort {
	mock := &MockJournalPort{ctrl: ctrl}
	mock.recorder = &MockJournalPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJournalPort) EXPECT() *MockJournalPortMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockJournalPort) Append(ctx context.Context, peerFingerprint, peerSessionID string, payload []byte) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, peerFingerprint, peerSessionID, payload)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Append indicates an expected call of Append.
func (mr *MockJournalPortMockRecorder) Append(ctx, peerFingerprint, peerSessionID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockJournalPort)(nil).Append), ctx, peerFingerprint, peerSessionID, payload)
}

// MockDBStatPort is a mock of DBStatPort interface.
type MockDBStatPort struct {
	ctrl     *gomock.Controller
	recorder *MockDBStatPortMockRecorder
	isgomock struct{}
}

// MockDBStatPortMockRecorder is the mock recorder for MockDBStatPort.
type MockDBStatPortMockRecorder struct {
	mock *MockDBStatPort
}

// NewMockDBStatPort creates a new mock instance.
func NewMockDBStatPort(ctrl *gomock.Controller) *MockDBStatPort {
	mock := &MockDBStatPort{ctrl: ctrl}
	mock.recorder = &MockDBStatPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBStatPort) EXPECT() *MockDBStatPortMockRecorder {
	return m.recorder
}

// DBStat mocks base method.
func (m *MockDBStatPort) DBStat() handlers.DBStat {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DBStat")
	ret0, _ := ret[0].(handlers.DBStat)
	return ret0
}

// DBStat indicates an expected call of DBStat.
func (mr *MockDBStatPortMockRecorder) DBStat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DBStat", reflect.TypeOf((*MockDBStatPort)(nil).DBStat))
}

// MockSessionLifecyclePort is a mock of SessionLifecyclePort interface.
type MockSessionLifecyclePort struct {
	ctrl     *gomock.Controller
	recorder *MockSessionLifecyclePortMockRecorder
	isgomock struct{}
}

// MockSessionLifecyclePortMockRecorder is the mock recorder for MockSessionLifecyclePort.
type MockSessionLifecyclePortMockRecorder struct {
	mock *MockSessionLifecyclePort
}

// NewMockSessionLifecyclePort creates a new mock instance.
func NewMockSessionLifecyclePort(ctrl *gomock.Controller) *MockSessionLifecyclePort {
	mock := &MockSessionLifecyclePort{ctrl: ctrl}
	mock.recorder = &MockSessionLifecyclePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionLifecyclePort) EXPECT() *MockSessionLifecyclePortMockRecorder {
	return m.recorder
}

// Finish mocks base method.
func (m *MockSessionLifecyclePort) Finish(ctx context.Context, peerFingerprint, peerSessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Finish", ctx, peerFingerprint, peerSessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Finish indicates an expected call of Finish.
func (mr *MockSessionLifecyclePortMockRecorder) Finish(ctx, peerFingerprint, peerSessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Finish", reflect.TypeOf((*MockSessionLifecyclePort)(nil).Finish), ctx, peerFingerprint, peerSessionID)
}

// Running mocks base method.
func (m *MockSessionLifecyclePort) Running(ctx context.Context, peerFingerprint, peerSessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Running", ctx, peerFingerprint, peerSessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Running indicates an expected call of Running.
func (mr *MockSessionLifecyclePortMockRecorder) Running(ctx, peerFingerprint, peerSessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Running", reflect.TypeOf((*MockSessionLifecyclePort)(nil).Running), ctx, peerFingerprint, peerSessionID)
}

// Start mocks base method.
func (m *MockSessionLifecyclePort) Start(ctx context.Context, rec handlers.SessionRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, rec)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockSessionLifecyclePortMockRecorder) Start(ctx, rec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockSessionLifecyclePort)(nil).Start), ctx, rec)
}

// MockSessionQueryPort is a mock of SessionQueryPort interface.
type MockSessionQueryPort struct {
	ctrl     *gomock.Controller
	recorder *MockSessionQueryPortMockRecorder
	isgomock struct{}
}

// MockSessionQueryPortMockRecorder is the mock recorder for MockSessionQueryPort.
type MockSessionQueryPortMockRecorder struct {
	mock *MockSessionQueryPort
}

// NewMockSessionQueryPort creates a new mock instance.
func NewMockSessionQueryPort(ctrl *gomock.Controller) *MockSessionQueryPort {
	mock := &MockSessionQueryPort{ctrl: ctrl}
	mock.recorder = &MockSessionQueryPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionQueryPort) EXPECT() *MockSessionQueryPortMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockSessionQueryPort) Find(ctx context.Context, peerFingerprint, peerSessionID string) (*handlers.SessionRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, peerFingerprint, peerSessionID)
	ret0, _ := ret[0].(*handlers.SessionRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockSessionQueryPortMockRecorder) Find(ctx, peerFingerprint, peerSessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockSessionQueryPort)(nil).Find), ctx, peerFingerprint, peerSessionID)
}

// List mocks base method.
func (m *MockSessionQueryPort) List(ctx context.Context, peerFingerprint, keyword string) ([]handlers.SessionRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, peerFingerprint, keyword)
	ret0, _ := ret[0].([]handlers.SessionRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSessionQueryPortMockRecorder) List(ctx, peerFingerprint, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSessionQueryPort)(nil).List), ctx, peerFingerprint, keyword)
}

// MockSessionDeletePort is a mock of SessionDeletePort interface.
type MockSessionDeletePort struct {
	ctrl     *gomock.Controller
	recorder *MockSessionDeletePortMockRecorder
	isgomock struct{}
}

// MockSessionDeletePortMockRecorder is the mock recorder for MockSessionDeletePort.
type MockSessionDeletePortMockRecorder struct {
	mock *MockSessionDeletePort
}

// NewMockSessionDeletePort creates a new mock instance.
func NewMockSessionDeletePort(ctrl *gomock.Controller) *MockSessionDeletePort {
	mock := &MockSessionDeletePort{ctrl: ctrl}
	mock.recorder = &MockSessionDeletePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionDeletePort) EXPECT() *MockSessionDeletePortMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockSessionDeletePort) Delete(ctx context.Context, peerFingerprint, peerSessionID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, peerFingerprint, peerSessionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockSessionDeletePortMockRecorder) Delete(ctx, peerFingerprint, peerSessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionDeletePort)(nil).Delete), ctx, peerFingerprint, peerSessionID)
}

// MockSessionModelTargetPort is a mock of SessionModelTargetPort interface.
type MockSessionModelTargetPort struct {
	ctrl     *gomock.Controller
	recorder *MockSessionModelTargetPortMockRecorder
	isgomock struct{}
}

// MockSessionModelTargetPortMockRecorder is the mock recorder for MockSessionModelTargetPort.
type MockSessionModelTargetPortMockRecorder struct {
	mock *MockSessionModelTargetPort
}

// NewMockSessionModelTargetPort creates a new mock instance.
func NewMockSessionModelTargetPort(ctrl *gomock.Controller) *MockSessionModelTargetPort {
	mock := &MockSessionModelTargetPort{ctrl: ctrl}
	mock.recorder = &MockSessionModelTargetPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionModelTargetPort) EXPECT() *MockSessionModelTargetPortMockRecorder {
	return m.recorder
}

// SetModelTarget mocks base method.
func (m *MockSessionModelTargetPort) SetModelTarget(ctx context.Context, peerFingerprint, peerSessionID, providerKey, modelKey string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetModelTarget", ctx, peerFingerprint, peerSessionID, providerKey, modelKey)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetModelTarget indicates an expected call of SetModelTarget.
func (mr *MockSessionModelTargetPortMockRecorder) SetModelTarget(ctx, peerFingerprint, peerSessionID, providerKey, modelKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetModelTarget", reflect.TypeOf((*MockSessionModelTargetPort)(nil).SetModelTarget), ctx, peerFingerprint, peerSessionID, providerKey, modelKey)
}

// MockSessionReasoningEffortPort is a mock of SessionReasoningEffortPort interface.
type MockSessionReasoningEffortPort struct {
	ctrl     *gomock.Controller
	recorder *MockSessionReasoningEffortPortMockRecorder
	isgomock struct{}
}

// MockSessionReasoningEffortPortMockRecorder is the mock recorder for MockSessionReasoningEffortPort.
type MockSessionReasoningEffortPortMockRecorder struct {
	mock *MockSessionReasoningEffortPort
}

// NewMockSessionReasoningEffortPort creates a new mock instance.
func NewMockSessionReasoningEffortPort(ctrl *gomock.Controller) *MockSessionReasoningEffortPort {
	mock := &MockSessionReasoningEffortPort{ctrl: ctrl}
	mock.recorder = &MockSessionReasoningEffortPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionReasoningEffortPort) EXPECT() *MockSessionReasoningEffortPortMockRecorder {
	return m.recorder
}

// SetReasoningEffort mocks base method.
func (m *MockSessionReasoningEffortPort) SetReasoningEffort(ctx context.Context, peerFingerprint, peerSessionID, reasoningEffort string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetReasoningEffort", ctx, peerFingerprint, peerSessionID, reasoningEffort)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetReasoningEffort indicates an expected call of SetReasoningEffort.
func (mr *MockSessionReasoningEffortPortMockRecorder) SetReasoningEffort(ctx, peerFingerprint, peerSessionID, reasoningEffort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReasoningEffort", reflect.TypeOf((*MockSessionReasoningEffortPort)(nil).SetReasoningEffort), ctx, peerFingerprint, peerSessionID, reasoningEffort)
}

// MockJournalPurgePort is a mock of JournalPurgePort interface.
type MockJournalPurgePort struct {
	ctrl     *gomock.Controller
	recorder *MockJournalPurgePortMockRecorder
	isgomock struct{}
}

// MockJournalPurgePortMockRecorder is the mock recorder for MockJournalPurgePort.
type MockJournalPurgePortMockRecorder struct {
	mock *MockJournalPurgePort
}

// NewMockJournalPurgePort creates a new mock instance.
func NewMockJournalPurgePort(ctrl *gomock.Controller) *MockJournalPurgePort {
	mock := &MockJournalPurgePort{ctrl: ctrl}
	mock.recorder = &MockJournalPurgePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJournalPurgePort) EXPECT() *MockJournalPurgePortMockRecorder {
	return m.recorder
}

// DeleteAll mocks base method.
func (m *MockJournalPurgePort) DeleteAll(ctx context.Context, peerFingerprint, peerSessionID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAll", ctx, peerFingerprint, peerSessionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAll indicates an expected call of DeleteAll.
func (mr *MockJournalPurgePortMockRecorder) DeleteAll(ctx, peerFingerprint, peerSessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MockJournalPurgePort)(nil).DeleteAll), ctx, peerFingerprint, peerSessionID)
}

// MockSteerSourcePort is a mock of SteerSourcePort interface.
type MockSteerSourcePort struct {
	ctrl     *gomock.Controller
	recorder *MockSteerSourcePortMockRecorder
	isgomock struct{}
}

// MockSteerSourcePortMockRecorder is the mock recorder for MockSteerSourcePort.
type MockSteerSourcePortMockRecorder struct {
	mock *MockSteerSourcePort
}

// NewMockSteerSourcePort creates a new mock instance.
func NewMockSteerSourcePort(ctrl *gomock.Controller) *MockSteerSourcePort {
	mock := &MockSteerSourcePort{ctrl: ctrl}
	mock.recorder = &MockSteerSourcePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSteerSourcePort) EXPECT() *MockSteerSourcePortMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockSteerSourcePort) Consume(queuedID string) (handlers.SteerSourceEntry, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", queuedID)
	ret0, _ := ret[0].(handlers.SteerSourceEntry)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Consume indicates an expected call of Consume.
func (mr *MockSteerSourcePortMockRecorder) Consume(queuedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockSteerSourcePort)(nil).Consume), queuedID)
}

// Forget mocks base method.
func (m *MockSteerSourcePort) Forget(queuedID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Forget", queuedID)
}

// Forget indicates an expected call of Forget.
func (mr *MockSteerSourcePortMockRecorder) Forget(queuedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Forget", reflect.TypeOf((*MockSteerSourcePort)(nil).Forget), queuedID)
}

// Record mocks base method.
func (m *MockSteerSourcePort) Record(queuedID string, entry handlers.SteerSourceEntry) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Record", queuedID, entry)
}

// Record indicates an expected call of Record.
func (mr *MockSteerSourcePortMockRecorder) Record(queuedID, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockSteerSourcePort)(nil).Record), queuedID, entry)
}

// MockJournalReaderPort is a mock of JournalReaderPort interface.
type MockJournalReaderPort struct {
	ctrl     *gomock.Controller
	recorder *MockJournalReaderPortMockRecorder
	isgomock struct{}
}

// MockJournalReaderPortMockRecorder is the mock recorder for MockJournalReaderPort.
type MockJournalReaderPortMockRecorder struct {
	mock *MockJournalReaderPort
}

// NewMockJournalReaderPort creates a new mock instance.
func NewMockJournalReaderPort(ctrl *gomock.Controller) *MockJournalReaderPort {
	mock := &MockJournalReaderPort{ctrl: ctrl}
	mock.recorder = &MockJournalReaderPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJournalReaderPort) EXPECT() *MockJournalReaderPortMockRecorder {
	return m.recorder
}

// LatestSeq mocks base method.
func (m *MockJournalReaderPort) LatestSeq(ctx context.Context, peerFingerprint, peerSessionID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestSeq", ctx, peerFingerprint, peerSessionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestSeq indicates an expected call of LatestSeq.
func (mr *MockJournalReaderPortMockRecorder) LatestSeq(ctx, peerFingerprint, peerSessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestSeq", reflect.TypeOf((*MockJournalReaderPort)(nil).LatestSeq), ctx, peerFingerprint, peerSessionID)
}

// LatestSeqByPeer mocks base method.
func (m *MockJournalReaderPort) LatestSeqByPeer(ctx context.Context, peerFingerprint string) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestSeqByPeer", ctx, peerFingerprint)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestSeqByPeer indicates an expected call of LatestSeqByPeer.
func (mr *MockJournalReaderPortMockRecorder) LatestSeqByPeer(ctx, peerFingerprint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestSeqByPeer", reflect.TypeOf((*MockJournalReaderPort)(nil).LatestSeqByPeer), ctx, peerFingerprint)
}

// ListSince mocks base method.
func (m *MockJournalReaderPort) ListSince(ctx context.Context, peerFingerprint, peerSessionID string, cursor int64, limit int) ([]handlers.JournalRow, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSince", ctx, peerFingerprint, peerSessionID, cursor, limit)
	ret0, _ := ret[0].([]handlers.JournalRow)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSince indicates an expected call of ListSince.
func (mr *MockJournalReaderPortMockRecorder) ListSince(ctx, peerFingerprint, peerSessionID, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSince", reflect.TypeOf((*MockJournalReaderPort)(nil).ListSince), ctx, peerFingerprint, peerSessionID, cursor, limit)
}

// OldestSeq mocks base method.
func (m *MockJournalReaderPort) OldestSeq(ctx context.Context, peerFingerprint, peerSessionID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OldestSeq", ctx, peerFingerprint, peerSessionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OldestSeq indicates an expected call of OldestSeq.
func (mr *MockJournalReaderPortMockRecorder) OldestSeq(ctx, peerFingerprint, peerSessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OldestSeq", reflect.TypeOf((*MockJournalReaderPort)(nil).OldestSeq), ctx, peerFingerprint, peerSessionID)
}

// MockGatewayPort is a mock of GatewayPort interface.
type MockGatewayPort struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayPortMockRecorder
	isgomock struct{}
}

// MockGatewayPortMockRecorder is the mock recorder for MockGatewayPort.
type MockGatewayPortMockRecorder struct {
	mock *MockGatewayPort
}

// NewMockGatewayPort creates a new mock instance.
func NewMockGatewayPort(ctrl *gomock.Controller) *MockGatewayPort {
	mock := &MockGatewayPort{ctrl: ctrl}
	mock.recorder = &MockGatewayPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGatewayPort) EXPECT() *MockGatewayPortMockRecorder {
	return m.recorder
}

// IssueToken mocks base method.
func (m *MockGatewayPort) IssueToken(ctx context.Context, b *agent_backend_entity.AgentBackend, ttl time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueToken", ctx, b, ttl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueToken indicates an expected call of IssueToken.
func (mr *MockGatewayPortMockRecorder) IssueToken(ctx, b, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueToken", reflect.TypeOf((*MockGatewayPort)(nil).IssueToken), ctx, b, ttl)
}

// IssueTokenFor mocks base method.
func (m *MockGatewayPort) IssueTokenFor(ctx context.Context, b *agent_backend_entity.AgentBackend, providerKey, modelKey string, ttl time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueTokenFor", ctx, b, providerKey, modelKey, ttl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueTokenFor indicates an expected call of IssueTokenFor.
func (mr *MockGatewayPortMockRecorder) IssueTokenFor(ctx, b, providerKey, modelKey, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueTokenFor", reflect.TypeOf((*MockGatewayPort)(nil).IssueTokenFor), ctx, b, providerKey, modelKey, ttl)
}

// RevokeToken mocks base method.
func (m *MockGatewayPort) RevokeToken(token string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RevokeToken", token)
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *MockGatewayPortMockRecorder) RevokeToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*MockGatewayPort)(nil).RevokeToken), token)
}

// SetTokenTarget mocks base method.
func (m *MockGatewayPort) SetTokenTarget(token, providerKey, modelKey string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTokenTarget", token, providerKey, modelKey)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// SetTokenTarget indicates an expected call of SetTokenTarget.
func (mr *MockGatewayPortMockRecorder) SetTokenTarget(token, providerKey, modelKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTokenTarget", reflect.TypeOf((*MockGatewayPort)(nil).SetTokenTarget), token, providerKey, modelKey)
}

// URL mocks base method.
func (m *MockGatewayPort) URL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "URL")
	ret0, _ := ret[0].(string)
	return ret0
}

// URL indicates an expected call of URL.
func (mr *MockGatewayPortMockRecorder) URL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "URL", reflect.TypeOf((*MockGatewayPort)(nil).URL))
}

// MockLLMProviderLookupPort is a mock of LLMProviderLookupPort interface.
type MockLLMProviderLookupPort struct {
	ctrl     *gomock.Controller
	recorder *MockLLMProviderLookupPortMockRecorder
	isgomock struct{}
}

// MockLLMProviderLookupPortMockRecorder is the mock recorder for MockLLMProviderLookupPort.
type MockLLMProviderLookupPortMockRecorder struct {
	mock *MockLLMProviderLookupPort
}

// NewMockLLMProviderLookupPort creates a new mock instance.
func NewMockLLMProviderLookupPort(ctrl *gomock.Controller) *MockLLMProviderLookupPort {
	mock := &MockLLMProviderLookupPort{ctrl: ctrl}
	mock.recorder = &MockLLMProviderLookupPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMProviderLookupPort) EXPECT() *MockLLMProviderLookupPortMockRecorder {
	return m.recorder
}

// FindByKey mocks base method.
func (m *MockLLMProviderLookupPort) FindByKey(ctx context.Context, key string) (*llm_provider_entity.LLMProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByKey", ctx, key)
	ret0, _ := ret[0].(*llm_provider_entity.LLMProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByKey indicates an expected call of FindByKey.
func (mr *MockLLMProviderLookupPortMockRecorder) FindByKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByKey", reflect.TypeOf((*MockLLMProviderLookupPort)(nil).FindByKey), ctx, key)
}

// ResolveModel mocks base method.
func (m *MockLLMProviderLookupPort) ResolveModel(ctx context.Context, providerKey, modelKey string) (handlers.EffectiveModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveModel", ctx, providerKey, modelKey)
	ret0, _ := ret[0].(handlers.EffectiveModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveModel indicates an expected call of ResolveModel.
func (mr *MockLLMProviderLookupPortMockRecorder) ResolveModel(ctx, providerKey, modelKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveModel", reflect.TypeOf((*MockLLMProviderLookupPort)(nil).ResolveModel), ctx, providerKey, modelKey)
}
