// Code generated by MockGen. DO NOT EDIT.
// Source: exec_target_override.go
//
// Generated by this command:
//
//	mockgen -source exec_target_override.go -destination mock_agent_repo/mock_exec_target_override.go
//

// Package mock_agent_repo is a generated GoMock package.
package mock_agent_repo

import (
	context "context"
	reflect "reflect"

	agent_entity "github.com/agentre-hub/agentre/internal/model/entity/agent_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentExecTargetOverrideRepo is a mock of AgentExecTargetOverrideRepo interface.
type MockAgentExecTargetOverrideRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAgentExecTargetOverrideRepoMockRecorder
	isgomock struct{}
}

// MockAgentExecTargetOverrideRepoMockRecorder is the mock recorder for MockAgentExecTargetOverrideRepo.
type MockAgentExecTargetOverrideRepoMockRecorder struct {
	mock *MockAgentExecTargetOverrideRepo
}

// NewMockAgentExecTargetOverrideRepo creates a new mock instance.
func NewMockAgentExecTargetOverrideRepo(ctrl *gomock.Controller) *MockAgentExecTargetOverrideRepo {
	mock := &MockAgentExecTargetOverrideRepo{ctrl: ctrl}
	mock.recorder = &MockAgentExecTargetOverrideRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentExecTargetOverrideRepo) EXPECT() *MockAgentExecTargetOverrideRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockAgentExecTargetOverrideRepo) Delete(ctx context.Context, agentID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, agentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAgentExecTargetOverrideRepoMockRecorder) Delete(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAgentExecTargetOverrideRepo)(nil).Delete), ctx, agentID)
}

// Get mocks base method.
func (m *MockAgentExecTargetOverrideRepo) Get(ctx context.Context, agentID int64) (*agent_entity.AgentExecTargetOverride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, agentID)
	ret0, _ := ret[0].(*agent_entity.AgentExecTargetOverride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAgentExecTargetOverrideRepoMockRecorder) Get(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAgentExecTargetOverrideRepo)(nil).Get), ctx, agentID)
}

// Save mocks base method.
func (m *MockAgentExecTargetOverrideRepo) Save(ctx context.Context, o *agent_entity.AgentExecTargetOverride) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, o)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockAgentExecTargetOverrideRepoMockRecorder) Save(ctx, o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAgentExecTargetOverrideRepo)(nil).Save), ctx, o)
}
