// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source deps.go -destination mock_hooktool_svc/mock_deps.go
//

// Package mock_hooktool_svc is a generated GoMock package.
package mock_hooktool_svc

import (
	context "context"
	reflect "reflect"

	agent_entity "github.com/agentre-hub/agentre/internal/model/entity/agent_entity"
	blocks "github.com/agentre-hub/agentre/internal/service/chat_svc/blocks"
	hook_svc "github.com/agentre-hub/agentre/internal/service/hook_svc"
	gomock "go.uber.org/mock/gomock"
)

// MockHookService is a mock of HookService interface.
type MockHookService struct {
	ctrl     *gomock.Controller
	recorder *MockHookServiceMockRecorder
	isgomock struct{}
}

// MockHookServiceMockRecorder is the mock recorder for MockHookService.
type MockHookServiceMockRecorder struct {
	mock *MockHookService
}

// NewMockHookService creates a new mock instance.
func NewMockHookService(ctrl *gomock.Controller) *MockHookService {
	mock := &MockHookService{ctrl: ctrl}
	mock.recorder = &MockHookServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHookService) EXPECT() *MockHookServiceMockRecorder {
	return m.recorder
}

// CreateHook mocks base method.
func (m *MockHookService) CreateHook(ctx context.Context, req *hook_svc.CreateHookRequest) (*hook_svc.HookItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHook", ctx, req)
	ret0, _ := ret[0].(*hook_svc.HookItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateHook indicates an expected call of CreateHook.
func (mr *MockHookServiceMockRecorder) CreateHook(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHook", reflect.TypeOf((*MockHookService)(nil).CreateHook), ctx, req)
}

// DeleteHook mocks base method.
func (m *MockHookService) DeleteHook(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHook", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteHook indicates an expected call of DeleteHook.
func (mr *MockHookServiceMockRecorder) DeleteHook(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHook", reflect.TypeOf((*MockHookService)(nil).DeleteHook), ctx, id)
}

// Load mocks base method.
func (m *MockHookService) Load(ctx context.Context, req *hook_svc.LoadHooksRequest) (*hook_svc.LoadHooksResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, req)
	ret0, _ := ret[0].(*hook_svc.LoadHooksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockHookServiceMockRecorder) Load(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockHookService)(nil).Load), ctx, req)
}

// RunHook mocks base method.
func (m *MockHookService) RunHook(ctx context.Context, req *hook_svc.RunHookRequest) (*hook_svc.RunHookResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunHook", ctx, req)
	ret0, _ := ret[0].(*hook_svc.RunHookResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunHook indicates an expected call of RunHook.
func (mr *MockHookServiceMockRecorder) RunHook(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunHook", reflect.TypeOf((*MockHookService)(nil).RunHook), ctx, req)
}

// UpdateHook mocks base method.
func (m *MockHookService) UpdateHook(ctx context.Context, req *hook_svc.UpdateHookRequest) (*hook_svc.HookItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHook", ctx, req)
	ret0, _ := ret[0].(*hook_svc.HookItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateHook indicates an expected call of UpdateHook.
func (mr *MockHookServiceMockRecorder) UpdateHook(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHook", reflect.TypeOf((*MockHookService)(nil).UpdateHook), ctx, req)
}

// MockAgentLookup is a mock of AgentLookup interface.
type MockAgentLookup struct {
	ctrl     *gomock.Controller
	recorder *MockAgentLookupMockRecorder
	isgomock struct{}
}

// MockAgentLookupMockRecorder is the mock recorder for MockAgentLookup.
type MockAgentLookupMockRecorder struct {
	mock *MockAgentLookup
}

// NewMockAgentLookup creates a new mock instance.
func NewMockAgentLookup(ctrl *gomock.Controller) *MockAgentLookup {
	mock := &MockAgentLookup{ctrl: ctrl}
	mock.recorder = &MockAgentLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentLookup) EXPECT() *MockAgentLookupMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockAgentLookup) Find(ctx context.Context, id int64) (*agent_entity.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*agent_entity.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockAgentLookupMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAgentLookup)(nil).Find), ctx, id)
}

// MockApprovalGateway is a mock of ApprovalGateway interface.
type MockApprovalGateway struct {
	ctrl     *gomock.Controller
	recorder *MockApprovalGatewayMockRecorder
	isgomock struct{}
}

// MockApprovalGatewayMockRecorder is the mock recorder for MockApprovalGateway.
type MockApprovalGatewayMockRecorder struct {
	mock *MockApprovalGateway
}

// NewMockApprovalGateway creates a new mock instance.
func NewMockApprovalGateway(ctrl *gomock.Controller) *MockApprovalGateway {
	mock := &MockApprovalGateway{ctrl: ctrl}
	mock.recorder = &MockApprovalGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApprovalGateway) EXPECT() *MockApprovalGatewayMockRecorder {
	return m.recorder
}

// BeginToolApproval mocks base method.
func (m *MockApprovalGateway) BeginToolApproval(ctx context.Context, sessionID int64, blk *blocks.ToolApprovalBlock) (<-chan bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginToolApproval", ctx, sessionID, blk)
	ret0, _ := ret[0].(<-chan bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginToolApproval indicates an expected call of BeginToolApproval.
func (mr *MockApprovalGatewayMockRecorder) BeginToolApproval(ctx, sessionID, blk any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginToolApproval", reflect.TypeOf((*MockApprovalGateway)(nil).BeginToolApproval), ctx, sessionID, blk)
}

// FinishToolApproval mocks base method.
func (m *MockApprovalGateway) FinishToolApproval(ctx context.Context, sessionID int64, requestID, status, result string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishToolApproval", ctx, sessionID, requestID, status, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// FinishToolApproval indicates an expected call of FinishToolApproval.
func (mr *MockApprovalGatewayMockRecorder) FinishToolApproval(ctx, sessionID, requestID, status, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishToolApproval", reflect.TypeOf((*MockApprovalGateway)(nil).FinishToolApproval), ctx, sessionID, requestID, status, result)
}
