// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source ports.go -destination mock_ctl_svc/mock_ports.go
//

// Package mock_ctl_svc is a generated GoMock package.
package mock_ctl_svc

import (
	context "context"
	reflect "reflect"

	project_entity "github.com/agentre-hub/agentre/internal/model/entity/project_entity"
	agent_backend_svc "github.com/agentre-hub/agentre/internal/service/agent_backend_svc"
	agent_svc "github.com/agentre-hub/agentre/internal/service/agent_svc"
	department_svc "github.com/agentre-hub/agentre/internal/service/department_svc"
	llm_provider_svc "github.com/agentre-hub/agentre/internal/service/llm_provider_svc"
	project_svc "github.com/agentre-hub/agentre/internal/service/project_svc"
	remote_device_svc "github.com/agentre-hub/agentre/internal/service/remote_device_svc"
	gomock "go.uber.org/mock/gomock"
)

// MockDepartmentService is a mock of DepartmentService interface.
type MockDepartmentService struct {
	ctrl     *gomock.Controller
	recorder *MockDepartmentServiceMockRecorder
	isgomock struct{}
}

// MockDepartmentServiceMockRecorder is the mock recorder for MockDepartmentService.
type MockDepartmentServiceMockRecorder struct {
	mock *MockDepartmentService
}

// NewMockDepartmentService creates a new mock instance.
func NewMockDepartmentService(ctrl *gomock.Controller) *MockDepartmentService {
	mock := &MockDepartmentService{ctrl: ctrl}
	mock.recorder = &MockDepartmentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepartmentService) EXPECT() *MockDepartmentServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDepartmentService) Create(ctx context.Context, req *department_svc.CreateDepartmentRequest) (*department_svc.CreateDepartmentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*department_svc.CreateDepartmentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDepartmentServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDepartmentService)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockDepartmentService) Delete(ctx context.Context, req *department_svc.DeleteDepartmentRequest) (*department_svc.DeleteDepartmentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, req)
	ret0, _ := ret[0].(*department_svc.DeleteDepartmentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockDepartmentServiceMockRecorder) Delete(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDepartmentService)(nil).Delete), ctx, req)
}

// Load mocks base method.
func (m *MockDepartmentService) Load(ctx context.Context, req *department_svc.LoadOrgRequest) (*department_svc.LoadOrgResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, req)
	ret0, _ := ret[0].(*department_svc.LoadOrgResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockDepartmentServiceMockRecorder) Load(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockDepartmentService)(nil).Load), ctx, req)
}

// Move mocks base method.
func (m *MockDepartmentService) Move(ctx context.Context, req *department_svc.MoveDepartmentRequest) (*department_svc.MoveDepartmentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Move", ctx, req)
	ret0, _ := ret[0].(*department_svc.MoveDepartmentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Move indicates an expected call of Move.
func (mr *MockDepartmentServiceMockRecorder) Move(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Move", reflect.TypeOf((*MockDepartmentService)(nil).Move), ctx, req)
}

// Update mocks base method.
func (m *MockDepartmentService) Update(ctx context.Context, req *department_svc.UpdateDepartmentRequest) (*department_svc.UpdateDepartmentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(*department_svc.UpdateDepartmentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDepartmentServiceMockRecorder) Update(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDepartmentService)(nil).Update), ctx, req)
}

// MockAgentService is a mock of AgentService interface.
type MockAgentService struct {
	ctrl     *gomock.Controller
	recorder *MockAgentServiceMockRecorder
	isgomock struct{}
}

// MockAgentServiceMockRecorder is the mock recorder for MockAgentService.
type MockAgentServiceMockRecorder struct {
	mock *MockAgentService
}

// NewMockAgentService creates a new mock instance.
func NewMockAgentService(ctrl *gomock.Controller) *MockAgentService {
	mock := &MockAgentService{ctrl: ctrl}
	mock.recorder = &MockAgentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentService) EXPECT() *MockAgentServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAgentService) Create(ctx context.Context, req *agent_svc.CreateAgentRequest) (*agent_svc.CreateAgentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*agent_svc.CreateAgentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAgentServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAgentService)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockAgentService) Delete(ctx context.Context, req *agent_svc.DeleteAgentRequest) (*agent_svc.DeleteAgentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, req)
	ret0, _ := ret[0].(*agent_svc.DeleteAgentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockAgentServiceMockRecorder) Delete(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAgentService)(nil).Delete), ctx, req)
}

// Move mocks base method.
func (m *MockAgentService) Move(ctx context.Context, req *agent_svc.MoveAgentRequest) (*agent_svc.MoveAgentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Move", ctx, req)
	ret0, _ := ret[0].(*agent_svc.MoveAgentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Move indicates an expected call of Move.
func (mr *MockAgentServiceMockRecorder) Move(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Move", reflect.TypeOf((*MockAgentService)(nil).Move), ctx, req)
}

// SetPinned mocks base method.
func (m *MockAgentService) SetPinned(ctx context.Context, req *agent_svc.SetPinnedRequest) (*agent_svc.SetPinnedResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPinned", ctx, req)
	ret0, _ := ret[0].(*agent_svc.SetPinnedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetPinned indicates an expected call of SetPinned.
func (mr *MockAgentServiceMockRecorder) SetPinned(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPinned", reflect.TypeOf((*MockAgentService)(nil).SetPinned), ctx, req)
}

// Update mocks base method.
func (m *MockAgentService) Update(ctx context.Context, req *agent_svc.UpdateAgentRequest) (*agent_svc.UpdateAgentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(*agent_svc.UpdateAgentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAgentServiceMockRecorder) Update(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAgentService)(nil).Update), ctx, req)
}

// MockProjectService is a mock of ProjectService interface.
type MockProjectService struct {
	ctrl     *gomock.Controller
	recorder *MockProjectServiceMockRecorder
	isgomock struct{}
}

// MockProjectServiceMockRecorder is the mock recorder for MockProjectService.
type MockProjectServiceMockRecorder struct {
	mock *MockProjectService
}

// NewMockProjectService creates a new mock instance.
func NewMockProjectService(ctrl *gomock.Controller) *MockProjectService {
	mock := &MockProjectService{ctrl: ctrl}
	mock.recorder = &MockProjectServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectService) EXPECT() *MockProjectServiceMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockProjectService) AddMember(ctx context.Context, projectID, agentID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", ctx, projectID, agentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMember indicates an expected call of AddMember.
func (mr *MockProjectServiceMockRecorder) AddMember(ctx, projectID, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockProjectService)(nil).AddMember), ctx, projectID, agentID)
}

// ClearLocalPath mocks base method.
func (m *MockProjectService) ClearLocalPath(ctx context.Context, id int64) (*project_entity.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearLocalPath", ctx, id)
	ret0, _ := ret[0].(*project_entity.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClearLocalPath indicates an expected call of ClearLocalPath.
func (mr *MockProjectServiceMockRecorder) ClearLocalPath(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearLocalPath", reflect.TypeOf((*MockProjectService)(nil).ClearLocalPath), ctx, id)
}

// Create mocks base method.
func (m *MockProjectService) Create(ctx context.Context, req *project_svc.CreateProjectRequest) (*project_entity.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*project_entity.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockProjectServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProjectService)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockProjectService) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProjectServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProjectService)(nil).Delete), ctx, id)
}

// Move mocks base method.
func (m *MockProjectService) Move(ctx context.Context, req *project_svc.MoveProjectRequest) (*project_entity.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Move", ctx, req)
	ret0, _ := ret[0].(*project_entity.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Move indicates an expected call of Move.
func (mr *MockProjectServiceMockRecorder) Move(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Move", reflect.TypeOf((*MockProjectService)(nil).Move), ctx, req)
}

// RemoveMember mocks base method.
func (m *MockProjectService) RemoveMember(ctx context.Context, projectID, agentID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, projectID, agentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockProjectServiceMockRecorder) RemoveMember(ctx, projectID, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockProjectService)(nil).RemoveMember), ctx, projectID, agentID)
}

// SetLocalPath mocks base method.
func (m *MockProjectService) SetLocalPath(ctx context.Context, id int64, path string) (*project_entity.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLocalPath", ctx, id, path)
	ret0, _ := ret[0].(*project_entity.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetLocalPath indicates an expected call of SetLocalPath.
func (mr *MockProjectServiceMockRecorder) SetLocalPath(ctx, id, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLocalPath", reflect.TypeOf((*MockProjectService)(nil).SetLocalPath), ctx, id, path)
}

// Update mocks base method.
func (m *MockProjectService) Update(ctx context.Context, req *project_svc.UpdateProjectRequest) (*project_entity.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(*project_entity.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockProjectServiceMockRecorder) Update(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProjectService)(nil).Update), ctx, req)
}

// MockProviderService is a mock of ProviderService interface.
type MockProviderService struct {
	ctrl     *gomock.Controller
	recorder *MockProviderServiceMockRecorder
	isgomock struct{}
}

// MockProviderServiceMockRecorder is the mock recorder for MockProviderService.
type MockProviderServiceMockRecorder struct {
	mock *MockProviderService
}

// NewMockProviderService creates a new mock instance.
func NewMockProviderService(ctrl *gomock.Controller) *MockProviderService {
	mock := &MockProviderService{ctrl: ctrl}
	mock.recorder = &MockProviderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderService) EXPECT() *MockProviderServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProviderService) Create(ctx context.Context, req *llm_provider_svc.CreateProviderRequest) (*llm_provider_svc.CreateProviderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*llm_provider_svc.CreateProviderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockProviderServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProviderService)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockProviderService) Delete(ctx context.Context, req *llm_provider_svc.DeleteProviderRequest) (*llm_provider_svc.DeleteProviderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, req)
	ret0, _ := ret[0].(*llm_provider_svc.DeleteProviderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockProviderServiceMockRecorder) Delete(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProviderService)(nil).Delete), ctx, req)
}

// DeleteModel mocks base method.
func (m *MockProviderService) DeleteModel(ctx context.Context, req *llm_provider_svc.DeleteModelRequest) (*llm_provider_svc.DeleteModelResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteModel", ctx, req)
	ret0, _ := ret[0].(*llm_provider_svc.DeleteModelResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteModel indicates an expected call of DeleteModel.
func (mr *MockProviderServiceMockRecorder) DeleteModel(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteModel", reflect.TypeOf((*MockProviderService)(nil).DeleteModel), ctx, req)
}

// ImportModels mocks base method.
func (m *MockProviderService) ImportModels(ctx context.Context, req *llm_provider_svc.ImportModelsRequest) (*llm_provider_svc.ImportModelsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportModels", ctx, req)
	ret0, _ := ret[0].(*llm_provider_svc.ImportModelsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportModels indicates an expected call of ImportModels.
func (mr *MockProviderServiceMockRecorder) ImportModels(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportModels", reflect.TypeOf((*MockProviderService)(nil).ImportModels), ctx, req)
}

// List mocks base method.
func (m *MockProviderService) List(ctx context.Context, req *llm_provider_svc.ListProvidersRequest) (*llm_provider_svc.ListProvidersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, req)
	ret0, _ := ret[0].(*llm_provider_svc.ListProvidersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockProviderServiceMockRecorder) List(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProviderService)(nil).List), ctx, req)
}

// ListModels mocks base method.
func (m *MockProviderService) ListModels(ctx context.Context, req *llm_provider_svc.ListModelsRequest) (*llm_provider_svc.ListModelsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModels", ctx, req)
	ret0, _ := ret[0].(*llm_provider_svc.ListModelsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModels indicates an expected call of ListModels.
func (mr *MockProviderServiceMockRecorder) ListModels(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModels", reflect.TypeOf((*MockProviderService)(nil).ListModels), ctx, req)
}

// SetModelDefault mocks base method.
func (m *MockProviderService) SetModelDefault(ctx context.Context, req *llm_provider_svc.SetModelDefaultRequest) (*llm_provider_svc.SetModelDefaultResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetModelDefault", ctx, req)
	ret0, _ := ret[0].(*llm_provider_svc.SetModelDefaultResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetModelDefault indicates an expected call of SetModelDefault.
func (mr *MockProviderServiceMockRecorder) SetModelDefault(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetModelDefault", reflect.TypeOf((*MockProviderService)(nil).SetModelDefault), ctx, req)
}

// SetModelEnabled mocks base method.
func (m *MockProviderService) SetModelEnabled(ctx context.Context, req *llm_provider_svc.SetModelEnabledRequest) (*llm_provider_svc.SetModelEnabledResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetModelEnabled", ctx, req)
	ret0, _ := ret[0].(*llm_provider_svc.SetModelEnabledResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetModelEnabled indicates an expected call of SetModelEnabled.
func (mr *MockProviderServiceMockRecorder) SetModelEnabled(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetModelEnabled", reflect.TypeOf((*MockProviderService)(nil).SetModelEnabled), ctx, req)
}

// SetProviderEnabled mocks base method.
func (m *MockProviderService) SetProviderEnabled(ctx context.Context, req *llm_provider_svc.SetProviderEnabledRequest) (*llm_provider_svc.SetProviderEnabledResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProviderEnabled", ctx, req)
	ret0, _ := ret[0].(*llm_provider_svc.SetProviderEnabledResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetProviderEnabled indicates an expected call of SetProviderEnabled.
func (mr *MockProviderServiceMockRecorder) SetProviderEnabled(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProviderEnabled", reflect.TypeOf((*MockProviderService)(nil).SetProviderEnabled), ctx, req)
}

// Update mocks base method.
func (m *MockProviderService) Update(ctx context.Context, req *llm_provider_svc.UpdateProviderRequest) (*llm_provider_svc.UpdateProviderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(*llm_provider_svc.UpdateProviderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockProviderServiceMockRecorder) Update(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProviderService)(nil).Update), ctx, req)
}

// UpdateModel mocks base method.
func (m *MockProviderService) UpdateModel(ctx context.Context, req *llm_provider_svc.UpdateModelRequest) (*llm_provider_svc.UpdateModelResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateModel", ctx, req)
	ret0, _ := ret[0].(*llm_provider_svc.UpdateModelResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateModel indicates an expected call of UpdateModel.
func (mr *MockProviderServiceMockRecorder) UpdateModel(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateModel", reflect.TypeOf((*MockProviderService)(nil).UpdateModel), ctx, req)
}

// MockBackendService is a mock of BackendService interface.
type MockBackendService struct {
	ctrl     *gomock.Controller
	recorder *MockBackendServiceMockRecorder
	isgomock struct{}
}

// MockBackendServiceMockRecorder is the mock recorder for MockBackendService.
type MockBackendServiceMockRecorder struct {
	mock *MockBackendService
}

// NewMockBackendService creates a new mock instance.
func NewMockBackendService(ctrl *gomock.Controller) *MockBackendService {
	mock := &MockBackendService{ctrl: ctrl}
	mock.recorder = &MockBackendServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackendService) EXPECT() *MockBackendServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBackendService) Create(ctx context.Context, req *agent_backend_svc.CreateBackendRequest) (*agent_backend_svc.CreateBackendResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*agent_backend_svc.CreateBackendResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockBackendServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBackendService)(nil).Create), ctx, req)
}

// CreateOpenClaw mocks base method.
func (m *MockBackendService) CreateOpenClaw(ctx context.Context, req *agent_backend_svc.CreateBackendRequest, token string) (*agent_backend_svc.CreateBackendResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOpenClaw", ctx, req, token)
	ret0, _ := ret[0].(*agent_backend_svc.CreateBackendResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOpenClaw indicates an expected call of CreateOpenClaw.
func (mr *MockBackendServiceMockRecorder) CreateOpenClaw(ctx, req, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOpenClaw", reflect.TypeOf((*MockBackendService)(nil).CreateOpenClaw), ctx, req, token)
}

// Delete mocks base method.
func (m *MockBackendService) Delete(ctx context.Context, req *agent_backend_svc.DeleteBackendRequest) (*agent_backend_svc.DeleteBackendResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, req)
	ret0, _ := ret[0].(*agent_backend_svc.DeleteBackendResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockBackendServiceMockRecorder) Delete(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBackendService)(nil).Delete), ctx, req)
}

// List mocks base method.
func (m *MockBackendService) List(ctx context.Context, req *agent_backend_svc.ListBackendsRequest) (*agent_backend_svc.ListBackendsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, req)
	ret0, _ := ret[0].(*agent_backend_svc.ListBackendsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBackendServiceMockRecorder) List(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBackendService)(nil).List), ctx, req)
}

// Update mocks base method.
func (m *MockBackendService) Update(ctx context.Context, req *agent_backend_svc.UpdateBackendRequest) (*agent_backend_svc.UpdateBackendResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(*agent_backend_svc.UpdateBackendResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockBackendServiceMockRecorder) Update(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBackendService)(nil).Update), ctx, req)
}

// UpdateOpenClaw mocks base method.
func (m *MockBackendService) UpdateOpenClaw(ctx context.Context, req *agent_backend_svc.UpdateBackendRequest, token string, clearToken bool) (*agent_backend_svc.UpdateBackendResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOpenClaw", ctx, req, token, clearToken)
	ret0, _ := ret[0].(*agent_backend_svc.UpdateBackendResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOpenClaw indicates an expected call of UpdateOpenClaw.
func (mr *MockBackendServiceMockRecorder) UpdateOpenClaw(ctx, req, token, clearToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOpenClaw", reflect.TypeOf((*MockBackendService)(nil).UpdateOpenClaw), ctx, req, token, clearToken)
}

// MockDeviceDirectory is a mock of DeviceDirectory interface.
type MockDeviceDirectory struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceDirectoryMockRecorder
	isgomock struct{}
}

// MockDeviceDirectoryMockRecorder is the mock recorder for MockDeviceDirectory.
type MockDeviceDirectoryMockRecorder struct {
	mock *MockDeviceDirectory
}

// NewMockDeviceDirectory creates a new mock instance.
func NewMockDeviceDirectory(ctrl *gomock.Controller) *MockDeviceDirectory {
	mock := &MockDeviceDirectory{ctrl: ctrl}
	mock.recorder = &MockDeviceDirectoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceDirectory) EXPECT() *MockDeviceDirectoryMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockDeviceDirectory) List(ctx context.Context) ([]*remote_device_svc.DeviceView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*remote_device_svc.DeviceView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDeviceDirectoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDeviceDirectory)(nil).List), ctx)
}
