// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: agentre/wire/ctl.proto

package agentrewire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CtlKind 是 agrctl 能管理的资源类型。
type CtlKind int32

const (
	CtlKind_CTL_KIND_UNSPECIFIED CtlKind = 0
	CtlKind_CTL_KIND_AGENT       CtlKind = 1
	CtlKind_CTL_KIND_DEPARTMENT  CtlKind = 2
	CtlKind_CTL_KIND_PROJECT     CtlKind = 3
	CtlKind_CTL_KIND_PROVIDER    CtlKind = 4
	// 模型是提供方下的子资源（spec 决策 9）。
	CtlKind_CTL_KIND_MODEL   CtlKind = 5
	CtlKind_CTL_KIND_BACKEND CtlKind = 6
)

// Enum value maps for CtlKind.
var (
	CtlKind_name = map[int32]string{
		0: "CTL_KIND_UNSPECIFIED",
		1: "CTL_KIND_AGENT",
		2: "CTL_KIND_DEPARTMENT",
		3: "CTL_KIND_PROJECT",
		4: "CTL_KIND_PROVIDER",
		5: "CTL_KIND_MODEL",
		6: "CTL_KIND_BACKEND",
	}
	CtlKind_value = map[string]int32{
		"CTL_KIND_UNSPECIFIED": 0,
		"CTL_KIND_AGENT":       1,
		"CTL_KIND_DEPARTMENT":  2,
		"CTL_KIND_PROJECT":     3,
		"CTL_KIND_PROVIDER":    4,
		"CTL_KIND_MODEL":       5,
		"CTL_KIND_BACKEND":     6,
	}
)

func (x CtlKind) Enum() *CtlKind {
	p := new(CtlKind)
	*p = x
	return p
}

func (x CtlKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CtlKind) Descriptor() protoreflect.EnumDescriptor {
	return file_agentre_wire_ctl_proto_enumTypes[0].Descriptor()
}

func (CtlKind) Type() protoreflect.EnumType {
	return &file_agentre_wire_ctl_proto_enumTypes[0]
}

func (x CtlKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CtlKind.Descriptor instead.
func (CtlKind) EnumDescriptor() ([]byte, []int) {
	return file_agentre_wire_ctl_proto_rawDescGZIP(), []int{0}
}

// CtlOp 是写操作的种类。
type CtlOp int32

const (
	CtlOp_CTL_OP_UNSPECIFIED CtlOp = 0
	CtlOp_CTL_OP_CREATE      CtlOp = 1
	CtlOp_CTL_OP_UPDATE      CtlOp = 2
	CtlOp_CTL_OP_DELETE      CtlOp = 3
)

// Enum value maps for CtlOp.
var (
	CtlOp_name = map[int32]string{
		0: "CTL_OP_UNSPECIFIED",
		1: "CTL_OP_CREATE",
		2: "CTL_OP_UPDATE",
		3: "CTL_OP_DELETE",
	}
	CtlOp_value = map[string]int32{
		"CTL_OP_UNSPECIFIED": 0,
		"CTL_OP_CREATE":      1,
		"CTL_OP_UPDATE":      2,
		"CTL_OP_DELETE":      3,
	}
)

func (x CtlOp) Enum() *CtlOp {
	p := new(CtlOp)
	*p = x
	return p
}

func (x CtlOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CtlOp) Descriptor() protoreflect.EnumDescriptor {
	return file_agentre_wire_ctl_proto_enumTypes[1].Descriptor()
}

func (CtlOp) Type() protoreflect.EnumType {
	return &file_agentre_wire_ctl_proto_enumTypes[1]
}

func (x CtlOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CtlOp.Descriptor instead.
func (CtlOp) EnumDescriptor() ([]byte, []int) {
	return file_agentre_wire_ctl_proto_rawDescGZIP(), []int{1}
}

// CtlCaller 是 agrctl 对调用方的分类，执行者据此决定审批方式：
//   - SESSION：环境变量里带着会话级 token（Agentre 会话里的 agent）→ 在该会话里审批；
//   - EXTERNAL：用本机握手 token、stdin 不是 TTY（外部 AI/脚本）→ 桌面端弹窗审批；
//   - HUMAN：用本机握手 token、stdin 是 TTY（人在终端里）→ 直接执行。
//
// 这是护栏级的分类：同一系统用户下的程序可以伪造，执行者不得把它当作鉴权。
type CtlCaller int32

const (
	CtlCaller_CTL_CALLER_UNSPECIFIED CtlCaller = 0
	CtlCaller_CTL_CALLER_SESSION     CtlCaller = 1
	CtlCaller_CTL_CALLER_EXTERNAL    CtlCaller = 2
	CtlCaller_CTL_CALLER_HUMAN       CtlCaller = 3
)

// Enum value maps for CtlCaller.
var (
	CtlCaller_name = map[int32]string{
		0: "CTL_CALLER_UNSPECIFIED",
		1: "CTL_CALLER_SESSION",
		2: "CTL_CALLER_EXTERNAL",
		3: "CTL_CALLER_HUMAN",
	}
	CtlCaller_value = map[string]int32{
		"CTL_CALLER_UNSPECIFIED": 0,
		"CTL_CALLER_SESSION":     1,
		"CTL_CALLER_EXTERNAL":    2,
		"CTL_CALLER_HUMAN":       3,
	}
)

func (x CtlCaller) Enum() *CtlCaller {
	p := new(CtlCaller)
	*p = x
	return p
}

func (x CtlCaller) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CtlCaller) Descriptor() protoreflect.EnumDescriptor {
	return file_agentre_wire_ctl_proto_enumTypes[2].Descriptor()
}

func (CtlCaller) Type() protoreflect.EnumType {
	return &file_agentre_wire_ctl_proto_enumTypes[2]
}

func (x CtlCaller) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CtlCaller.Descriptor instead.
func (CtlCaller) EnumDescriptor() ([]byte, []int) {
	return file_agentre_wire_ctl_proto_rawDescGZIP(), []int{2}
}

// CtlAgent 是一个 Agent。
type CtlAgent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// 0 = 不属于任何部门。
	DepartmentId int64 `protobuf:"varint,4,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	// 执行目标（按顺序的后端 id）。写入时整体替换。
	BackendIds  []int64 `protobuf:"varint,5,rep,packed,name=backend_ids,json=backendIds,proto3" json:"backend_ids,omitempty"`
	Pinned      bool    `protobuf:"varint,6,opt,name=pinned,proto3" json:"pinned,omitempty"`
	AvatarColor string  `protobuf:"bytes,7,opt,name=avatar_color,json=avatarColor,proto3" json:"avatar_color,omitempty"`
	AvatarIcon  string  `protobuf:"bytes,8,opt,name=avatar_icon,json=avatarIcon,proto3" json:"avatar_icon,omitempty"`
	// 只读：非空表示系统 Agent。
	SystemBadge   string `protobuf:"bytes,9,opt,name=system_badge,json=systemBadge,proto3" json:"system_badge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtlAgent) Reset() {
	*x = CtlAgent{}
	mi := &file_agentre_wire_ctl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtlAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtlAgent) ProtoMessage() {}

func (x *CtlAgent) ProtoReflect() protoreflect.Message {
	mi := &file_agentre_wire_ctl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtlAgent.ProtoReflect.Descriptor instead.
func (*CtlAgent) Descriptor() ([]byte, []int) {
	return file_agentre_wire_ctl_proto_rawDescGZIP(), []int{0}
}

func (x *CtlAgent) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CtlAgent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CtlAgent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CtlAgent) GetDepartmentId() int64 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *CtlAgent) GetBackendIds() []int64 {
	if x != nil {
		return x.BackendIds
	}
	return nil
}

func (x *CtlAgent) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *CtlAgent) GetAvatarColor() string {
	if x != nil {
		return x.AvatarColor
	}
	return ""
}

func (x *CtlAgent) GetAvatarIcon() string {
	if x != nil {
		return x.AvatarIcon
	}
	return ""
}

func (x *CtlAgent) GetSystemBadge() string {
	if x != nil {
		return x.SystemBadge
	}
	return ""
}

// CtlDepartment 是一个部门；名字只在同一父部门下唯一。
type CtlDepartment struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Icon        string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	AccentColor string                 `protobuf:"bytes,5,opt,name=accent_color,json=accentColor,proto3" json:"accent_color,omitempty"`
	// 0 = 顶层部门。
	ParentId int64 `protobuf:"varint,6,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// 0 = 未指定负责人。
	LeadAgentId   int64 `protobuf:"varint,7,opt,name=lead_agent_id,json=leadAgentId,proto3" json:"lead_agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtlDepartment) Reset() {
	*x = CtlDepartment{}
	mi := &file_agentre_wire_ctl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtlDepartment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtlDepartment) ProtoMessage() {}

func (x *CtlDepartment) ProtoReflect() protoreflect.Message {
	mi := &file_agentre_wire_ctl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtlDepartment.ProtoReflect.Descriptor instead.
func (*CtlDepartment) Descriptor() ([]byte, []int) {
	return file_agentre_wire_ctl_proto_rawDescGZIP(), []int{1}
}

func (x *CtlDepartment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CtlDepartment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CtlDepartment) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CtlDepartment) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CtlDepartment) GetAccentColor() string {
	if x != nil {
		return x.AccentColor
	}
	return ""
}

func (x *CtlDepartment) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CtlDepartment) GetLeadAgentId() int64 {
	if x != nil {
		return x.LeadAgentId
	}
	return 0
}

// CtlProjectLocation 是项目在某台设备上的路径（只读）。
type CtlProjectLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceName    string                 `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtlProjectLocation) Reset() {
	*x = CtlProjectLocation{}
	mi := &file_agentre_wire_ctl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtlProjectLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtlProjectLocation) ProtoMessage() {}

func (x *CtlProjectLocation) ProtoReflect() protoreflect.Message {
	mi := &file_agentre_wire_ctl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtlProjectLocation.ProtoReflect.Descriptor instead.
func (*CtlProjectLocation) Descriptor() ([]byte, []int) {
	return file_agentre_wire_ctl_proto_rawDescGZIP(), []int{2}
}

func (x *CtlProjectLocation) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CtlProjectLocation) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *CtlProjectLocation) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// CtlProject 是一个项目；名字只在同一父项目下唯一。
type CtlProject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 0 = 顶层项目。
	ParentId    int64  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Icon        string `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Color       string `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	// 执行者本机上的路径。
	Path string `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	// 成员 Agent。创建时是初始成员；更新时用 CtlWriteRequest 的 add/remove 字段增减。
	MemberAgentIds []int64 `protobuf:"varint,8,rep,packed,name=member_agent_ids,json=memberAgentIds,proto3" json:"member_agent_ids,omitempty"`
	// 只读：各设备上的路径。
	Locations     []*CtlProjectLocation `protobuf:"bytes,9,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtlProject) Reset() {
	*x = CtlProject{}
	mi := &file_agentre_wire_ctl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtlProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtlProject) ProtoMessage() {}

func (x *CtlProject) ProtoReflect() protoreflect.Message {
	mi := &file_agentre_wire_ctl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtlProject.ProtoReflect.Descriptor instead.
func (*CtlProject) Descriptor() ([]byte, []int) {
	return file_agentre_wire_ctl_proto_rawDescGZIP(), []int{3}
}

func (x *CtlProject) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CtlProject) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CtlProject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CtlProject) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CtlProject) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *CtlProject) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CtlProject) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CtlProject) GetMemberAgentIds() []int64 {
	if x != nil {
		return x.MemberAgentIds
	}
	return nil
}

func (x *CtlProject) GetLocations() []*CtlProjectLocation {
	if x != nil {
		return x.Locations
	}
	return nil
}

// CtlProvider 是一个 LLM 提供方。
type CtlProvider struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type    string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	BaseUrl string                 `protobuf:"bytes,4,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Enabled bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// 写入时是明文；响应里只能是掩码（前 4 位、圆点、后 4 位），未设置时为空。
	ApiKey string `protobuf:"bytes,6,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// 只读：是否已设置 API key。
	ApiKeySet bool `protobuf:"varint,7,opt,name=api_key_set,json=apiKeySet,proto3" json:"api_key_set,omitempty"`
	// 默认模型的 key。
	DefaultModelKey string `protobuf:"bytes,8,opt,name=default_model_key,json=defaultModelKey,proto3" json:"default_model_key,omitempty"`
	// 只读：引用它的后端数。
	BackendRefs   int32 `protobuf:"varint,9,opt,name=backend_refs,json=backendRefs,proto3" json:"backend_refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtlProvider) Reset() {
	*x = CtlProvider{}
	mi := &file_agentre_wire_ctl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtlProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtlProvider) ProtoMessage() {}

func (x *CtlProvider) ProtoReflect() protoreflect.Message {
	mi := &file_agentre_wire_ctl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtlProvider.ProtoReflect.Descriptor instead.
func (*CtlProvider) Descriptor() ([]byte, []int) {
	return file_agentre_wire_ctl_proto_rawDescGZIP(), []int{4}
}

func (x *CtlProvider) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CtlProvider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CtlProvider) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CtlProvider) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *CtlProvider) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CtlProvider) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *CtlProvider) GetApiKeySet() bool {
	if x != nil {
		return x.ApiKeySet
	}
	return false
}

func (x *CtlProvider) GetDefaultModelKey() string {
	if x != nil {
		return x.DefaultModelKey
	}
	return ""
}

func (x *CtlProvider) GetBackendRefs() int32 {
	if x != nil {
		return x.BackendRefs
	}
	return 0
}

// CtlModel 是提供方下的一个模型，用 `提供方/模型key` 定位。
type CtlModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProviderId    int64                  `protobuf:"varint,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	ModelId       string                 `protobuf:"bytes,4,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	ContextWindow int64                  `protobuf:"varint,6,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
	MaxOutput     int64                  `protobuf:"varint,7,opt,name=max_output,json=maxOutput,proto3" json:"max_output,omitempty"`
	Enabled       bool                   `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// 读：是否为所属提供方的默认模型。写：true 表示把它设为默认模型。
	IsDefault bool `protobuf:"varint,9,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	// 只读：引用它的后端数。
	BackendRefs   int32 `protobuf:"varint,10,opt,name=backend_refs,json=backendRefs,proto3" json:"backend_refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtlModel) Reset() {
	*x = CtlModel{}
	mi := &file_agentre_wire_ctl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtlModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtlModel) ProtoMessage() {}

func (x *CtlModel) ProtoReflect() protoreflect.Message {
	mi := &file_agentre_wire_ctl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtlModel.ProtoReflect.Descriptor instead.
func (*CtlModel) Descriptor() ([]byte, []int) {
	return file_agentre_wire_ctl_proto_rawDescGZIP(), []int{5}
}

func (x *CtlModel) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CtlModel) GetProviderId() int64 {
	if x != nil {
		return x.ProviderId
	}
	return 0
}

func (x *CtlModel) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CtlModel) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *CtlModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CtlModel) GetContextWindow() int64 {
	if x != nil {
		return x.ContextWindow
	}
	return 0
}

func (x *CtlModel) GetMaxOutput() int64 {
	if x != nil {
		return x.MaxOutput
	}
	return 0
}

func (x *CtlModel) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CtlModel) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *CtlModel) GetBackendRefs() int32 {
	if x != nil {
		return x.BackendRefs
	}
	return 0
}

// CtlBackend 是一个 Agent 后端。
type CtlBackend struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 创建后不可改。
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// 绑定的提供方；0 = CLI 自身登录态（native）。
	ProviderId int64 `protobuf:"varint,4,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	// 固定模型；0 = 跟随提供方的默认模型。
	ModelId int64 `protobuf:"varint,5,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// 目标设备：已配对设备的名字或设备指纹，空 = 本机。设备不属于 ctl 管理的资源，
	// 由执行者解析。
	Device          string            `protobuf:"bytes,6,opt,name=device,proto3" json:"device,omitempty"`
	CliPath         string            `protobuf:"bytes,7,opt,name=cli_path,json=cliPath,proto3" json:"cli_path,omitempty"`
	ReasoningEffort string            `protobuf:"bytes,8,opt,name=reasoning_effort,json=reasoningEffort,proto3" json:"reasoning_effort,omitempty"`
	Env             map[string]string `protobuf:"bytes,9,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 该后端类型独占的设置，形如同步契约的 AgentBackendConfig（camelCase 键的 JSON 对象）。
	// 写入时 update 只替换其中出现的键。
	ConfigJson string `protobuf:"bytes,10,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	// 只写：openclaw 网关 token 的明文；响应里恒为空。
	Token string `protobuf:"bytes,11,opt,name=token,proto3" json:"token,omitempty"`
	// 只读：token 是否已设置。
	TokenSet      bool `protobuf:"varint,12,opt,name=token_set,json=tokenSet,proto3" json:"token_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtlBackend) Reset() {
	*x = CtlBackend{}
	mi := &file_agentre_wire_ctl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtlBackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtlBackend) ProtoMessage() {}

func (x *CtlBackend) ProtoReflect() protoreflect.Message {
	mi := &file_agentre_wire_ctl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtlBackend.ProtoReflect.Descriptor instead.
func (*CtlBackend) Descriptor() ([]byte, []int) {
	return file_agentre_wire_ctl_proto_rawDescGZIP(), []int{6}
}

func (x *CtlBackend) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CtlBackend) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CtlBackend) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CtlBackend) GetProviderId() int64 {
	if x != nil {
		return x.ProviderId
	}
	return 0
}

func (x *CtlBackend) GetModelId() int64 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

func (x *CtlBackend) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *CtlBackend) GetCliPath() string {
	if x != nil {
		return x.CliPath
	}
	return ""
}

func (x *CtlBackend) GetReasoningEffort() string {
	if x != nil {
		return x.ReasoningEffort
	}
	return ""
}

func (x *CtlBackend) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *CtlBackend) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *CtlBackend) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CtlBackend) GetTokenSet() bool {
	if x != nil {
		return x.TokenSet
	}
	return false
}

// CtlResource 是任意一类资源的文档。
type CtlResource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Doc:
	//
	//	*CtlResource_Agent
	//	*CtlResource_Department
	//	*CtlResource_Project
	//	*CtlResource_Provider
	//	*CtlResource_Model
	//	*CtlResource_Backend
	Doc           isCtlResource_Doc `protobuf_oneof:"doc"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtlResource) Reset() {
	*x = CtlResource{}
	mi := &file_agentre_wire_ctl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtlResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtlResource) ProtoMessage() {}

func (x *CtlResource) ProtoReflect() protoreflect.Message {
	mi := &file_agentre_wire_ctl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtlResource.ProtoReflect.Descriptor instead.
func (*CtlResource) Descriptor() ([]byte, []int) {
	return file_agentre_wire_ctl_proto_rawDescGZIP(), []int{7}
}

func (x *CtlResource) GetDoc() isCtlResource_Doc {
	if x != nil {
		return x.Doc
	}
	return nil
}

func (x *CtlResource) GetAgent() *CtlAgent {
	if x != nil {
		if x, ok := x.Doc.(*CtlResource_Agent); ok {
			return x.Agent
		}
	}
	return nil
}

func (x *CtlResource) GetDepartment() *CtlDepartment {
	if x != nil {
		if x, ok := x.Doc.(*CtlResource_Department); ok {
			return x.Department
		}
	}
	return nil
}

func (x *CtlResource) GetProject() *CtlProject {
	if x != nil {
		if x, ok := x.Doc.(*CtlResource_Project); ok {
			return x.Project
		}
	}
	return nil
}

func (x *CtlResource) GetProvider() *CtlProvider {
	if x != nil {
		if x, ok := x.Doc.(*CtlResource_Provider); ok {
			return x.Provider
		}
	}
	return nil
}

func (x *CtlResource) GetModel() *CtlModel {
	if x != nil {
		if x, ok := x.Doc.(*CtlResource_Model); ok {
			return x.Model
		}
	}
	return nil
}

func (x *CtlResource) GetBackend() *CtlBackend {
	if x != nil {
		if x, ok := x.Doc.(*CtlResource_Backend); ok {
			return x.Backend
		}
	}
	return nil
}

type isCtlResource_Doc interface {
	isCtlResource_Doc()
}

type CtlResource_Agent struct {
	Agent *CtlAgent `protobuf:"bytes,1,opt,name=agent,proto3,oneof"`
}

type CtlResource_Department struct {
	Department *CtlDepartment `protobuf:"bytes,2,opt,name=department,proto3,oneof"`
}

type CtlResource_Project struct {
	Project *CtlProject `protobuf:"bytes,3,opt,name=project,proto3,oneof"`
}

type CtlResource_Provider struct {
	Provider *CtlProvider `protobuf:"bytes,4,opt,name=provider,proto3,oneof"`
}

type CtlResource_Model struct {
	Model *CtlModel `protobuf:"bytes,5,opt,name=model,proto3,oneof"`
}

type CtlResource_Backend struct {
	Backend *CtlBackend `protobuf:"bytes,6,opt,name=backend,proto3,oneof"`
}

func (*CtlResource_Agent) isCtlResource_Doc() {}

func (*CtlResource_Department) isCtlResource_Doc() {}

func (*CtlResource_Project) isCtlResource_Doc() {}

func (*CtlResource_Provider) isCtlResource_Doc() {}

func (*CtlResource_Model) isCtlResource_Doc() {}

func (*CtlResource_Backend) isCtlResource_Doc() {}

// CtlListRequest 列出某类资源的全部条目；过滤在客户端做。
type CtlListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          CtlKind                `protobuf:"varint,1,opt,name=kind,proto3,enum=agentre.wire.CtlKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtlListRequest) Reset() {
	*x = CtlListRequest{}
	mi := &file_agentre_wire_ctl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtlListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtlListRequest) ProtoMessage() {}

func (x *CtlListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentre_wire_ctl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtlListRequest.ProtoReflect.Descriptor instead.
func (*CtlListRequest) Descriptor() ([]byte, []int) {
	return file_agentre_wire_ctl_proto_rawDescGZIP(), []int{8}
}

func (x *CtlListRequest) GetKind() CtlKind {
	if x != nil {
		return x.Kind
	}
	return CtlKind_CTL_KIND_UNSPECIFIED
}

type CtlListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CtlResource         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtlListResponse) Reset() {
	*x = CtlListResponse{}
	mi := &file_agentre_wire_ctl_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtlListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtlListResponse) ProtoMessage() {}

func (x *CtlListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentre_wire_ctl_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtlListResponse.ProtoReflect.Descriptor instead.
func (*CtlListResponse) Descriptor() ([]byte, []int) {
	return file_agentre_wire_ctl_proto_rawDescGZIP(), []int{9}
}

func (x *CtlListResponse) GetItems() []*CtlResource {
	if x != nil {
		return x.Items
	}
	return nil
}

// CtlGetRequest 按 id 取一条资源的详情（含只读的关联信息）。
type CtlGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          CtlKind                `protobuf:"varint,1,opt,name=kind,proto3,enum=agentre.wire.CtlKind" json:"kind,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtlGetRequest) Reset() {
	*x = CtlGetRequest{}
	mi := &file_agentre_wire_ctl_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtlGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtlGetRequest) ProtoMessage() {}

func (x *CtlGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentre_wire_ctl_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtlGetRequest.ProtoReflect.Descriptor instead.
func (*CtlGetRequest) Descriptor() ([]byte, []int) {
	return file_agentre_wire_ctl_proto_rawDescGZIP(), []int{10}
}

func (x *CtlGetRequest) GetKind() CtlKind {
	if x != nil {
		return x.Kind
	}
	return CtlKind_CTL_KIND_UNSPECIFIED
}

func (x *CtlGetRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CtlGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *CtlResource           `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtlGetResponse) Reset() {
	*x = CtlGetResponse{}
	mi := &file_agentre_wire_ctl_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtlGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtlGetResponse) ProtoMessage() {}

func (x *CtlGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentre_wire_ctl_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtlGetResponse.ProtoReflect.Descriptor instead.
func (*CtlGetResponse) Descriptor() ([]byte, []int) {
	return file_agentre_wire_ctl_proto_rawDescGZIP(), []int{11}
}

func (x *CtlGetResponse) GetResource() *CtlResource {
	if x != nil {
		return x.Resource
	}
	return nil
}

// CtlWriteRequest 是一次按 id 的写操作。
type CtlWriteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Op    CtlOp                  `protobuf:"varint,1,opt,name=op,proto3,enum=agentre.wire.CtlOp" json:"op,omitempty"`
	Kind  CtlKind                `protobuf:"varint,2,opt,name=kind,proto3,enum=agentre.wire.CtlKind" json:"kind,omitempty"`
	// update / delete 的目标 id；create 时为 0。
	Id int64 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	// create / update 的字段值。只有 fields 里列出的字段有效，其余一律忽略。
	Resource *CtlResource `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	// 本次写入的字段集合：该资源文档里字段的 JSON 名（如 "departmentId"、"backendIds"）。
	// update 只修改这些字段。
	Fields []string `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	// 仅 project update：增减成员 Agent。
	AddMemberAgentIds    []int64 `protobuf:"varint,6,rep,packed,name=add_member_agent_ids,json=addMemberAgentIds,proto3" json:"add_member_agent_ids,omitempty"`
	RemoveMemberAgentIds []int64 `protobuf:"varint,7,rep,packed,name=remove_member_agent_ids,json=removeMemberAgentIds,proto3" json:"remove_member_agent_ids,omitempty"`
	// 仅 department delete：连同子部门和 Agent 一起删除；否则把它们上移到父部门。
	Cascade bool `protobuf:"varint,8,opt,name=cascade,proto3" json:"cascade,omitempty"`
	// 仅 provider / model delete：仍被后端引用时也删除。
	Force  bool      `protobuf:"varint,9,opt,name=force,proto3" json:"force,omitempty"`
	Caller CtlCaller `protobuf:"varint,10,opt,name=caller,proto3,enum=agentre.wire.CtlCaller" json:"caller,omitempty"`
	// 完整命令行（密钥值已替换为 …），供审批卡展示。
	Command       string `protobuf:"bytes,11,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtlWriteRequest) Reset() {
	*x = CtlWriteRequest{}
	mi := &file_agentre_wire_ctl_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtlWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtlWriteRequest) ProtoMessage() {}

func (x *CtlWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentre_wire_ctl_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtlWriteRequest.ProtoReflect.Descriptor instead.
func (*CtlWriteRequest) Descriptor() ([]byte, []int) {
	return file_agentre_wire_ctl_proto_rawDescGZIP(), []int{12}
}

func (x *CtlWriteRequest) GetOp() CtlOp {
	if x != nil {
		return x.Op
	}
	return CtlOp_CTL_OP_UNSPECIFIED
}

func (x *CtlWriteRequest) GetKind() CtlKind {
	if x != nil {
		return x.Kind
	}
	return CtlKind_CTL_KIND_UNSPECIFIED
}

func (x *CtlWriteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CtlWriteRequest) GetResource() *CtlResource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *CtlWriteRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *CtlWriteRequest) GetAddMemberAgentIds() []int64 {
	if x != nil {
		return x.AddMemberAgentIds
	}
	return nil
}

func (x *CtlWriteRequest) GetRemoveMemberAgentIds() []int64 {
	if x != nil {
		return x.RemoveMemberAgentIds
	}
	return nil
}

func (x *CtlWriteRequest) GetCascade() bool {
	if x != nil {
		return x.Cascade
	}
	return false
}

func (x *CtlWriteRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *CtlWriteRequest) GetCaller() CtlCaller {
	if x != nil {
		return x.Caller
	}
	return CtlCaller_CTL_CALLER_UNSPECIFIED
}

func (x *CtlWriteRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

// CtlFieldChange 是一个字段的变更；before/after 缺席表示「没有」（创建时无 before，
// 删除时无 after）。secret 为 true 时两者都缺席，只表示该密钥被写入。
type CtlFieldChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Before        *string                `protobuf:"bytes,2,opt,name=before,proto3,oneof" json:"before,omitempty"`
	After         *string                `protobuf:"bytes,3,opt,name=after,proto3,oneof" json:"after,omitempty"`
	Secret        bool                   `protobuf:"varint,4,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtlFieldChange) Reset() {
	*x = CtlFieldChange{}
	mi := &file_agentre_wire_ctl_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtlFieldChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtlFieldChange) ProtoMessage() {}

func (x *CtlFieldChange) ProtoReflect() protoreflect.Message {
	mi := &file_agentre_wire_ctl_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtlFieldChange.ProtoReflect.Descriptor instead.
func (*CtlFieldChange) Descriptor() ([]byte, []int) {
	return file_agentre_wire_ctl_proto_rawDescGZIP(), []int{13}
}

func (x *CtlFieldChange) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *CtlFieldChange) GetBefore() string {
	if x != nil && x.Before != nil {
		return *x.Before
	}
	return ""
}

func (x *CtlFieldChange) GetAfter() string {
	if x != nil && x.After != nil {
		return *x.After
	}
	return ""
}

func (x *CtlFieldChange) GetSecret() bool {
	if x != nil {
		return x.Secret
	}
	return false
}

// CtlChange 是一条资源的变更，由执行者对照当前数据计算。
type CtlChange struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Op     CtlOp                  `protobuf:"varint,1,opt,name=op,proto3,enum=agentre.wire.CtlOp" json:"op,omitempty"`
	Kind   CtlKind                `protobuf:"varint,2,opt,name=kind,proto3,enum=agentre.wire.CtlKind" json:"kind,omitempty"`
	Id     int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Name   string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Fields []*CtlFieldChange      `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	// 附注，例如级联删除波及的子资源。
	Note          string `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtlChange) Reset() {
	*x = CtlChange{}
	mi := &file_agentre_wire_ctl_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtlChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtlChange) ProtoMessage() {}

func (x *CtlChange) ProtoReflect() protoreflect.Message {
	mi := &file_agentre_wire_ctl_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtlChange.ProtoReflect.Descriptor instead.
func (*CtlChange) Descriptor() ([]byte, []int) {
	return file_agentre_wire_ctl_proto_rawDescGZIP(), []int{14}
}

func (x *CtlChange) GetOp() CtlOp {
	if x != nil {
		return x.Op
	}
	return CtlOp_CTL_OP_UNSPECIFIED
}

func (x *CtlChange) GetKind() CtlKind {
	if x != nil {
		return x.Kind
	}
	return CtlKind_CTL_KIND_UNSPECIFIED
}

func (x *CtlChange) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CtlChange) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CtlChange) GetFields() []*CtlFieldChange {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *CtlChange) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type CtlWriteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 被写入资源的 id 与名字（create 时是新 id）。
	Id            int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Changes       []*CtlChange `protobuf:"bytes,3,rep,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtlWriteResponse) Reset() {
	*x = CtlWriteResponse{}
	mi := &file_agentre_wire_ctl_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtlWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtlWriteResponse) ProtoMessage() {}

func (x *CtlWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentre_wire_ctl_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtlWriteResponse.ProtoReflect.Descriptor instead.
func (*CtlWriteResponse) Descriptor() ([]byte, []int) {
	return file_agentre_wire_ctl_proto_rawDescGZIP(), []int{15}
}

func (x *CtlWriteResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CtlWriteResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CtlWriteResponse) GetChanges() []*CtlChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

// CtlRequest 是 `POST /ctl/v1/resources` 的请求体。
type CtlRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*CtlRequest_List
	//	*CtlRequest_Get
	//	*CtlRequest_Write
	Op            isCtlRequest_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtlRequest) Reset() {
	*x = CtlRequest{}
	mi := &file_agentre_wire_ctl_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtlRequest) ProtoMessage() {}

func (x *CtlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentre_wire_ctl_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtlRequest.ProtoReflect.Descriptor instead.
func (*CtlRequest) Descriptor() ([]byte, []int) {
	return file_agentre_wire_ctl_proto_rawDescGZIP(), []int{16}
}

func (x *CtlRequest) GetOp() isCtlRequest_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *CtlRequest) GetList() *CtlListRequest {
	if x != nil {
		if x, ok := x.Op.(*CtlRequest_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *CtlRequest) GetGet() *CtlGetRequest {
	if x != nil {
		if x, ok := x.Op.(*CtlRequest_Get); ok {
			return x.Get
		}
	}
	return nil
}

func (x *CtlRequest) GetWrite() *CtlWriteRequest {
	if x != nil {
		if x, ok := x.Op.(*CtlRequest_Write); ok {
			return x.Write
		}
	}
	return nil
}

type isCtlRequest_Op interface {
	isCtlRequest_Op()
}

type CtlRequest_List struct {
	List *CtlListRequest `protobuf:"bytes,1,opt,name=list,proto3,oneof"`
}

type CtlRequest_Get struct {
	Get *CtlGetRequest `protobuf:"bytes,2,opt,name=get,proto3,oneof"`
}

type CtlRequest_Write struct {
	Write *CtlWriteRequest `protobuf:"bytes,3,opt,name=write,proto3,oneof"`
}

func (*CtlRequest_List) isCtlRequest_Op() {}

func (*CtlRequest_Get) isCtlRequest_Op() {}

func (*CtlRequest_Write) isCtlRequest_Op() {}

// CtlResponse 是 `POST /ctl/v1/resources` 的成功响应体，分支与请求一一对应。
type CtlResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*CtlResponse_List
	//	*CtlResponse_Get
	//	*CtlResponse_Write
	Result        isCtlResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtlResponse) Reset() {
	*x = CtlResponse{}
	mi := &file_agentre_wire_ctl_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtlResponse) ProtoMessage() {}

func (x *CtlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentre_wire_ctl_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtlResponse.ProtoReflect.Descriptor instead.
func (*CtlResponse) Descriptor() ([]byte, []int) {
	return file_agentre_wire_ctl_proto_rawDescGZIP(), []int{17}
}

func (x *CtlResponse) GetResult() isCtlResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CtlResponse) GetList() *CtlListResponse {
	if x != nil {
		if x, ok := x.Result.(*CtlResponse_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *CtlResponse) GetGet() *CtlGetResponse {
	if x != nil {
		if x, ok := x.Result.(*CtlResponse_Get); ok {
			return x.Get
		}
	}
	return nil
}

func (x *CtlResponse) GetWrite() *CtlWriteResponse {
	if x != nil {
		if x, ok := x.Result.(*CtlResponse_Write); ok {
			return x.Write
		}
	}
	return nil
}

type isCtlResponse_Result interface {
	isCtlResponse_Result()
}

type CtlResponse_List struct {
	List *CtlListResponse `protobuf:"bytes,1,opt,name=list,proto3,oneof"`
}

type CtlResponse_Get struct {
	Get *CtlGetResponse `protobuf:"bytes,2,opt,name=get,proto3,oneof"`
}

type CtlResponse_Write struct {
	Write *CtlWriteResponse `protobuf:"bytes,3,opt,name=write,proto3,oneof"`
}

func (*CtlResponse_List) isCtlResponse_Result() {}

func (*CtlResponse_Get) isCtlResponse_Result() {}

func (*CtlResponse_Write) isCtlResponse_Result() {}

var File_agentre_wire_ctl_proto protoreflect.FileDescriptor

const file_agentre_wire_ctl_proto_rawDesc = "" +
	"\n" +
	"\x16agentre/wire/ctl.proto\x12\fagentre.wire\"\x95\x02\n" +
	"\bCtlAgent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rdepartment_id\x18\x04 \x01(\x03R\fdepartmentId\x12\x1f\n" +
	"\vbackend_ids\x18\x05 \x03(\x03R\n" +
	"backendIds\x12\x16\n" +
	"\x06pinned\x18\x06 \x01(\bR\x06pinned\x12!\n" +
	"\favatar_color\x18\a \x01(\tR\vavatarColor\x12\x1f\n" +
	"\vavatar_icon\x18\b \x01(\tR\n" +
	"avatarIcon\x12!\n" +
	"\fsystem_badge\x18\t \x01(\tR\vsystemBadge\"\xcd\x01\n" +
	"\rCtlDepartment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12!\n" +
	"\faccent_color\x18\x05 \x01(\tR\vaccentColor\x12\x1b\n" +
	"\tparent_id\x18\x06 \x01(\x03R\bparentId\x12\"\n" +
	"\rlead_agent_id\x18\a \x01(\x03R\vleadAgentId\"f\n" +
	"\x12CtlProjectLocation\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vdevice_name\x18\x02 \x01(\tR\n" +
	"deviceName\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"\x97\x02\n" +
	"\n" +
	"CtlProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x03R\bparentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\x12(\n" +
	"\x10member_agent_ids\x18\b \x03(\x03R\x0ememberAgentIds\x12>\n" +
	"\tlocations\x18\t \x03(\v2 .agentre.wire.CtlProjectLocationR\tlocations\"\x82\x02\n" +
	"\vCtlProvider\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x19\n" +
	"\bbase_url\x18\x04 \x01(\tR\abaseUrl\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12\x17\n" +
	"\aapi_key\x18\x06 \x01(\tR\x06apiKey\x12\x1e\n" +
	"\vapi_key_set\x18\a \x01(\bR\tapiKeySet\x12*\n" +
	"\x11default_model_key\x18\b \x01(\tR\x0fdefaultModelKey\x12!\n" +
	"\fbackend_refs\x18\t \x01(\x05R\vbackendRefs\"\x9e\x02\n" +
	"\bCtlModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\x03R\n" +
	"providerId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x19\n" +
	"\bmodel_id\x18\x04 \x01(\tR\amodelId\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12%\n" +
	"\x0econtext_window\x18\x06 \x01(\x03R\rcontextWindow\x12\x1d\n" +
	"\n" +
	"max_output\x18\a \x01(\x03R\tmaxOutput\x12\x18\n" +
	"\aenabled\x18\b \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"is_default\x18\t \x01(\bR\tisDefault\x12!\n" +
	"\fbackend_refs\x18\n" +
	" \x01(\x05R\vbackendRefs\"\x9f\x03\n" +
	"\n" +
	"CtlBackend\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1f\n" +
	"\vprovider_id\x18\x04 \x01(\x03R\n" +
	"providerId\x12\x19\n" +
	"\bmodel_id\x18\x05 \x01(\x03R\amodelId\x12\x16\n" +
	"\x06device\x18\x06 \x01(\tR\x06device\x12\x19\n" +
	"\bcli_path\x18\a \x01(\tR\acliPath\x12)\n" +
	"\x10reasoning_effort\x18\b \x01(\tR\x0freasoningEffort\x123\n" +
	"\x03env\x18\t \x03(\v2!.agentre.wire.CtlBackend.EnvEntryR\x03env\x12\x1f\n" +
	"\vconfig_json\x18\n" +
	" \x01(\tR\n" +
	"configJson\x12\x14\n" +
	"\x05token\x18\v \x01(\tR\x05token\x12\x1b\n" +
	"\ttoken_set\x18\f \x01(\bR\btokenSet\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd8\x02\n" +
	"\vCtlResource\x12.\n" +
	"\x05agent\x18\x01 \x01(\v2\x16.agentre.wire.CtlAgentH\x00R\x05agent\x12=\n" +
	"\n" +
	"department\x18\x02 \x01(\v2\x1b.agentre.wire.CtlDepartmentH\x00R\n" +
	"department\x124\n" +
	"\aproject\x18\x03 \x01(\v2\x18.agentre.wire.CtlProjectH\x00R\aproject\x127\n" +
	"\bprovider\x18\x04 \x01(\v2\x19.agentre.wire.CtlProviderH\x00R\bprovider\x12.\n" +
	"\x05model\x18\x05 \x01(\v2\x16.agentre.wire.CtlModelH\x00R\x05model\x124\n" +
	"\abackend\x18\x06 \x01(\v2\x18.agentre.wire.CtlBackendH\x00R\abackendB\x05\n" +
	"\x03doc\";\n" +
	"\x0eCtlListRequest\x12)\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x15.agentre.wire.CtlKindR\x04kind\"B\n" +
	"\x0fCtlListResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.agentre.wire.CtlResourceR\x05items\"J\n" +
	"\rCtlGetRequest\x12)\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x15.agentre.wire.CtlKindR\x04kind\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"G\n" +
	"\x0eCtlGetResponse\x125\n" +
	"\bresource\x18\x01 \x01(\v2\x19.agentre.wire.CtlResourceR\bresource\"\xa3\x03\n" +
	"\x0fCtlWriteRequest\x12#\n" +
	"\x02op\x18\x01 \x01(\x0e2\x13.agentre.wire.CtlOpR\x02op\x12)\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x15.agentre.wire.CtlKindR\x04kind\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x125\n" +
	"\bresource\x18\x04 \x01(\v2\x19.agentre.wire.CtlResourceR\bresource\x12\x16\n" +
	"\x06fields\x18\x05 \x03(\tR\x06fields\x12/\n" +
	"\x14add_member_agent_ids\x18\x06 \x03(\x03R\x11addMemberAgentIds\x125\n" +
	"\x17remove_member_agent_ids\x18\a \x03(\x03R\x14removeMemberAgentIds\x12\x18\n" +
	"\acascade\x18\b \x01(\bR\acascade\x12\x14\n" +
	"\x05force\x18\t \x01(\bR\x05force\x12/\n" +
	"\x06caller\x18\n" +
	" \x01(\x0e2\x17.agentre.wire.CtlCallerR\x06caller\x12\x18\n" +
	"\acommand\x18\v \x01(\tR\acommand\"\x8b\x01\n" +
	"\x0eCtlFieldChange\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1b\n" +
	"\x06before\x18\x02 \x01(\tH\x00R\x06before\x88\x01\x01\x12\x19\n" +
	"\x05after\x18\x03 \x01(\tH\x01R\x05after\x88\x01\x01\x12\x16\n" +
	"\x06secret\x18\x04 \x01(\bR\x06secretB\t\n" +
	"\a_beforeB\b\n" +
	"\x06_after\"\xc9\x01\n" +
	"\tCtlChange\x12#\n" +
	"\x02op\x18\x01 \x01(\x0e2\x13.agentre.wire.CtlOpR\x02op\x12)\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x15.agentre.wire.CtlKindR\x04kind\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x124\n" +
	"\x06fields\x18\x05 \x03(\v2\x1c.agentre.wire.CtlFieldChangeR\x06fields\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\"i\n" +
	"\x10CtlWriteResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x121\n" +
	"\achanges\x18\x03 \x03(\v2\x17.agentre.wire.CtlChangeR\achanges\"\xae\x01\n" +
	"\n" +
	"CtlRequest\x122\n" +
	"\x04list\x18\x01 \x01(\v2\x1c.agentre.wire.CtlListRequestH\x00R\x04list\x12/\n" +
	"\x03get\x18\x02 \x01(\v2\x1b.agentre.wire.CtlGetRequestH\x00R\x03get\x125\n" +
	"\x05write\x18\x03 \x01(\v2\x1d.agentre.wire.CtlWriteRequestH\x00R\x05writeB\x04\n" +
	"\x02op\"\xb6\x01\n" +
	"\vCtlResponse\x123\n" +
	"\x04list\x18\x01 \x01(\v2\x1d.agentre.wire.CtlListResponseH\x00R\x04list\x120\n" +
	"\x03get\x18\x02 \x01(\v2\x1c.agentre.wire.CtlGetResponseH\x00R\x03get\x126\n" +
	"\x05write\x18\x03 \x01(\v2\x1e.agentre.wire.CtlWriteResponseH\x00R\x05writeB\b\n" +
	"\x06result*\xa7\x01\n" +
	"\aCtlKind\x12\x18\n" +
	"\x14CTL_KIND_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eCTL_KIND_AGENT\x10\x01\x12\x17\n" +
	"\x13CTL_KIND_DEPARTMENT\x10\x02\x12\x14\n" +
	"\x10CTL_KIND_PROJECT\x10\x03\x12\x15\n" +
	"\x11CTL_KIND_PROVIDER\x10\x04\x12\x12\n" +
	"\x0eCTL_KIND_MODEL\x10\x05\x12\x14\n" +
	"\x10CTL_KIND_BACKEND\x10\x06*X\n" +
	"\x05CtlOp\x12\x16\n" +
	"\x12CTL_OP_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rCTL_OP_CREATE\x10\x01\x12\x11\n" +
	"\rCTL_OP_UPDATE\x10\x02\x12\x11\n" +
	"\rCTL_OP_DELETE\x10\x03*n\n" +
	"\tCtlCaller\x12\x1a\n" +
	"\x16CTL_CALLER_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CTL_CALLER_SESSION\x10\x01\x12\x17\n" +
	"\x13CTL_CALLER_EXTERNAL\x10\x02\x12\x14\n" +
	"\x10CTL_CALLER_HUMAN\x10\x03BAZ?github.com/agentre-hub/agentre/pkg/wire/agentrewire;agentrewireb\x06proto3"

var (
	file_agentre_wire_ctl_proto_rawDescOnce sync.Once
	file_agentre_wire_ctl_proto_rawDescData []byte
)

func file_agentre_wire_ctl_proto_rawDescGZIP() []byte {
	file_agentre_wire_ctl_proto_rawDescOnce.Do(func() {
		file_agentre_wire_ctl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agentre_wire_ctl_proto_rawDesc), len(file_agentre_wire_ctl_proto_rawDesc)))
	})
	return file_agentre_wire_ctl_proto_rawDescData
}

var file_agentre_wire_ctl_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_agentre_wire_ctl_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_agentre_wire_ctl_proto_goTypes = []any{
	(CtlKind)(0),               // 0: agentre.wire.CtlKind
	(CtlOp)(0),                 // 1: agentre.wire.CtlOp
	(CtlCaller)(0),             // 2: agentre.wire.CtlCaller
	(*CtlAgent)(nil),           // 3: agentre.wire.CtlAgent
	(*CtlDepartment)(nil),      // 4: agentre.wire.CtlDepartment
	(*CtlProjectLocation)(nil), // 5: agentre.wire.CtlProjectLocation
	(*CtlProject)(nil),         // 6: agentre.wire.CtlProject
	(*CtlProvider)(nil),        // 7: agentre.wire.CtlProvider
	(*CtlModel)(nil),           // 8: agentre.wire.CtlModel
	(*CtlBackend)(nil),         // 9: agentre.wire.CtlBackend
	(*CtlResource)(nil),        // 10: agentre.wire.CtlResource
	(*CtlListRequest)(nil),     // 11: agentre.wire.CtlListRequest
	(*CtlListResponse)(nil),    // 12: agentre.wire.CtlListResponse
	(*CtlGetRequest)(nil),      // 13: agentre.wire.CtlGetRequest
	(*CtlGetResponse)(nil),     // 14: agentre.wire.CtlGetResponse
	(*CtlWriteRequest)(nil),    // 15: agentre.wire.CtlWriteRequest
	(*CtlFieldChange)(nil),     // 16: agentre.wire.CtlFieldChange
	(*CtlChange)(nil),          // 17: agentre.wire.CtlChange
	(*CtlWriteResponse)(nil),   // 18: agentre.wire.CtlWriteResponse
	(*CtlRequest)(nil),         // 19: agentre.wire.CtlRequest
	(*CtlResponse)(nil),        // 20: agentre.wire.CtlResponse
	nil,                        // 21: agentre.wire.CtlBackend.EnvEntry
}
var file_agentre_wire_ctl_proto_depIdxs = []int32{
	5,  // 0: agentre.wire.CtlProject.locations:type_name -> agentre.wire.CtlProjectLocation
	21, // 1: agentre.wire.CtlBackend.env:type_name -> agentre.wire.CtlBackend.EnvEntry
	3,  // 2: agentre.wire.CtlResource.agent:type_name -> agentre.wire.CtlAgent
	4,  // 3: agentre.wire.CtlResource.department:type_name -> agentre.wire.CtlDepartment
	6,  // 4: agentre.wire.CtlResource.project:type_name -> agentre.wire.CtlProject
	7,  // 5: agentre.wire.CtlResource.provider:type_name -> agentre.wire.CtlProvider
	8,  // 6: agentre.wire.CtlResource.model:type_name -> agentre.wire.CtlModel
	9,  // 7: agentre.wire.CtlResource.backend:type_name -> agentre.wire.CtlBackend
	0,  // 8: agentre.wire.CtlListRequest.kind:type_name -> agentre.wire.CtlKind
	10, // 9: agentre.wire.CtlListResponse.items:type_name -> agentre.wire.CtlResource
	0,  // 10: agentre.wire.CtlGetRequest.kind:type_name -> agentre.wire.CtlKind
	10, // 11: agentre.wire.CtlGetResponse.resource:type_name -> agentre.wire.CtlResource
	1,  // 12: agentre.wire.CtlWriteRequest.op:type_name -> agentre.wire.CtlOp
	0,  // 13: agentre.wire.CtlWriteRequest.kind:type_name -> agentre.wire.CtlKind
	10, // 14: agentre.wire.CtlWriteRequest.resource:type_name -> agentre.wire.CtlResource
	2,  // 15: agentre.wire.CtlWriteRequest.caller:type_name -> agentre.wire.CtlCaller
	1,  // 16: agentre.wire.CtlChange.op:type_name -> agentre.wire.CtlOp
	0,  // 17: agentre.wire.CtlChange.kind:type_name -> agentre.wire.CtlKind
	16, // 18: agentre.wire.CtlChange.fields:type_name -> agentre.wire.CtlFieldChange
	17, // 19: agentre.wire.CtlWriteResponse.changes:type_name -> agentre.wire.CtlChange
	11, // 20: agentre.wire.CtlRequest.list:type_name -> agentre.wire.CtlListRequest
	13, // 21: agentre.wire.CtlRequest.get:type_name -> agentre.wire.CtlGetRequest
	15, // 22: agentre.wire.CtlRequest.write:type_name -> agentre.wire.CtlWriteRequest
	12, // 23: agentre.wire.CtlResponse.list:type_name -> agentre.wire.CtlListResponse
	14, // 24: agentre.wire.CtlResponse.get:type_name -> agentre.wire.CtlGetResponse
	18, // 25: agentre.wire.CtlResponse.write:type_name -> agentre.wire.CtlWriteResponse
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_agentre_wire_ctl_proto_init() }
func file_agentre_wire_ctl_proto_init() {
	if File_agentre_wire_ctl_proto != nil {
		return
	}
	file_agentre_wire_ctl_proto_msgTypes[7].OneofWrappers = []any{
		(*CtlResource_Agent)(nil),
		(*CtlResource_Department)(nil),
		(*CtlResource_Project)(nil),
		(*CtlResource_Provider)(nil),
		(*CtlResource_Model)(nil),
		(*CtlResource_Backend)(nil),
	}
	file_agentre_wire_ctl_proto_msgTypes[13].OneofWrappers = []any{}
	file_agentre_wire_ctl_proto_msgTypes[16].OneofWrappers = []any{
		(*CtlRequest_List)(nil),
		(*CtlRequest_Get)(nil),
		(*CtlRequest_Write)(nil),
	}
	file_agentre_wire_ctl_proto_msgTypes[17].OneofWrappers = []any{
		(*CtlResponse_List)(nil),
		(*CtlResponse_Get)(nil),
		(*CtlResponse_Write)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agentre_wire_ctl_proto_rawDesc), len(file_agentre_wire_ctl_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agentre_wire_ctl_proto_goTypes,
		DependencyIndexes: file_agentre_wire_ctl_proto_depIdxs,
		EnumInfos:         file_agentre_wire_ctl_proto_enumTypes,
		MessageInfos:      file_agentre_wire_ctl_proto_msgTypes,
	}.Build()
	File_agentre_wire_ctl_proto = out.File
	file_agentre_wire_ctl_proto_goTypes = nil
	file_agentre_wire_ctl_proto_depIdxs = nil
}
