// Code generated by MockGen. DO NOT EDIT.
// Source: notification.go
//
// Generated by this command:
//
//	mockgen -source notification.go -destination mock_notification_repo/mock_notification.go
//

// Package mock_notification_repo is a generated GoMock package.
package mock_notification_repo

import (
	context "context"
	reflect "reflect"

	notification_repo "github.com/agentre-hub/agentre/internal/daemon/repository/notification_repo"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationRepo is a mock of NotificationRepo interface.
type MockNotificationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepoMockRecorder
	isgomock struct{}
}

// MockNotificationRepoMockRecorder is the mock recorder for MockNotificationRepo.
type MockNotificationRepoMockRecorder struct {
	mock *MockNotificationRepo
}

// NewMockNotificationRepo creates a new mock instance.
func NewMockNotificationRepo(ctrl *gomock.Controller) *MockNotificationRepo {
	mock := &MockNotificationRepo{ctrl: ctrl}
	mock.recorder = &MockNotificationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepo) EXPECT() *MockNotificationRepoMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockNotificationRepo) Append(ctx context.Context, n *notification_repo.NotificationLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockNotificationRepoMockRecorder) Append(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockNotificationRepo)(nil).Append), ctx, n)
}

// DeleteAll mocks base method.
func (m *MockNotificationRepo) DeleteAll(ctx context.Context, peerFingerprint, conversationID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAll", ctx, peerFingerprint, conversationID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAll indicates an expected call of DeleteAll.
func (mr *MockNotificationRepoMockRecorder) DeleteAll(ctx, peerFingerprint, conversationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MockNotificationRepo)(nil).DeleteAll), ctx, peerFingerprint, conversationID)
}

// LatestSeq mocks base method.
func (m *MockNotificationRepo) LatestSeq(ctx context.Context, peerFingerprint, conversationID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestSeq", ctx, peerFingerprint, conversationID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestSeq indicates an expected call of LatestSeq.
func (mr *MockNotificationRepoMockRecorder) LatestSeq(ctx, peerFingerprint, conversationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestSeq", reflect.TypeOf((*MockNotificationRepo)(nil).LatestSeq), ctx, peerFingerprint, conversationID)
}

// LatestSeqByPeer mocks base method.
func (m *MockNotificationRepo) LatestSeqByPeer(ctx context.Context, peerFingerprint string) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestSeqByPeer", ctx, peerFingerprint)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestSeqByPeer indicates an expected call of LatestSeqByPeer.
func (mr *MockNotificationRepoMockRecorder) LatestSeqByPeer(ctx, peerFingerprint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestSeqByPeer", reflect.TypeOf((*MockNotificationRepo)(nil).LatestSeqByPeer), ctx, peerFingerprint)
}

// ListSince mocks base method.
func (m *MockNotificationRepo) ListSince(ctx context.Context, peerFingerprint, conversationID string, cursor int64, limit int) ([]*notification_repo.NotificationLog, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSince", ctx, peerFingerprint, conversationID, cursor, limit)
	ret0, _ := ret[0].([]*notification_repo.NotificationLog)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSince indicates an expected call of ListSince.
func (mr *MockNotificationRepoMockRecorder) ListSince(ctx, peerFingerprint, conversationID, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSince", reflect.TypeOf((*MockNotificationRepo)(nil).ListSince), ctx, peerFingerprint, conversationID, cursor, limit)
}

// OldestSeq mocks base method.
func (m *MockNotificationRepo) OldestSeq(ctx context.Context, peerFingerprint, conversationID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OldestSeq", ctx, peerFingerprint, conversationID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OldestSeq indicates an expected call of OldestSeq.
func (mr *MockNotificationRepoMockRecorder) OldestSeq(ctx, peerFingerprint, conversationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OldestSeq", reflect.TypeOf((*MockNotificationRepo)(nil).OldestSeq), ctx, peerFingerprint, conversationID)
}
