// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source deps.go -destination mock_deps/mock_deps.go -package mock_deps
//

// Package mock_deps is a generated GoMock package.
package mock_deps

import (
	context "context"
	reflect "reflect"

	agent_backend_entity "github.com/agentre-hub/agentre/internal/model/entity/agent_backend_entity"
	agent_entity "github.com/agentre-hub/agentre/internal/model/entity/agent_entity"
	llm_provider_entity "github.com/agentre-hub/agentre/internal/model/entity/llm_provider_entity"
	llm_provider_model_entity "github.com/agentre-hub/agentre/internal/model/entity/llm_provider_model_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentPort is a mock of AgentPort interface.
type MockAgentPort struct {
	ctrl     *gomock.Controller
	recorder *MockAgentPortMockRecorder
	isgomock struct{}
}

// MockAgentPortMockRecorder is the mock recorder for MockAgentPort.
type MockAgentPortMockRecorder struct {
	mock *MockAgentPort
}

// NewMockAgentPort creates a new mock instance.
func NewMockAgentPort(ctrl *gomock.Controller) *MockAgentPort {
	mock := &MockAgentPort{ctrl: ctrl}
	mock.recorder = &MockAgentPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentPort) EXPECT() *MockAgentPortMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockAgentPort) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAgentPortMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAgentPort)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockAgentPort) Find(ctx context.Context, id int64) (*agent_entity.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*agent_entity.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockAgentPortMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAgentPort)(nil).Find), ctx, id)
}

// FindSystem mocks base method.
func (m *MockAgentPort) FindSystem(ctx context.Context) (*agent_entity.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSystem", ctx)
	ret0, _ := ret[0].(*agent_entity.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSystem indicates an expected call of FindSystem.
func (mr *MockAgentPortMockRecorder) FindSystem(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSystem", reflect.TypeOf((*MockAgentPort)(nil).FindSystem), ctx)
}

// List mocks base method.
func (m *MockAgentPort) List(ctx context.Context) ([]*agent_entity.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*agent_entity.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAgentPortMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAgentPort)(nil).List), ctx)
}

// ListByDepartment mocks base method.
func (m *MockAgentPort) ListByDepartment(ctx context.Context, departmentID int64) ([]*agent_entity.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByDepartment", ctx, departmentID)
	ret0, _ := ret[0].([]*agent_entity.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByDepartment indicates an expected call of ListByDepartment.
func (mr *MockAgentPortMockRecorder) ListByDepartment(ctx, departmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByDepartment", reflect.TypeOf((*MockAgentPort)(nil).ListByDepartment), ctx, departmentID)
}

// UpdatePlacement mocks base method.
func (m *MockAgentPort) UpdatePlacement(ctx context.Context, id, departmentID, parentAgentID int64, sortOrder int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlacement", ctx, id, departmentID, parentAgentID, sortOrder)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePlacement indicates an expected call of UpdatePlacement.
func (mr *MockAgentPortMockRecorder) UpdatePlacement(ctx, id, departmentID, parentAgentID, sortOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlacement", reflect.TypeOf((*MockAgentPort)(nil).UpdatePlacement), ctx, id, departmentID, parentAgentID, sortOrder)
}

// MockAgentExecTargetPort is a mock of AgentExecTargetPort interface.
type MockAgentExecTargetPort struct {
	ctrl     *gomock.Controller
	recorder *MockAgentExecTargetPortMockRecorder
	isgomock struct{}
}

// MockAgentExecTargetPortMockRecorder is the mock recorder for MockAgentExecTargetPort.
type MockAgentExecTargetPortMockRecorder struct {
	mock *MockAgentExecTargetPort
}

// NewMockAgentExecTargetPort creates a new mock instance.
func NewMockAgentExecTargetPort(ctrl *gomock.Controller) *MockAgentExecTargetPort {
	mock := &MockAgentExecTargetPort{ctrl: ctrl}
	mock.recorder = &MockAgentExecTargetPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentExecTargetPort) EXPECT() *MockAgentExecTargetPortMockRecorder {
	return m.recorder
}

// ListByAgents mocks base method.
func (m *MockAgentExecTargetPort) ListByAgents(ctx context.Context, agentIDs []int64) (map[int64][]*agent_entity.AgentExecTarget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAgents", ctx, agentIDs)
	ret0, _ := ret[0].(map[int64][]*agent_entity.AgentExecTarget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAgents indicates an expected call of ListByAgents.
func (mr *MockAgentExecTargetPortMockRecorder) ListByAgents(ctx, agentIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAgents", reflect.TypeOf((*MockAgentExecTargetPort)(nil).ListByAgents), ctx, agentIDs)
}

// MockAgentBackendPort is a mock of AgentBackendPort interface.
type MockAgentBackendPort struct {
	ctrl     *gomock.Controller
	recorder *MockAgentBackendPortMockRecorder
	isgomock struct{}
}

// MockAgentBackendPortMockRecorder is the mock recorder for MockAgentBackendPort.
type MockAgentBackendPortMockRecorder struct {
	mock *MockAgentBackendPort
}

// NewMockAgentBackendPort creates a new mock instance.
func NewMockAgentBackendPort(ctrl *gomock.Controller) *MockAgentBackendPort {
	mock := &MockAgentBackendPort{ctrl: ctrl}
	mock.recorder = &MockAgentBackendPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentBackendPort) EXPECT() *MockAgentBackendPortMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockAgentBackendPort) List(ctx context.Context) ([]*agent_backend_entity.AgentBackend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*agent_backend_entity.AgentBackend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAgentBackendPortMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAgentBackendPort)(nil).List), ctx)
}

// MockLLMProviderPort is a mock of LLMProviderPort interface.
type MockLLMProviderPort struct {
	ctrl     *gomock.Controller
	recorder *MockLLMProviderPortMockRecorder
	isgomock struct{}
}

// MockLLMProviderPortMockRecorder is the mock recorder for MockLLMProviderPort.
type MockLLMProviderPortMockRecorder struct {
	mock *MockLLMProviderPort
}

// NewMockLLMProviderPort creates a new mock instance.
func NewMockLLMProviderPort(ctrl *gomock.Controller) *MockLLMProviderPort {
	mock := &MockLLMProviderPort{ctrl: ctrl}
	mock.recorder = &MockLLMProviderPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMProviderPort) EXPECT() *MockLLMProviderPortMockRecorder {
	return m.recorder
}

// FindModelByKey mocks base method.
func (m *MockLLMProviderPort) FindModelByKey(ctx context.Context, modelKey string) (*llm_provider_model_entity.LLMProviderModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindModelByKey", ctx, modelKey)
	ret0, _ := ret[0].(*llm_provider_model_entity.LLMProviderModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindModelByKey indicates an expected call of FindModelByKey.
func (mr *MockLLMProviderPortMockRecorder) FindModelByKey(ctx, modelKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindModelByKey", reflect.TypeOf((*MockLLMProviderPort)(nil).FindModelByKey), ctx, modelKey)
}

// List mocks base method.
func (m *MockLLMProviderPort) List(ctx context.Context) ([]*llm_provider_entity.LLMProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*llm_provider_entity.LLMProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockLLMProviderPortMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockLLMProviderPort)(nil).List), ctx)
}
