import type { TFunction } from "i18next";
import { Braces, Terminal } from "lucide-react";
import type { LucideIcon } from "lucide-react";

import { formatRelativeTime as sharedFormatRelativeTime } from "@agentre-hub/agentre-ui";

import type { hook_svc } from "../../../wailsjs/go/models";

// ── Domain types (generated by wailsjs from hook_svc.*) ───────────────────────

export type EnvVar = hook_svc.EnvVar;
export type InterpreterOption = hook_svc.InterpreterOption;
export type HookItem = hook_svc.HookItem;
export type HookEventItem = hook_svc.HookEventItem;
export type RunHookResult = hook_svc.RunHookResult;

export type Draft = {
  id: number | null; // null = creating a new hook
  name: string;
  interpreter: string;
  interpreterPath: string;
  command: string;
  scheduleExpr: string;
  timezone: string;
  env: EnvVar[];
  enabled: boolean;
};

export type FlashState = { kind: "ok" | "err"; text: string } | null;
export type HookTab = "script" | "runLog";
export type HookStatus = "ok" | "failed" | "running" | "disabled" | "idle";

// ── Constants ────────────────────────────────────────────────────────────────

// Secret env values come back from the backend as "********" and round-trip
// unchanged through CreateHook/UpdateHook, where preserveSecrets keeps the
// stored value — so the UI never needs the plaintext.

export const INTERP_META: Record<
  string,
  { abbrev: string; icon: LucideIcon; color: string }
> = {
  bash: { abbrev: "SH", icon: Terminal, color: "agent-8" },
  sh: { abbrev: "SH", icon: Terminal, color: "agent-8" },
  node: { abbrev: "JS", icon: Braces, color: "agent-1" },
  python: { abbrev: "PY", icon: Terminal, color: "agent-4" },
  pwsh: { abbrev: "PS7", icon: Terminal, color: "agent-3" },
  powershell: { abbrev: "PS", icon: Terminal, color: "agent-5" },
  cmd: { abbrev: "CMD", icon: Terminal, color: "agent-15" },
};

export function interpMeta(interpreter: string) {
  return (
    INTERP_META[interpreter] ?? {
      abbrev: interpreter.toUpperCase(),
      icon: Terminal,
      color: "agent-15",
    }
  );
}

// ── Helpers ──────────────────────────────────────────────────────────────────

/**
 * 档位阶梯与文案都在共享包里（`formatRelativeTime`）。这一页要的是「N 秒前」这一
 * 档而不是「刚刚」—— hook 刚跑完 3 秒与跑完 59 秒在这张列表上不是同一句话。
 */
export function formatRelativeTime(ms: number, t: TFunction): string {
  return sharedFormatRelativeTime(ms, Date.now(), t, { seconds: true });
}

export function hookStatus(h: HookItem): HookStatus {
  if (!h.enabled) return "disabled";
  if (h.lastStatus === "failed") return "failed";
  if (h.lastStatus === "running") return "running";
  if (h.lastStatus === "ok") return "ok";
  return "idle";
}

export function draftFromHook(h: HookItem): Draft {
  return {
    id: h.id,
    name: h.name,
    interpreter: h.interpreter,
    interpreterPath: h.interpreterPath ?? "",
    command: h.command,
    scheduleExpr: h.scheduleExpr,
    timezone: h.timezone || "Asia/Shanghai",
    env: (h.env ?? []).map((e) => ({ ...e })),
    enabled: h.enabled,
  };
}

export function emptyDraft(t: TFunction): Draft {
  return {
    id: null,
    name: t("hooks.create.defaultName"),
    interpreter: "bash",
    interpreterPath: "",
    command: "",
    scheduleExpr: "*/5 * * * *",
    timezone: "Asia/Shanghai",
    env: [],
    enabled: true,
  };
}

export function hookMatchesQuery(h: HookItem, query: string): boolean {
  const q = query.trim().toLowerCase();
  if (!q) return true;
  return `${h.name} ${h.interpreter} ${h.scheduleExpr}`
    .toLowerCase()
    .includes(q);
}

export function runOk(result: RunHookResult): boolean {
  return result.exitCode === 0 && !result.parseError && !result.timedOut;
}
