// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source ports.go -destination mock_peer_svc/mock_ports.go
//

// Package mock_peer_svc is a generated GoMock package.
package mock_peer_svc

import (
	context "context"
	reflect "reflect"

	client "github.com/agentre-hub/agentre/internal/daemon/client"
	agent_entity "github.com/agentre-hub/agentre/internal/model/entity/agent_entity"
	project_entity "github.com/agentre-hub/agentre/internal/model/entity/project_entity"
	wire "github.com/agentre-hub/agentre/internal/pkg/agentruntime/runtimes/remote/wire"
	peer_svc "github.com/agentre-hub/agentre/internal/service/peer_svc"
	gomock "go.uber.org/mock/gomock"
)

// MockDialer is a mock of Dialer interface.
type MockDialer struct {
	ctrl     *gomock.Controller
	recorder *MockDialerMockRecorder
	isgomock struct{}
}

// MockDialerMockRecorder is the mock recorder for MockDialer.
type MockDialerMockRecorder struct {
	mock *MockDialer
}

// NewMockDialer creates a new mock instance.
func NewMockDialer(ctrl *gomock.Controller) *MockDialer {
	mock := &MockDialer{ctrl: ctrl}
	mock.recorder = &MockDialerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDialer) EXPECT() *MockDialerMockRecorder {
	return m.recorder
}

// DialDesktopRelay mocks base method.
func (m *MockDialer) DialDesktopRelay(ctx context.Context, desktopFingerprint, peerFingerprint string) (client.ProtobufConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DialDesktopRelay", ctx, desktopFingerprint, peerFingerprint)
	ret0, _ := ret[0].(client.ProtobufConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DialDesktopRelay indicates an expected call of DialDesktopRelay.
func (mr *MockDialerMockRecorder) DialDesktopRelay(ctx, desktopFingerprint, peerFingerprint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DialDesktopRelay", reflect.TypeOf((*MockDialer)(nil).DialDesktopRelay), ctx, desktopFingerprint, peerFingerprint)
}

// MockEmitter is a mock of Emitter interface.
type MockEmitter struct {
	ctrl     *gomock.Controller
	recorder *MockEmitterMockRecorder
	isgomock struct{}
}

// MockEmitterMockRecorder is the mock recorder for MockEmitter.
type MockEmitterMockRecorder struct {
	mock *MockEmitter
}

// NewMockEmitter creates a new mock instance.
func NewMockEmitter(ctrl *gomock.Controller) *MockEmitter {
	mock := &MockEmitter{ctrl: ctrl}
	mock.recorder = &MockEmitterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmitter) EXPECT() *MockEmitterMockRecorder {
	return m.recorder
}

// Emit mocks base method.
func (m *MockEmitter) Emit(event peer_svc.PeerEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Emit", event)
}

// Emit indicates an expected call of Emit.
func (mr *MockEmitterMockRecorder) Emit(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Emit", reflect.TypeOf((*MockEmitter)(nil).Emit), event)
}

// MockFingerprintProvider is a mock of FingerprintProvider interface.
type MockFingerprintProvider struct {
	ctrl     *gomock.Controller
	recorder *MockFingerprintProviderMockRecorder
	isgomock struct{}
}

// MockFingerprintProviderMockRecorder is the mock recorder for MockFingerprintProvider.
type MockFingerprintProviderMockRecorder struct {
	mock *MockFingerprintProvider
}

// NewMockFingerprintProvider creates a new mock instance.
func NewMockFingerprintProvider(ctrl *gomock.Controller) *MockFingerprintProvider {
	mock := &MockFingerprintProvider{ctrl: ctrl}
	mock.recorder = &MockFingerprintProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFingerprintProvider) EXPECT() *MockFingerprintProviderMockRecorder {
	return m.recorder
}

// DeviceFingerprint mocks base method.
func (m *MockFingerprintProvider) DeviceFingerprint() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeviceFingerprint")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeviceFingerprint indicates an expected call of DeviceFingerprint.
func (mr *MockFingerprintProviderMockRecorder) DeviceFingerprint() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeviceFingerprint", reflect.TypeOf((*MockFingerprintProvider)(nil).DeviceFingerprint))
}

// MockAgentLookup is a mock of AgentLookup interface.
type MockAgentLookup struct {
	ctrl     *gomock.Controller
	recorder *MockAgentLookupMockRecorder
	isgomock struct{}
}

// MockAgentLookupMockRecorder is the mock recorder for MockAgentLookup.
type MockAgentLookupMockRecorder struct {
	mock *MockAgentLookup
}

// NewMockAgentLookup creates a new mock instance.
func NewMockAgentLookup(ctrl *gomock.Controller) *MockAgentLookup {
	mock := &MockAgentLookup{ctrl: ctrl}
	mock.recorder = &MockAgentLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentLookup) EXPECT() *MockAgentLookupMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockAgentLookup) Find(ctx context.Context, id int64) (*agent_entity.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*agent_entity.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockAgentLookupMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAgentLookup)(nil).Find), ctx, id)
}

// MockProjectLookup is a mock of ProjectLookup interface.
type MockProjectLookup struct {
	ctrl     *gomock.Controller
	recorder *MockProjectLookupMockRecorder
	isgomock struct{}
}

// MockProjectLookupMockRecorder is the mock recorder for MockProjectLookup.
type MockProjectLookupMockRecorder struct {
	mock *MockProjectLookup
}

// NewMockProjectLookup creates a new mock instance.
func NewMockProjectLookup(ctrl *gomock.Controller) *MockProjectLookup {
	mock := &MockProjectLookup{ctrl: ctrl}
	mock.recorder = &MockProjectLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectLookup) EXPECT() *MockProjectLookupMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockProjectLookup) Find(ctx context.Context, id int64) (*project_entity.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*project_entity.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockProjectLookupMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockProjectLookup)(nil).Find), ctx, id)
}

// MockPeerSvc is a mock of PeerSvc interface.
type MockPeerSvc struct {
	ctrl     *gomock.Controller
	recorder *MockPeerSvcMockRecorder
	isgomock struct{}
}

// MockPeerSvcMockRecorder is the mock recorder for MockPeerSvc.
type MockPeerSvcMockRecorder struct {
	mock *MockPeerSvc
}

// NewMockPeerSvc creates a new mock instance.
func NewMockPeerSvc(ctrl *gomock.Controller) *MockPeerSvc {
	mock := &MockPeerSvc{ctrl: ctrl}
	mock.recorder = &MockPeerSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPeerSvc) EXPECT() *MockPeerSvcMockRecorder {
	return m.recorder
}

// Attach mocks base method.
func (m *MockPeerSvc) Attach(ctx context.Context, req peer_svc.AttachRequest) (*wire.SessionAttachResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attach", ctx, req)
	ret0, _ := ret[0].(*wire.SessionAttachResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Attach indicates an expected call of Attach.
func (mr *MockPeerSvcMockRecorder) Attach(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attach", reflect.TypeOf((*MockPeerSvc)(nil).Attach), ctx, req)
}

// Close mocks base method.
func (m *MockPeerSvc) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockPeerSvcMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPeerSvc)(nil).Close))
}

// Detach mocks base method.
func (m *MockPeerSvc) Detach(ctx context.Context, fingerprint string, conversationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detach", ctx, fingerprint, conversationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Detach indicates an expected call of Detach.
func (mr *MockPeerSvcMockRecorder) Detach(ctx, fingerprint, conversationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detach", reflect.TypeOf((*MockPeerSvc)(nil).Detach), ctx, fingerprint, conversationID)
}

// ListSessions mocks base method.
func (m *MockPeerSvc) ListSessions(ctx context.Context, fingerprint string) (*wire.SessionListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessions", ctx, fingerprint)
	ret0, _ := ret[0].(*wire.SessionListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSessions indicates an expected call of ListSessions.
func (mr *MockPeerSvcMockRecorder) ListSessions(ctx, fingerprint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessions", reflect.TypeOf((*MockPeerSvc)(nil).ListSessions), ctx, fingerprint)
}

// Pull mocks base method.
func (m *MockPeerSvc) Pull(ctx context.Context, req peer_svc.PullRequest) (*wire.SessionPullResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pull", ctx, req)
	ret0, _ := ret[0].(*wire.SessionPullResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pull indicates an expected call of Pull.
func (mr *MockPeerSvcMockRecorder) Pull(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pull", reflect.TypeOf((*MockPeerSvc)(nil).Pull), ctx, req)
}

// RunFresh mocks base method.
func (m *MockPeerSvc) RunFresh(ctx context.Context, req peer_svc.RunFreshRequest) (wire.RunAck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunFresh", ctx, req)
	ret0, _ := ret[0].(wire.RunAck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunFresh indicates an expected call of RunFresh.
func (mr *MockPeerSvcMockRecorder) RunFresh(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunFresh", reflect.TypeOf((*MockPeerSvc)(nil).RunFresh), ctx, req)
}

// Steer mocks base method.
func (m *MockPeerSvc) Steer(ctx context.Context, req peer_svc.SteerRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Steer", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Steer indicates an expected call of Steer.
func (mr *MockPeerSvcMockRecorder) Steer(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Steer", reflect.TypeOf((*MockPeerSvc)(nil).Steer), ctx, req)
}

// SubmitAnswer mocks base method.
func (m *MockPeerSvc) SubmitAnswer(ctx context.Context, req peer_svc.SubmitAnswerRequest) (*wire.PeerSessionControlResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitAnswer", ctx, req)
	ret0, _ := ret[0].(*wire.PeerSessionControlResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitAnswer indicates an expected call of SubmitAnswer.
func (mr *MockPeerSvcMockRecorder) SubmitAnswer(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitAnswer", reflect.TypeOf((*MockPeerSvc)(nil).SubmitAnswer), ctx, req)
}

// SubmitToolPermission mocks base method.
func (m *MockPeerSvc) SubmitToolPermission(ctx context.Context, req peer_svc.SubmitToolPermissionRequest) (*wire.PeerSessionControlResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitToolPermission", ctx, req)
	ret0, _ := ret[0].(*wire.PeerSessionControlResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitToolPermission indicates an expected call of SubmitToolPermission.
func (mr *MockPeerSvcMockRecorder) SubmitToolPermission(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitToolPermission", reflect.TypeOf((*MockPeerSvc)(nil).SubmitToolPermission), ctx, req)
}
