// Code generated by MockGen. DO NOT EDIT.
// Source: sync_account.go
//
// Generated by this command:
//
//	mockgen -source sync_account.go -destination mock_sync_account_repo/mock_sync_account.go
//

// Package mock_sync_account_repo is a generated GoMock package.
package mock_sync_account_repo

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSyncAccountRepo is a mock of SyncAccountRepo interface.
type MockSyncAccountRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSyncAccountRepoMockRecorder
	isgomock struct{}
}

// MockSyncAccountRepoMockRecorder is the mock recorder for MockSyncAccountRepo.
type MockSyncAccountRepoMockRecorder struct {
	mock *MockSyncAccountRepo
}

// NewMockSyncAccountRepo creates a new mock instance.
func NewMockSyncAccountRepo(ctrl *gomock.Controller) *MockSyncAccountRepo {
	mock := &MockSyncAccountRepo{ctrl: ctrl}
	mock.recorder = &MockSyncAccountRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncAccountRepo) EXPECT() *MockSyncAccountRepoMockRecorder {
	return m.recorder
}

// EnsureKey mocks base method.
func (m *MockSyncAccountRepo) EnsureKey(ctx context.Context, serverURL string, remoteUserID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureKey", ctx, serverURL, remoteUserID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureKey indicates an expected call of EnsureKey.
func (mr *MockSyncAccountRepoMockRecorder) EnsureKey(ctx, serverURL, remoteUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureKey", reflect.TypeOf((*MockSyncAccountRepo)(nil).EnsureKey), ctx, serverURL, remoteUserID)
}
