// Code generated by MockGen. DO NOT EDIT.
// Source: svc.go
//
// Generated by this command:
//
//	mockgen -source svc.go -destination mock_port_forward_svc/mock_svc.go
//

// Package mock_port_forward_svc is a generated GoMock package.
package mock_port_forward_svc

import (
	context "context"
	reflect "reflect"

	port_forward_svc "github.com/agentre-hub/agentre/internal/service/port_forward_svc"
	gomock "go.uber.org/mock/gomock"
)

// MockPortForwardSvc is a mock of PortForwardSvc interface.
type MockPortForwardSvc struct {
	ctrl     *gomock.Controller
	recorder *MockPortForwardSvcMockRecorder
	isgomock struct{}
}

// MockPortForwardSvcMockRecorder is the mock recorder for MockPortForwardSvc.
type MockPortForwardSvcMockRecorder struct {
	mock *MockPortForwardSvc
}

// NewMockPortForwardSvc creates a new mock instance.
func NewMockPortForwardSvc(ctrl *gomock.Controller) *MockPortForwardSvc {
	mock := &MockPortForwardSvc{ctrl: ctrl}
	mock.recorder = &MockPortForwardSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPortForwardSvc) EXPECT() *MockPortForwardSvcMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPortForwardSvc) Create(ctx context.Context, deviceID string, port int, name string) (*port_forward_svc.MappingView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, deviceID, port, name)
	ret0, _ := ret[0].(*port_forward_svc.MappingView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPortForwardSvcMockRecorder) Create(ctx, deviceID, port, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPortForwardSvc)(nil).Create), ctx, deviceID, port, name)
}

// Delete mocks base method.
func (m *MockPortForwardSvc) Delete(ctx context.Context, deviceID, mappingID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, deviceID, mappingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPortForwardSvcMockRecorder) Delete(ctx, deviceID, mappingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPortForwardSvc)(nil).Delete), ctx, deviceID, mappingID)
}

// List mocks base method.
func (m *MockPortForwardSvc) List(ctx context.Context, deviceID string) ([]port_forward_svc.MappingView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, deviceID)
	ret0, _ := ret[0].([]port_forward_svc.MappingView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPortForwardSvcMockRecorder) List(ctx, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPortForwardSvc)(nil).List), ctx, deviceID)
}

// SetEnabled mocks base method.
func (m *MockPortForwardSvc) SetEnabled(ctx context.Context, deviceID, mappingID string, enabled bool) (*port_forward_svc.MappingView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEnabled", ctx, deviceID, mappingID, enabled)
	ret0, _ := ret[0].(*port_forward_svc.MappingView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetEnabled indicates an expected call of SetEnabled.
func (mr *MockPortForwardSvcMockRecorder) SetEnabled(ctx, deviceID, mappingID, enabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEnabled", reflect.TypeOf((*MockPortForwardSvc)(nil).SetEnabled), ctx, deviceID, mappingID, enabled)
}
