// Code generated by MockGen. DO NOT EDIT.
// Source: lost_change.go
//
// Generated by this command:
//
//	mockgen -source lost_change.go -destination mock_syncqueue_repo/mock_lost_change.go
//

// Package mock_syncqueue_repo is a generated GoMock package.
package mock_syncqueue_repo

import (
	context "context"
	reflect "reflect"

	syncqueue_entity "github.com/agentre-hub/agentre/internal/model/entity/syncqueue_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockLostChangeRepo is a mock of LostChangeRepo interface.
type MockLostChangeRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLostChangeRepoMockRecorder
	isgomock struct{}
}

// MockLostChangeRepoMockRecorder is the mock recorder for MockLostChangeRepo.
type MockLostChangeRepoMockRecorder struct {
	mock *MockLostChangeRepo
}

// NewMockLostChangeRepo creates a new mock instance.
func NewMockLostChangeRepo(ctrl *gomock.Controller) *MockLostChangeRepo {
	mock := &MockLostChangeRepo{ctrl: ctrl}
	mock.recorder = &MockLostChangeRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLostChangeRepo) EXPECT() *MockLostChangeRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLostChangeRepo) Create(ctx context.Context, row *syncqueue_entity.LostChange) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, row)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLostChangeRepoMockRecorder) Create(ctx, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLostChangeRepo)(nil).Create), ctx, row)
}

// Delete mocks base method.
func (m *MockLostChangeRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLostChangeRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLostChangeRepo)(nil).Delete), ctx, id)
}

// ListByAccount mocks base method.
func (m *MockLostChangeRepo) ListByAccount(ctx context.Context, accountID int64) ([]*syncqueue_entity.LostChange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAccount", ctx, accountID)
	ret0, _ := ret[0].([]*syncqueue_entity.LostChange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAccount indicates an expected call of ListByAccount.
func (mr *MockLostChangeRepoMockRecorder) ListByAccount(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAccount", reflect.TypeOf((*MockLostChangeRepo)(nil).ListByAccount), ctx, accountID)
}
