// Code generated by MockGen. DO NOT EDIT.
// Source: outbound_queue.go
//
// Generated by this command:
//
//	mockgen -source outbound_queue.go -destination mock_syncqueue_repo/mock_outbound_queue.go
//

// Package mock_syncqueue_repo is a generated GoMock package.
package mock_syncqueue_repo

import (
	context "context"
	reflect "reflect"

	syncqueue_entity "github.com/agentre-hub/agentre/internal/model/entity/syncqueue_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockOutboundQueueRepo is a mock of OutboundQueueRepo interface.
type MockOutboundQueueRepo struct {
	ctrl     *gomock.Controller
	recorder *MockOutboundQueueRepoMockRecorder
	isgomock struct{}
}

// MockOutboundQueueRepoMockRecorder is the mock recorder for MockOutboundQueueRepo.
type MockOutboundQueueRepoMockRecorder struct {
	mock *MockOutboundQueueRepo
}

// NewMockOutboundQueueRepo creates a new mock instance.
func NewMockOutboundQueueRepo(ctrl *gomock.Controller) *MockOutboundQueueRepo {
	mock := &MockOutboundQueueRepo{ctrl: ctrl}
	mock.recorder = &MockOutboundQueueRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboundQueueRepo) EXPECT() *MockOutboundQueueRepoMockRecorder {
	return m.recorder
}

// CreateMany mocks base method.
func (m *MockOutboundQueueRepo) CreateMany(ctx context.Context, rows []*syncqueue_entity.OutboundQueueItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMany", ctx, rows)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMany indicates an expected call of CreateMany.
func (mr *MockOutboundQueueRepoMockRecorder) CreateMany(ctx, rows any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMany", reflect.TypeOf((*MockOutboundQueueRepo)(nil).CreateMany), ctx, rows)
}

// DeleteMany mocks base method.
func (m *MockOutboundQueueRepo) DeleteMany(ctx context.Context, ids []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMany", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMany indicates an expected call of DeleteMany.
func (mr *MockOutboundQueueRepoMockRecorder) DeleteMany(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMany", reflect.TypeOf((*MockOutboundQueueRepo)(nil).DeleteMany), ctx, ids)
}

// ListByAccount mocks base method.
func (m *MockOutboundQueueRepo) ListByAccount(ctx context.Context, accountID int64) ([]*syncqueue_entity.OutboundQueueItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAccount", ctx, accountID)
	ret0, _ := ret[0].([]*syncqueue_entity.OutboundQueueItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAccount indicates an expected call of ListByAccount.
func (mr *MockOutboundQueueRepoMockRecorder) ListByAccount(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAccount", reflect.TypeOf((*MockOutboundQueueRepo)(nil).ListByAccount), ctx, accountID)
}

// ReassignAccount mocks base method.
func (m *MockOutboundQueueRepo) ReassignAccount(ctx context.Context, from, to int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReassignAccount", ctx, from, to)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReassignAccount indicates an expected call of ReassignAccount.
func (mr *MockOutboundQueueRepoMockRecorder) ReassignAccount(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReassignAccount", reflect.TypeOf((*MockOutboundQueueRepo)(nil).ReassignAccount), ctx, from, to)
}
