// Code generated by MockGen. DO NOT EDIT.
// Source: outbound_queue.go
//
// Generated by this command:
//
//	mockgen -source outbound_queue.go -destination mock_syncqueue_repo/mock_outbound_queue.go
//

// Package mock_syncqueue_repo is a generated GoMock package.
package mock_syncqueue_repo

import (
	context "context"
	reflect "reflect"

	syncqueue_entity "github.com/agentre-hub/agentre/internal/model/entity/syncqueue_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockOutboundQueueRepo is a mock of OutboundQueueRepo interface.
type MockOutboundQueueRepo struct {
	ctrl     *gomock.Controller
	recorder *MockOutboundQueueRepoMockRecorder
	isgomock struct{}
}

// MockOutboundQueueRepoMockRecorder is the mock recorder for MockOutboundQueueRepo.
type MockOutboundQueueRepoMockRecorder struct {
	mock *MockOutboundQueueRepo
}

// NewMockOutboundQueueRepo creates a new mock instance.
func NewMockOutboundQueueRepo(ctrl *gomock.Controller) *MockOutboundQueueRepo {
	mock := &MockOutboundQueueRepo{ctrl: ctrl}
	mock.recorder = &MockOutboundQueueRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboundQueueRepo) EXPECT() *MockOutboundQueueRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOutboundQueueRepo) Create(ctx context.Context, row *syncqueue_entity.OutboundQueueItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, row)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOutboundQueueRepoMockRecorder) Create(ctx, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOutboundQueueRepo)(nil).Create), ctx, row)
}

// Delete mocks base method.
func (m *MockOutboundQueueRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOutboundQueueRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOutboundQueueRepo)(nil).Delete), ctx, id)
}

// DeleteMany mocks base method.
func (m *MockOutboundQueueRepo) DeleteMany(ctx context.Context, ids []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMany", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMany indicates an expected call of DeleteMany.
func (mr *MockOutboundQueueRepoMockRecorder) DeleteMany(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMany", reflect.TypeOf((*MockOutboundQueueRepo)(nil).DeleteMany), ctx, ids)
}

// ListByAccount mocks base method.
func (m *MockOutboundQueueRepo) ListByAccount(ctx context.Context, accountID int64) ([]*syncqueue_entity.OutboundQueueItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAccount", ctx, accountID)
	ret0, _ := ret[0].([]*syncqueue_entity.OutboundQueueItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAccount indicates an expected call of ListByAccount.
func (mr *MockOutboundQueueRepoMockRecorder) ListByAccount(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAccount", reflect.TypeOf((*MockOutboundQueueRepo)(nil).ListByAccount), ctx, accountID)
}
