// 「首字母」那一档:用 agent 名字的首字母当头像的预览与说明。

import { useTranslation } from "react-i18next";
import { getAgentInitials } from "@agentre-hub/agentre-ui";

import { cn } from "@/lib/utils";

import { agentColorClassNames, type AgentColor } from "../types";

export function LetterModePanel({
  name,
  color,
}: {
  name: string;
  color: AgentColor;
}) {
  const { t } = useTranslation();
  return (
    <div className="flex items-center gap-3 px-3 py-3">
      <div
        aria-hidden="true"
        className={cn(
          "inline-flex size-16 shrink-0 items-center justify-center rounded-lg text-2xl font-semibold text-agent-foreground",
          agentColorClassNames[color],
        )}
      >
        {getAgentInitials(name)}
      </div>
      <div className="flex flex-col gap-0.5">
        <span className="text-sm font-semibold">
          {t("iconPicker.avatar.autoGenerated", {
            initials: getAgentInitials(name),
          })}
        </span>
        <span className="font-mono text-2xs text-muted-foreground">
          {t("iconPicker.avatar.letterHint")}
        </span>
      </div>
    </div>
  );
}
