// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source deps.go -destination mock_project_svc/mock_deps.go
//

// Package mock_project_svc is a generated GoMock package.
package mock_project_svc

import (
	context "context"
	reflect "reflect"

	agent_entity "github.com/agentre-hub/agentre/internal/model/entity/agent_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionPort is a mock of SessionPort interface.
type MockSessionPort struct {
	ctrl     *gomock.Controller
	recorder *MockSessionPortMockRecorder
	isgomock struct{}
}

// MockSessionPortMockRecorder is the mock recorder for MockSessionPort.
type MockSessionPortMockRecorder struct {
	mock *MockSessionPort
}

// NewMockSessionPort creates a new mock instance.
func NewMockSessionPort(ctrl *gomock.Controller) *MockSessionPort {
	mock := &MockSessionPort{ctrl: ctrl}
	mock.recorder = &MockSessionPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionPort) EXPECT() *MockSessionPortMockRecorder {
	return m.recorder
}

// CountActiveByProject mocks base method.
func (m *MockSessionPort) CountActiveByProject(ctx context.Context, projectID int64, agentStatuses []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveByProject", ctx, projectID, agentStatuses)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveByProject indicates an expected call of CountActiveByProject.
func (mr *MockSessionPortMockRecorder) CountActiveByProject(ctx, projectID, agentStatuses any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveByProject", reflect.TypeOf((*MockSessionPort)(nil).CountActiveByProject), ctx, projectID, agentStatuses)
}

// ReassignProject mocks base method.
func (m *MockSessionPort) ReassignProject(ctx context.Context, fromProjectID, toProjectID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReassignProject", ctx, fromProjectID, toProjectID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReassignProject indicates an expected call of ReassignProject.
func (mr *MockSessionPortMockRecorder) ReassignProject(ctx, fromProjectID, toProjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReassignProject", reflect.TypeOf((*MockSessionPort)(nil).ReassignProject), ctx, fromProjectID, toProjectID)
}

// MockAgentPort is a mock of AgentPort interface.
type MockAgentPort struct {
	ctrl     *gomock.Controller
	recorder *MockAgentPortMockRecorder
	isgomock struct{}
}

// MockAgentPortMockRecorder is the mock recorder for MockAgentPort.
type MockAgentPortMockRecorder struct {
	mock *MockAgentPort
}

// NewMockAgentPort creates a new mock instance.
func NewMockAgentPort(ctrl *gomock.Controller) *MockAgentPort {
	mock := &MockAgentPort{ctrl: ctrl}
	mock.recorder = &MockAgentPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentPort) EXPECT() *MockAgentPortMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockAgentPort) Find(ctx context.Context, id int64) (*agent_entity.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*agent_entity.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockAgentPortMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAgentPort)(nil).Find), ctx, id)
}

// List mocks base method.
func (m *MockAgentPort) List(ctx context.Context) ([]*agent_entity.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*agent_entity.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAgentPortMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAgentPort)(nil).List), ctx)
}
