// Code generated by MockGen. DO NOT EDIT.
// Source: port_forward.go
//
// Generated by this command:
//
//	mockgen -source port_forward.go -destination mock_port_forward_repo/mock_port_forward.go
//

// Package mock_port_forward_repo is a generated GoMock package.
package mock_port_forward_repo

import (
	context "context"
	reflect "reflect"

	port_forward_entity "github.com/agentre-hub/agentre/internal/model/entity/port_forward_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockPortForwardRepo is a mock of PortForwardRepo interface.
type MockPortForwardRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPortForwardRepoMockRecorder
	isgomock struct{}
}

// MockPortForwardRepoMockRecorder is the mock recorder for MockPortForwardRepo.
type MockPortForwardRepoMockRecorder struct {
	mock *MockPortForwardRepo
}

// NewMockPortForwardRepo creates a new mock instance.
func NewMockPortForwardRepo(ctrl *gomock.Controller) *MockPortForwardRepo {
	mock := &MockPortForwardRepo{ctrl: ctrl}
	mock.recorder = &MockPortForwardRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPortForwardRepo) EXPECT() *MockPortForwardRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPortForwardRepo) Create(ctx context.Context, p *port_forward_entity.PortForward) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPortForwardRepoMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPortForwardRepo)(nil).Create), ctx, p)
}

// Delete mocks base method.
func (m *MockPortForwardRepo) Delete(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockPortForwardRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPortForwardRepo)(nil).Delete), ctx, id)
}

// FindByPort mocks base method.
func (m *MockPortForwardRepo) FindByPort(ctx context.Context, port int) (*port_forward_entity.PortForward, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPort", ctx, port)
	ret0, _ := ret[0].(*port_forward_entity.PortForward)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByPort indicates an expected call of FindByPort.
func (mr *MockPortForwardRepoMockRecorder) FindByPort(ctx, port any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPort", reflect.TypeOf((*MockPortForwardRepo)(nil).FindByPort), ctx, port)
}

// Get mocks base method.
func (m *MockPortForwardRepo) Get(ctx context.Context, id int64) (*port_forward_entity.PortForward, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*port_forward_entity.PortForward)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPortForwardRepoMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPortForwardRepo)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockPortForwardRepo) List(ctx context.Context) ([]*port_forward_entity.PortForward, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*port_forward_entity.PortForward)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPortForwardRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPortForwardRepo)(nil).List), ctx)
}

// SetEnabled mocks base method.
func (m *MockPortForwardRepo) SetEnabled(ctx context.Context, id int64, enabled bool) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEnabled", ctx, id, enabled)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetEnabled indicates an expected call of SetEnabled.
func (mr *MockPortForwardRepoMockRecorder) SetEnabled(ctx, id, enabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEnabled", reflect.TypeOf((*MockPortForwardRepo)(nil).SetEnabled), ctx, id, enabled)
}
