// Code generated by MockGen. DO NOT EDIT.
// Source: llm_provider.go
//
// Generated by this command:
//
//	mockgen -source llm_provider.go -destination mock_llm_provider_repo/mock_llm_provider.go
//

// Package mock_llm_provider_repo is a generated GoMock package.
package mock_llm_provider_repo

import (
	context "context"
	reflect "reflect"

	llm_provider_entity "github.com/agentre-hub/agentre/internal/model/entity/llm_provider_entity"
	llm_provider_model_entity "github.com/agentre-hub/agentre/internal/model/entity/llm_provider_model_entity"
	llm_provider_repo "github.com/agentre-hub/agentre/internal/repository/llm_provider_repo"
	gomock "go.uber.org/mock/gomock"
)

// MockLLMProviderRepo is a mock of LLMProviderRepo interface.
type MockLLMProviderRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLLMProviderRepoMockRecorder
	isgomock struct{}
}

// MockLLMProviderRepoMockRecorder is the mock recorder for MockLLMProviderRepo.
type MockLLMProviderRepoMockRecorder struct {
	mock *MockLLMProviderRepo
}

// NewMockLLMProviderRepo creates a new mock instance.
func NewMockLLMProviderRepo(ctrl *gomock.Controller) *MockLLMProviderRepo {
	mock := &MockLLMProviderRepo{ctrl: ctrl}
	mock.recorder = &MockLLMProviderRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMProviderRepo) EXPECT() *MockLLMProviderRepoMockRecorder {
	return m.recorder
}

// BatchFindByKey mocks base method.
func (m *MockLLMProviderRepo) BatchFindByKey(ctx context.Context, keys []string) (map[string]*llm_provider_entity.LLMProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchFindByKey", ctx, keys)
	ret0, _ := ret[0].(map[string]*llm_provider_entity.LLMProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchFindByKey indicates an expected call of BatchFindByKey.
func (mr *MockLLMProviderRepoMockRecorder) BatchFindByKey(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchFindByKey", reflect.TypeOf((*MockLLMProviderRepo)(nil).BatchFindByKey), ctx, keys)
}

// CountModelReferences mocks base method.
func (m *MockLLMProviderRepo) CountModelReferences(ctx context.Context, modelKey string) (llm_provider_repo.ModelRefCounts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountModelReferences", ctx, modelKey)
	ret0, _ := ret[0].(llm_provider_repo.ModelRefCounts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountModelReferences indicates an expected call of CountModelReferences.
func (mr *MockLLMProviderRepoMockRecorder) CountModelReferences(ctx, modelKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountModelReferences", reflect.TypeOf((*MockLLMProviderRepo)(nil).CountModelReferences), ctx, modelKey)
}

// CountModelsByProvider mocks base method.
func (m *MockLLMProviderRepo) CountModelsByProvider(ctx context.Context, providerIDs []int64) (map[int64]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountModelsByProvider", ctx, providerIDs)
	ret0, _ := ret[0].(map[int64]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountModelsByProvider indicates an expected call of CountModelsByProvider.
func (mr *MockLLMProviderRepoMockRecorder) CountModelsByProvider(ctx, providerIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountModelsByProvider", reflect.TypeOf((*MockLLMProviderRepo)(nil).CountModelsByProvider), ctx, providerIDs)
}

// CountProviderReferences mocks base method.
func (m *MockLLMProviderRepo) CountProviderReferences(ctx context.Context, providerKey string) (llm_provider_repo.ProviderRefCounts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountProviderReferences", ctx, providerKey)
	ret0, _ := ret[0].(llm_provider_repo.ProviderRefCounts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountProviderReferences indicates an expected call of CountProviderReferences.
func (mr *MockLLMProviderRepoMockRecorder) CountProviderReferences(ctx, providerKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountProviderReferences", reflect.TypeOf((*MockLLMProviderRepo)(nil).CountProviderReferences), ctx, providerKey)
}

// CreateModel mocks base method.
func (m_2 *MockLLMProviderRepo) CreateModel(ctx context.Context, m *llm_provider_model_entity.LLMProviderModel) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "CreateModel", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateModel indicates an expected call of CreateModel.
func (mr *MockLLMProviderRepoMockRecorder) CreateModel(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateModel", reflect.TypeOf((*MockLLMProviderRepo)(nil).CreateModel), ctx, m)
}

// CreateWithModels mocks base method.
func (m *MockLLMProviderRepo) CreateWithModels(ctx context.Context, p *llm_provider_entity.LLMProvider, models []*llm_provider_model_entity.LLMProviderModel, defaultModelKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithModels", ctx, p, models, defaultModelKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithModels indicates an expected call of CreateWithModels.
func (mr *MockLLMProviderRepoMockRecorder) CreateWithModels(ctx, p, models, defaultModelKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithModels", reflect.TypeOf((*MockLLMProviderRepo)(nil).CreateWithModels), ctx, p, models, defaultModelKey)
}

// DeleteModel mocks base method.
func (m *MockLLMProviderRepo) DeleteModel(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteModel", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteModel indicates an expected call of DeleteModel.
func (mr *MockLLMProviderRepoMockRecorder) DeleteModel(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteModel", reflect.TypeOf((*MockLLMProviderRepo)(nil).DeleteModel), ctx, id)
}

// DeleteWithModels mocks base method.
func (m *MockLLMProviderRepo) DeleteWithModels(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWithModels", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWithModels indicates an expected call of DeleteWithModels.
func (mr *MockLLMProviderRepoMockRecorder) DeleteWithModels(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWithModels", reflect.TypeOf((*MockLLMProviderRepo)(nil).DeleteWithModels), ctx, id)
}

// Find mocks base method.
func (m *MockLLMProviderRepo) Find(ctx context.Context, id int64) (*llm_provider_entity.LLMProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*llm_provider_entity.LLMProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockLLMProviderRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockLLMProviderRepo)(nil).Find), ctx, id)
}

// FindByKey mocks base method.
func (m *MockLLMProviderRepo) FindByKey(ctx context.Context, key string) (*llm_provider_entity.LLMProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByKey", ctx, key)
	ret0, _ := ret[0].(*llm_provider_entity.LLMProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByKey indicates an expected call of FindByKey.
func (mr *MockLLMProviderRepoMockRecorder) FindByKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByKey", reflect.TypeOf((*MockLLMProviderRepo)(nil).FindByKey), ctx, key)
}

// FindByName mocks base method.
func (m *MockLLMProviderRepo) FindByName(ctx context.Context, name string) (*llm_provider_entity.LLMProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].(*llm_provider_entity.LLMProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockLLMProviderRepoMockRecorder) FindByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockLLMProviderRepo)(nil).FindByName), ctx, name)
}

// FindModel mocks base method.
func (m *MockLLMProviderRepo) FindModel(ctx context.Context, id int64) (*llm_provider_model_entity.LLMProviderModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindModel", ctx, id)
	ret0, _ := ret[0].(*llm_provider_model_entity.LLMProviderModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindModel indicates an expected call of FindModel.
func (mr *MockLLMProviderRepoMockRecorder) FindModel(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindModel", reflect.TypeOf((*MockLLMProviderRepo)(nil).FindModel), ctx, id)
}

// FindModelByKey mocks base method.
func (m *MockLLMProviderRepo) FindModelByKey(ctx context.Context, modelKey string) (*llm_provider_model_entity.LLMProviderModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindModelByKey", ctx, modelKey)
	ret0, _ := ret[0].(*llm_provider_model_entity.LLMProviderModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindModelByKey indicates an expected call of FindModelByKey.
func (mr *MockLLMProviderRepoMockRecorder) FindModelByKey(ctx, modelKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindModelByKey", reflect.TypeOf((*MockLLMProviderRepo)(nil).FindModelByKey), ctx, modelKey)
}

// ImportModels mocks base method.
func (m *MockLLMProviderRepo) ImportModels(ctx context.Context, updates, inserts []*llm_provider_model_entity.LLMProviderModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportModels", ctx, updates, inserts)
	ret0, _ := ret[0].(error)
	return ret0
}

// ImportModels indicates an expected call of ImportModels.
func (mr *MockLLMProviderRepoMockRecorder) ImportModels(ctx, updates, inserts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportModels", reflect.TypeOf((*MockLLMProviderRepo)(nil).ImportModels), ctx, updates, inserts)
}

// List mocks base method.
func (m *MockLLMProviderRepo) List(ctx context.Context) ([]*llm_provider_entity.LLMProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*llm_provider_entity.LLMProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockLLMProviderRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockLLMProviderRepo)(nil).List), ctx)
}

// ListModels mocks base method.
func (m *MockLLMProviderRepo) ListModels(ctx context.Context, providerID int64) ([]*llm_provider_model_entity.LLMProviderModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModels", ctx, providerID)
	ret0, _ := ret[0].([]*llm_provider_model_entity.LLMProviderModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModels indicates an expected call of ListModels.
func (mr *MockLLMProviderRepoMockRecorder) ListModels(ctx, providerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModels", reflect.TypeOf((*MockLLMProviderRepo)(nil).ListModels), ctx, providerID)
}

// Update mocks base method.
func (m *MockLLMProviderRepo) Update(ctx context.Context, p *llm_provider_entity.LLMProvider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockLLMProviderRepoMockRecorder) Update(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLLMProviderRepo)(nil).Update), ctx, p)
}

// UpdateModel mocks base method.
func (m_2 *MockLLMProviderRepo) UpdateModel(ctx context.Context, m *llm_provider_model_entity.LLMProviderModel) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "UpdateModel", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateModel indicates an expected call of UpdateModel.
func (mr *MockLLMProviderRepoMockRecorder) UpdateModel(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateModel", reflect.TypeOf((*MockLLMProviderRepo)(nil).UpdateModel), ctx, m)
}

// UpsertFromSync mocks base method.
func (m *MockLLMProviderRepo) UpsertFromSync(ctx context.Context, p *llm_provider_entity.LLMProvider, models []*llm_provider_model_entity.LLMProviderModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertFromSync", ctx, p, models)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertFromSync indicates an expected call of UpsertFromSync.
func (mr *MockLLMProviderRepoMockRecorder) UpsertFromSync(ctx, p, models any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertFromSync", reflect.TypeOf((*MockLLMProviderRepo)(nil).UpsertFromSync), ctx, p, models)
}
