// Code generated by MockGen. DO NOT EDIT.
// Source: agent_backend.go
//
// Generated by this command:
//
//	mockgen -source agent_backend.go -destination mock_agent_backend_repo/mock_agent_backend.go
//

// Package mock_agent_backend_repo is a generated GoMock package.
package mock_agent_backend_repo

import (
	context "context"
	reflect "reflect"

	agent_backend_entity "github.com/agentre-hub/agentre/internal/model/entity/agent_backend_entity"
	agent_backend_repo "github.com/agentre-hub/agentre/internal/repository/agent_backend_repo"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentBackendRepo is a mock of AgentBackendRepo interface.
type MockAgentBackendRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAgentBackendRepoMockRecorder
	isgomock struct{}
}

// MockAgentBackendRepoMockRecorder is the mock recorder for MockAgentBackendRepo.
type MockAgentBackendRepoMockRecorder struct {
	mock *MockAgentBackendRepo
}

// NewMockAgentBackendRepo creates a new mock instance.
func NewMockAgentBackendRepo(ctrl *gomock.Controller) *MockAgentBackendRepo {
	mock := &MockAgentBackendRepo{ctrl: ctrl}
	mock.recorder = &MockAgentBackendRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentBackendRepo) EXPECT() *MockAgentBackendRepoMockRecorder {
	return m.recorder
}

// BatchFind mocks base method.
func (m *MockAgentBackendRepo) BatchFind(ctx context.Context, ids []int64) (map[int64]*agent_backend_entity.AgentBackend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchFind", ctx, ids)
	ret0, _ := ret[0].(map[int64]*agent_backend_entity.AgentBackend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchFind indicates an expected call of BatchFind.
func (mr *MockAgentBackendRepoMockRecorder) BatchFind(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchFind", reflect.TypeOf((*MockAgentBackendRepo)(nil).BatchFind), ctx, ids)
}

// ClaimRelative mocks base method.
func (m *MockAgentBackendRepo) ClaimRelative(ctx context.Context, fingerprint string) ([]agent_backend_repo.RelativeClaim, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimRelative", ctx, fingerprint)
	ret0, _ := ret[0].([]agent_backend_repo.RelativeClaim)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimRelative indicates an expected call of ClaimRelative.
func (mr *MockAgentBackendRepoMockRecorder) ClaimRelative(ctx, fingerprint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimRelative", reflect.TypeOf((*MockAgentBackendRepo)(nil).ClaimRelative), ctx, fingerprint)
}

// Create mocks base method.
func (m *MockAgentBackendRepo) Create(ctx context.Context, b *agent_backend_entity.AgentBackend) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAgentBackendRepoMockRecorder) Create(ctx, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAgentBackendRepo)(nil).Create), ctx, b)
}

// CreateCLIOverlay mocks base method.
func (m *MockAgentBackendRepo) CreateCLIOverlay(ctx context.Context, overlay *agent_backend_entity.CLIOverlay) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCLIOverlay", ctx, overlay)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCLIOverlay indicates an expected call of CreateCLIOverlay.
func (mr *MockAgentBackendRepoMockRecorder) CreateCLIOverlay(ctx, overlay any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCLIOverlay", reflect.TypeOf((*MockAgentBackendRepo)(nil).CreateCLIOverlay), ctx, overlay)
}

// Delete mocks base method.
func (m *MockAgentBackendRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAgentBackendRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAgentBackendRepo)(nil).Delete), ctx, id)
}

// DeleteCLIOverlay mocks base method.
func (m *MockAgentBackendRepo) DeleteCLIOverlay(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCLIOverlay", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCLIOverlay indicates an expected call of DeleteCLIOverlay.
func (mr *MockAgentBackendRepoMockRecorder) DeleteCLIOverlay(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCLIOverlay", reflect.TypeOf((*MockAgentBackendRepo)(nil).DeleteCLIOverlay), ctx, id)
}

// ExistsByName mocks base method.
func (m *MockAgentBackendRepo) ExistsByName(ctx context.Context, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByName", ctx, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByName indicates an expected call of ExistsByName.
func (mr *MockAgentBackendRepoMockRecorder) ExistsByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByName", reflect.TypeOf((*MockAgentBackendRepo)(nil).ExistsByName), ctx, name)
}

// Find mocks base method.
func (m *MockAgentBackendRepo) Find(ctx context.Context, id int64) (*agent_backend_entity.AgentBackend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*agent_backend_entity.AgentBackend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockAgentBackendRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAgentBackendRepo)(nil).Find), ctx, id)
}

// FindByName mocks base method.
func (m *MockAgentBackendRepo) FindByName(ctx context.Context, name string) (*agent_backend_entity.AgentBackend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].(*agent_backend_entity.AgentBackend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockAgentBackendRepoMockRecorder) FindByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockAgentBackendRepo)(nil).FindByName), ctx, name)
}

// FindCLIOverlay mocks base method.
func (m *MockAgentBackendRepo) FindCLIOverlay(ctx context.Context, backendSyncID, fingerprint string) (*agent_backend_entity.CLIOverlay, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCLIOverlay", ctx, backendSyncID, fingerprint)
	ret0, _ := ret[0].(*agent_backend_entity.CLIOverlay)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCLIOverlay indicates an expected call of FindCLIOverlay.
func (mr *MockAgentBackendRepoMockRecorder) FindCLIOverlay(ctx, backendSyncID, fingerprint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCLIOverlay", reflect.TypeOf((*MockAgentBackendRepo)(nil).FindCLIOverlay), ctx, backendSyncID, fingerprint)
}

// List mocks base method.
func (m *MockAgentBackendRepo) List(ctx context.Context) ([]*agent_backend_entity.AgentBackend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*agent_backend_entity.AgentBackend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAgentBackendRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAgentBackendRepo)(nil).List), ctx)
}

// ListByDevice mocks base method.
func (m *MockAgentBackendRepo) ListByDevice(ctx context.Context, deviceID string) ([]*agent_backend_entity.AgentBackend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByDevice", ctx, deviceID)
	ret0, _ := ret[0].([]*agent_backend_entity.AgentBackend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByDevice indicates an expected call of ListByDevice.
func (mr *MockAgentBackendRepoMockRecorder) ListByDevice(ctx, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByDevice", reflect.TypeOf((*MockAgentBackendRepo)(nil).ListByDevice), ctx, deviceID)
}

// ListCLIOverlays mocks base method.
func (m *MockAgentBackendRepo) ListCLIOverlays(ctx context.Context) ([]*agent_backend_entity.CLIOverlay, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCLIOverlays", ctx)
	ret0, _ := ret[0].([]*agent_backend_entity.CLIOverlay)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCLIOverlays indicates an expected call of ListCLIOverlays.
func (mr *MockAgentBackendRepoMockRecorder) ListCLIOverlays(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCLIOverlays", reflect.TypeOf((*MockAgentBackendRepo)(nil).ListCLIOverlays), ctx)
}

// ListExecTargetBackendRefs mocks base method.
func (m *MockAgentBackendRepo) ListExecTargetBackendRefs(ctx context.Context) ([]agent_backend_repo.ExecTargetBackendRef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExecTargetBackendRefs", ctx)
	ret0, _ := ret[0].([]agent_backend_repo.ExecTargetBackendRef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExecTargetBackendRefs indicates an expected call of ListExecTargetBackendRefs.
func (mr *MockAgentBackendRepoMockRecorder) ListExecTargetBackendRefs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExecTargetBackendRefs", reflect.TypeOf((*MockAgentBackendRepo)(nil).ListExecTargetBackendRefs), ctx)
}

// ListTombstonesOlderThan mocks base method.
func (m *MockAgentBackendRepo) ListTombstonesOlderThan(ctx context.Context, cutoff int64) ([]*agent_backend_entity.AgentBackend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTombstonesOlderThan", ctx, cutoff)
	ret0, _ := ret[0].([]*agent_backend_entity.AgentBackend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTombstonesOlderThan indicates an expected call of ListTombstonesOlderThan.
func (mr *MockAgentBackendRepoMockRecorder) ListTombstonesOlderThan(ctx, cutoff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTombstonesOlderThan", reflect.TypeOf((*MockAgentBackendRepo)(nil).ListTombstonesOlderThan), ctx, cutoff)
}

// PurgeTombstones mocks base method.
func (m *MockAgentBackendRepo) PurgeTombstones(ctx context.Context, ids []int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PurgeTombstones", ctx, ids)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PurgeTombstones indicates an expected call of PurgeTombstones.
func (mr *MockAgentBackendRepoMockRecorder) PurgeTombstones(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PurgeTombstones", reflect.TypeOf((*MockAgentBackendRepo)(nil).PurgeTombstones), ctx, ids)
}

// Update mocks base method.
func (m *MockAgentBackendRepo) Update(ctx context.Context, b *agent_backend_entity.AgentBackend) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAgentBackendRepoMockRecorder) Update(ctx, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAgentBackendRepo)(nil).Update), ctx, b)
}

// UpdateCLIOverlay mocks base method.
func (m *MockAgentBackendRepo) UpdateCLIOverlay(ctx context.Context, overlay *agent_backend_entity.CLIOverlay) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCLIOverlay", ctx, overlay)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCLIOverlay indicates an expected call of UpdateCLIOverlay.
func (mr *MockAgentBackendRepoMockRecorder) UpdateCLIOverlay(ctx, overlay any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCLIOverlay", reflect.TypeOf((*MockAgentBackendRepo)(nil).UpdateCLIOverlay), ctx, overlay)
}
