// Package handlers implements each daemon RPC method as a thin function.
// All external dependencies enter via the Port interfaces defined here,
// so handler unit tests can inject mocks generated by `make mock`.
package handlers

import (
	"context"
	"time"

	"github.com/cago-frame/agents/agent/blocks"

	"github.com/agentre-hub/agentre/internal/daemon/state"
	"github.com/agentre-hub/agentre/internal/model/entity/agent_backend_entity"
	"github.com/agentre-hub/agentre/internal/model/entity/llm_provider_entity"
	"github.com/agentre-hub/agentre/internal/model/entity/transcript_entity"
	"github.com/agentre-hub/agentre/internal/pkg/agentruntime"
	"github.com/agentre-hub/agentre/internal/pkg/transcript"
	"github.com/agentre-hub/agentre/pkg/wire/agentrewire"
	"github.com/agentre-hub/agentre/pkg/wire/devicefp"
)

//go:generate mockgen -source ports.go -destination mock_handlers/mock_ports.go -package mock_handlers

// StatePort is the subset of *state.State consumed by handlers. State itself
// satisfies this — defining the interface here keeps tests mockable without
// coupling the state package to consumer details.
type StatePort interface {
	Mutate(func(*state.State))
	Save() error
	Snapshot() state.State
}

// NotifierPort sends server-initiated notifications and reverse-direction
// requests back to the connected client (e.g. chat.event, approval.request).
//
// Notify 收的是**已经转换好**的 Protobuf 通知,而不是「method + 随便什么 params」:
// 转换要对密封事件做一次 JSON 解码并重建整棵消息树,而这条路径上跑的是 agent 流式
// 输出的每一个 token。让端口收已转换的消息,发送侧就只可能转换一次 —— 落库的字节与
// 推出去的消息是同一条消息,method 名与会话 id 都由它自己解出(见 protowire 的
// NotificationMethod / NotificationSessionID)。
//
// 调用方交出通知之后不得再改它:扇出会把同一条消息交给属主与每个订阅者,各自在自己的
// goroutine 上 marshal(并发只读安全,并发改不安全)。
type NotifierPort interface {
	Notify(notification *agentrewire.RpcNotification) error
	Request(ctx context.Context, method string, params any, result any) error
}

// TranscriptPort 把这台机器上跑出来的转录落进库:与桌面端**同形**的消息行 + 块行
// (决策 1 / 8)。同一段内容只有这一种存储形态。
//
// 三个方法就是一轮转录的三个时刻:
//
//   - StartTurn:起手。把发起这一轮的用户消息落成一条 user 消息行,并建一条空的
//     assistant 消息行,两行一并交回来。会话身份仍是 conversation_id;它到本机数字
//     主键的翻译在实现里(决策 9),handlers 这一层不认识那个数字。用户那一行也要
//     交回来,是因为它起手就定稿了 —— 调用方当场把它作为持久帧发出去,取到的号才
//     排在这一轮的最前面(没有用户文本的自主续轮交回 nil)。
//     userBlocks 是这一轮随文本一起来的附件(runtime.run 的 userBlocks —— 浏览器
//     控制台发图走的就是它)。它们与文本落在**同一行**用户消息里,顺序是「文本在前、
//     附件在后」,与桌面端本机发图那条路一字不差(chat_svc.userBlocksForSend)。
//     此前这一格不存在,附件只到得了模型、进不了任何宿主的转录
//     (spec 2026-09-07-host-transcript-user-input 决策 3)。
//     source 是提交这一轮的对端身份,盖进用户那一行的第一个文本块 —— 与插话那一路
//     (SegmentTurn)和桌面端做宿主时(chat_svc.persistPeerMessageSource)同一份代码、
//     同一个位置。它必须落在**这一行**上:发起方标识此前只骑在一条另发的预览帧上,
//     而那条帧不进转录、也不参与补齐,于是转录里没人知道这句话是谁发的。
//   - Checkpoint:轮内。每个 ToolResult(以及待决策的提出与作答等定稿时刻)之后一次,
//     只写变化的块行。**在途那一轮抗崩溃只靠它**,不另立 WAL(决策 5)——
//     同一段内容只存这一种形态。
//   - SegmentTurn:轮中分段。插话被后端消费掉的那一刻,当前 assistant 就此收口,
//     后面接上每条插话的一行用户消息与一条空的新 assistant。桌面端做宿主时是同一个
//     形状(chat_svc.persistConsumedSteers),两个宿主必须落下同一份转录
//     (spec 2026-09-07-host-transcript-user-input 决策 1)。
//   - FinishTurn:收口。正文定稿 + 这一轮的模型 / 用量 / 计时 / 错误一起落库。
//
// 交回并在轮内一路带着的是**实体本身**,与桌面端 chat_svc 手里那条 assistantMsg 同形:
// 这一轮的模型 / 用量 / 计时 / 错误由调用方就地写在它上面,收口时随正文一起落库。
// 换成「按 id 传几个标量」会逼实现在每次 checkpoint 前把整条消息连正文读回来,而
// checkpoint 是每个 ToolResult 一次的高频路径。
//
// 实现挂在 Daemon 级(一个 daemon 一份库),不是 per-connection:转录的生产者是活过
// 连接的 fanout goroutine。
//   - AllocateFrameSeqs:发布。块落了库才轮到取号,取到了才发得出去 —— 实时发布的
//     持久帧与补齐交出的那一份因此永远是同一串号(决策 3 /「帧编号」)。它属于写入侧
//     而不是补齐读侧:一条持续在线的对端靠它推进游标,重连补齐才只补它真缺的那一段。
type TranscriptPort interface {
	StartTurn(ctx context.Context, conversationID, userText string, userBlocks []blocks.ContentBlock, source transcript.UserSource) (user, assistant *transcript_entity.Message, err error)
	Checkpoint(ctx context.Context, m *transcript_entity.Message, prevBlocksJSON string) error
	// SegmentTurn 把 current(正文已由调用方定稿)落库,再在它后面依次建每条插话的
	// 用户消息行与一条空的新 assistant 行,一并交回。一次事务:半截分段会让转录里
	// 出现一条没有下文的用户消息。steers 为空时是 no-op。
	SegmentTurn(ctx context.Context, current *transcript_entity.Message, steers []agentruntime.ConsumedSteer) (users []*transcript_entity.Message, next *transcript_entity.Message, err error)
	FinishTurn(ctx context.Context, m *transcript_entity.Message) error
	// AllocateFrameSeqs 依次给这些帧位置取下一个号并落库,返回与 keys 一一对应的编号。
	// 取号失败即没有分配,调用方据此**不发布**这一帧 —— 否则对端会持有一个宿主认不
	// 回来的号。
	AllocateFrameSeqs(ctx context.Context, sessionID int64, keys []transcript.FrameKey) ([]int64, error)
}

// DBStat 是 agentred 自己那个库此刻的落盘事实:文件在哪、占了多少字节。
//
// SizeBytes 是**整个库的体量**(主库文件 + 它的 WAL / SHM 旁文件):WAL 模式下刚写进去
// 的通知先落在 -wal 上,只报主库文件会在最该看见增长的时刻纹丝不动。
type DBStat struct {
	Path      string
	SizeBytes int64
}

// DBStatPort 交出 DBStat。库文件路径与体量必须在 daemon 状态查询里可见，用户据此
// 自行判断何时清理。实现在 daemon 包
// (只有它知道自己开在哪个 DataDir 下),按 DIP 声明在消费方。
//
// Path 只喂给本机 IPC 的状态查询;经 LAN 发给对端的 health.ping 只带体量(见
// HealthPingResult)。
type DBStatPort interface {
	DBStat() DBStat
}

// SessionRecord 是一条会话在 daemon 上的身份与元数据。会话身份是
// (PeerFingerprint, PeerSessionID) 的组合；AgentID / Cwd / BackendType 原样透传
// 客户端起手时报的值,供重连后的清单重建界面。
//
// Title / AgentSyncID 是 R7 的新列:会话标题与所属 Agent 的账号级同步标识,每轮由
// 调用方随 RunParams 携带、幂等覆盖,老会话缺字段时保持空串。ProviderSessionID 是
// 决策 8 的新列:daemon 每轮从 RunAck 路径收回并落库,续话不再需要调用方提供。
//
// 它**不含**「最新 seq」与「是否正在等待输入」:前者由帧编号台账报出(见 DurableFrameReaderPort),
// 后者由实时 waiter 状态叠加计算、永不落库。
type SessionRecord struct {
	PeerFingerprint devicefp.Initiator
	PeerSessionID   string
	AgentID         int64
	Cwd             string
	BackendType     string
	LifecycleState  string
	Title           string
	AgentSyncID     string
	// ProjectSyncID 是这条会话所属项目的账号级同步标识,与 AgentSyncID 同批:每轮
	// 由调用方随 RunParams 携带、幂等覆盖。空串 = 发起方没报,不是「未知待推导」。
	ProjectSyncID     string
	ProviderSessionID string
	// LastMessageAt 是这条会话最后一次活动的时刻(Unix 毫秒),R5 的「最后活动时间」。
	LastMessageAt int64
	// Createtime 是这条会话建立的时刻(Unix 毫秒)。它在起手那一次落下,此后每轮
	// 幂等覆盖都保留最初的值(session_repo.Upsert),因此是一个**不会变**的事实 ——
	// 活跃统计按它分桶,过去那些天的计数才是终值(activityrollup.Aggregate)。
	Createtime int64
	// ProviderKey / ModelKey 是会话级 ModelTarget 的两格,语义见 wire.SessionSummary
	// 上的说明。**每轮起手的 Upsert 不碰它们** —— 它们由 runtime.setModelTarget 单独
	// 写入,跟着轮次幂等覆盖会把轮中刚选好的模型冲回旧值(桌面端 chat_entity 的
	// ModelKey 注释是同一条纪律的另一半)。
	ProviderKey string
	ModelKey    string
	// ReasoningEffort 是会话级思考力度这一格,语义见 wire.SessionSummary 上的说明。
	// 它与上面两格同一条纪律:**每轮起手的 Upsert 不碰它** —— 由
	// runtime.setSessionReasoningEffort 单独写入,跟着轮次幂等覆盖会把用户轮中刚选好
	// 的档位冲回「跟随后端配置」。
	ReasoningEffort string
}

// SessionLifecyclePort 记录会话生命周期的推进,由跑一轮执行的一侧调用。
//
// 生命周期依次为 Start（起手，建行并置 running）→ Finish / Fail
// (轮结束,置 idle / failed)→ Running(自主续轮开始,回到 running)。daemon 重启导致的
// interrupted 不在这里 —— 那是启动清扫一次性做的,进程内没有触发点。
//
// Finish 与 Fail 分成两个方法而不是一个带布尔的 Finish:调用点是「这一轮怎么收的场」
// 这个判断的**唯一**读者,把判断结果编码进方法名,调用处读起来就是它的意思。
type SessionLifecyclePort interface {
	Start(ctx context.Context, rec SessionRecord) error
	Running(ctx context.Context, peerFingerprint devicefp.Initiator, peerSessionID string) error
	Finish(ctx context.Context, peerFingerprint devicefp.Initiator, peerSessionID string) error
	// Fail 把会话落成 failed(轮次以故障收场)。它**不是**终点:会话照旧接得上
	// 实时流、发得出下一轮,再跑一轮就回到 running。判据见 wire.IsTurnFailure。
	Fail(ctx context.Context, peerFingerprint devicefp.Initiator, peerSessionID string) error
}

// SessionListFilter 是会话清单的收窄条件。零值 = 不收窄,那是协议里「整份」那一档
// (不带任何收窄字段的老客户端拿到的形态)。
//
// 两格合成一个结构体而不是各占一个参数:清单与它的 COUNT 必须收**同一份**条件,
// 否则「查看全部 N」下面挂着的是另一批行。一个值传两处,两者天然对得上;拆成并列
// 参数则每加一格就多一处可以漏传的地方。
type SessionListFilter struct {
	// Keyword 按标题的大小写不敏感子串收窄(空串 / 全空白 = 不收窄)。
	Keyword string
	// ConversationIDs 收窄到点名的这几条对话(空 = 不收窄)。它是身份上的点查,
	// 不是搜索:调用方(详情页要一条摘要、账号要它保存过的那些)手上已经有名单,
	// 拿整台机器的清单回去 find 一遍是这条 RPC 最大的一次白读。
	ConversationIDs []string
}

// SessionQueryPort 是会话的读出口,供重连客户端的清单 / 接管查询使用。两个方法都以
// 对端指纹打头：查询一律限定在调用方自己的对端范围内，按会话 id 单独查的入口
// 本层不提供。
type SessionQueryPort interface {
	// List 列出该对端的**一页**会话,再按 filter 收窄。收窄一律下推到存储而不是在
	// 内存里过一遍 —— 对端要的往往只是其中几条,整份取出来再筛既白读一遍库,
	// 也没省下任何东西。
	//
	// offset / limit 同理下推。limit<=0 = 不分页,那是协议里「老客户端不带 limit」
	// 那一档要保留的行为(见 wire.ClampSessionListLimit),不是「一条都不要」。
	List(ctx context.Context, peerFingerprint devicefp.Initiator, filter SessionListFilter, offset, limit int) ([]SessionRecord, error)
	// Count 是 List 在**同一个 filter** 下的总数,供应答里的「一共 N 条」。分页之后
	// 清单只剩一页,N 就只有它数得出;两者收的条件必须一个字不差。
	Count(ctx context.Context, peerFingerprint devicefp.Initiator, filter SessionListFilter) (int64, error)
	// ListByLifecycle 列出停在某个生命周期上的会话,至多 limit 条。
	//
	// session.counts 用它答「在跑几条 / 几条在等你」:正在跑的本来就是个小集合,而
	// 「在等你」只有逐条问过 backend 才知道 —— 拿整份清单去数,等于为三个数把一台
	// 机器的摘要全读一遍。
	ListByLifecycle(ctx context.Context, peerFingerprint devicefp.Initiator, state string, limit int) ([]SessionRecord, error)
	// ListCreatedSince 取建立时刻不早于 createdFromMs 的会话(0 = 不设下界),不限对端:
	// 这台机器上的会话本来就属于同一个账号,而活跃统计是账号级的。
	//
	// 窗口下推到存储而不是取回整份再按天丢:统计问的通常只是最近一段,把三年的会话
	// 读进内存去画一张 30 天的图,正是这一轮要消灭的形态。
	ListCreatedSince(ctx context.Context, createdFromMs int64) ([]SessionRecord, error)
	Find(ctx context.Context, peerFingerprint devicefp.Initiator, peerSessionID string) (*SessionRecord, error)
}

// SelfUpdateActiveTurnsPort 数一数这台 daemon 此刻正在跑的会话,供远程自更新 RPC
// 的活跃轮次闸门使用(update_svc.GuardActiveTurns)。它与 SessionQueryPort 分开声明
// 是 ISP:自更新只要一个数,不该连带拿到能查任意对端会话清单的能力;命令行那一侧的
// 同一道闸门读的是 `agentred status` 的 activeSessions 字段,这里直接读同一份计数
// 的存取口(daemonSessionStore.CountRunning),两条路径最终问的是同一件事。
type SelfUpdateActiveTurnsPort interface {
	CountRunning(ctx context.Context) (int64, error)
}

// SessionDeletePort 删掉一条会话的身份行,返回真的删了几行(不存在时 0 行、不报错)。
//
// 它与 SessionQueryPort / SessionLifecyclePort 分开声明是 ISP,也是刻意的读写分离:
// 补齐族只读、跑一轮的一侧只推进生命周期,只有删除会让一条会话整个消失。
type SessionDeletePort interface {
	Delete(ctx context.Context, peerFingerprint devicefp.Initiator, peerSessionID string) (int64, error)
}

// SessionModelTargetPort 改写某会话钉的 LLM ModelTarget,返回受影响行数
// (0 = 这台机器上没有这条会话)。
//
// 与 SessionLifecyclePort.Start 那条**刻意分开**:Start 每轮起手都跑、携带当轮
// RunParams 里的元数据,而 ModelTarget 不在 RunParams 里 —— 让它跟着轮次幂等覆盖,
// 每轮都会拿零值把用户轮中刚选好的模型静默冲回「跟随 Agent 绑定」。
type SessionModelTargetPort interface {
	SetModelTarget(ctx context.Context, peerFingerprint devicefp.Initiator, peerSessionID, providerKey, modelKey string) (int64, error)
}

// SessionReasoningEffortPort 改写某会话钉的思考力度,返回受影响行数
// (0 = 这台机器上没有这条会话)。
//
// 与 SessionModelTargetPort 分开声明是 ISP:两条 RPC 各自只需要自己那一格,合起来
// 会让改模型的那条路上凭空多出改档位的能力。它同样与 SessionLifecyclePort.Start
// **刻意分开**:那是每轮起手都跑的幂等覆盖,力度不在 RunParams 的元数据里,跟着轮次
// 覆盖会把用户轮中刚选好的档位静默冲回「跟随后端配置」。
type SessionReasoningEffortPort interface {
	SetReasoningEffort(ctx context.Context, peerFingerprint devicefp.Initiator, peerSessionID, reasoningEffort string) (int64, error)
}

// TranscriptPurgePort 删掉某会话的**全部**转录(消息行 + 块行),返回删除的消息行数。
//
// 它是会话删除的另一半:只删会话身份行会留下一段没有主人的转录,而会话号是各客户端
// 本地铸的 —— 那段旧转录下一次就会被当成新会话的历史读走。
//
// 与写入侧(TranscriptPort)分开声明是 ISP:一条路径只做一件事,而这条是唯一一条会让
// 已落库的转录消失的路径。
type TranscriptPurgePort interface {
	DeleteAll(ctx context.Context, peerFingerprint devicefp.Initiator, peerSessionID string) (int64, error)
}

// SteerSourceEntry 是一条 mid-turn steer 的提交方信息。Record 时由 Steer RPC
// 从调用连接的对端鉴权状态里取,Consume 时盖回被消费的 steer 上。
type SteerSourceEntry struct {
	Peer devicefp.Initiator // 提交方设备指纹;空 = 本机/未知
	Name string             // 提交方设备名(auth.pair 时上报);空 = 无可用名字
}

// SteerSourcePort 记录并消费「queuedID → 提交方对端」的映射。它是 **Daemon 级**
// 的:Steer RPC 可能落在任意一条连接上(同设备多条连接 / 他端接管别人的会话),而
// SteerConsumed 由发起会话那条连接的 fanout 发出 —— 映射必须在两者之间共享,per-conn
// 存就会在「提交落在连接 B、fanout 跑在连接 A」时查不到。
type SteerSourcePort interface {
	Record(queuedID string, entry SteerSourceEntry)
	// Consume 取走并删除 queuedID 对应的提交方;查不到返回零值 + false。
	Consume(queuedID string) (SteerSourceEntry, bool)
	// Forget 删除一个 queuedID 的映射(steer 被撤回等不再会被消费的场景)。
	Forget(queuedID string)
}

// DurableFrameRow 是补齐交出的一行。Payload 是那条通知的 params 原样、**不含 seq**;
// seq 是行自己的属性,推送时才盖到帧上。
type DurableFrameRow struct {
	Seq     int64
	Payload []byte
	// Createtime 是这一帧所在转录行落库的那一刻(Unix 毫秒),也就是这一帧真正发生的
	// 时刻。补齐把它原样带出去:下游(浏览器
	// 控制台的转录)除此之外只剩「收到的时刻」,而补齐是成批的,那会把一整段离线期间
	// 的帧盖成同一个瞬间。
	Createtime int64
}

// DurableFrameReaderPort 是补齐的读出口:增量拉取与「最新 seq」。它与 TranscriptPort
// (写)分开声明是 ISP —— 跑一轮执行的一侧只写不读,补齐的一侧只读不写。
//
// 它的**数据源**是持久化的转录(块 → 帧的投影 + 帧编号台账),交出的是「(seq, 那条
// 通知的 params 原样)」。它只服务持久帧 —— 预览帧
// 从不落库,补齐因此天然不重放逐 token 的过程(规格「两级帧与补齐」)。
type DurableFrameReaderPort interface {
	ListSince(ctx context.Context, peerFingerprint devicefp.Initiator, peerSessionID string, cursor int64, limit int) (rows []DurableFrameRow, hasMore bool, err error)
	LatestSeq(ctx context.Context, peerFingerprint devicefp.Initiator, peerSessionID string) (int64, error)
	// LatestSeqs 只对给定的这些行求最新 seq(决策 1 / 要求 8):session.list 传的是它
	// 刚查出来的**这一页**,而不是这个对端全部会话 —— 取代此前的 LatestSeqByPeer,
	// 后者会把整个对端重新 ListByPeer 一遍(offset=0/limit=0 = 全表)再逐条投影整段
	// 转录求 seq,是清单分页时最大的一次白读。返回的 map 按 SessionRecord.PeerSessionID
	// 键出。
	LatestSeqs(ctx context.Context, rows []SessionRecord) (map[string]int64, error)
	// OldestSeq 是该会话现存最老那一帧的 seq,一条都没有时 0。agentred 不回收转录(规格
	// 2026-08-18 决策 8),所以当前实现有帧就报 1;补齐的客户端拿它当下界,分辨「游标之后
	// 那一条还没写」与「它已经不在了」。库被从外部恢复或截断的情形,这个实现并不检测。
	OldestSeq(ctx context.Context, peerFingerprint devicefp.Initiator, peerSessionID string) (int64, error)
}

// GatewayPort daemon-side LLM gateway 端口：给 CLI 子进程签短 token、查 URL、回收 token。
// 当前由 cli.* handler 使用；chat.* 走 Runner 内部直拿 *httpgateway.Gateway 没经此端口。
// 具体实现 *httpgateway.Gateway 自然满足本接口（方法签名一致）。
//
// IssueTokenFor / SetTokenTarget 是会话级 ModelTarget 切换用的两件（spec 决策 3/9/12）：
// 按 wire 传来的 effective target 签发、以及在**不换 token 字符串**的前提下改既有
// token 的路由目标 —— token 首轮就烤进 daemon 本机 spawn 的 CLI 子进程 env，重签会让
// 它立刻 401。
type GatewayPort interface {
	URL() string
	IssueToken(ctx context.Context, b *agent_backend_entity.AgentBackend, ttl time.Duration) (string, error)
	IssueTokenFor(
		ctx context.Context, b *agent_backend_entity.AgentBackend, providerKey, modelKey string, ttl time.Duration,
	) (string, error)
	SetTokenTarget(token, providerKey, modelKey string) (previous string, ok bool)
	RevokeToken(token string)
}

// EffectiveModel 是 daemon 侧解析出的执行模型（决策 11）：固定模型或当前默认模型。
// ModelKey 稳定，ModelID 是实际发给上游的模型 id。
//
// ContextWindow / MaxOutput 是该模型的元数据（目录里没记就是 0），随执行侧配置一路带下去 ——
// 桌面解析口（llm_provider_svc.ResolvedModel）一直有这两项，daemon 这边缺了它们就会让
// 同一套输入在两端构造出不同的 EffectiveLLMConfig。
type EffectiveModel struct {
	ModelKey      string
	ModelID       string
	ContextWindow int
	MaxOutput     int
}

// LLMProviderLookupPort daemon-side LLM provider 查询端口：按稳定 UUID key 解出
// 含 APIKey 的完整 LLMProvider 实体。daemon 内 *ProviderLookup 自然满足本接口。
// 未命中按 (nil, error) 返回，调用方按 error 处理。
//
// 形状有意与 httpgateway.ProviderLookup 重合 —— 在 handlers 这边独立声明
// 是为了保留消费方 ISP，避免 internal/daemon/handlers 反向耦合到
// internal/pkg/httpgateway。
type LLMProviderLookupPort interface {
	FindByKey(ctx context.Context, key string) (*llm_provider_entity.LLMProvider, error)
	// ResolveModel 从 daemon 自家目录解析 Provider 的执行模型（决策 11）：
	//   - modelKey 空 → provider-default：Provider 当前默认模型（DefaultModelKey 精确命中
	//     Models 且启用）。Provider 存在但无合法启用默认模型（无默认 / 默认缺失 / 默认停用）
	//     → error（配置损坏，严格阻止），绝不回落旧单模型字段或空值静默执行；
	//   - modelKey 非空 → fixed-model：精确查 Models 中启用模型。模型缺失或停用 → error，
	//     调用方严格阻止本轮，绝不静默降级为默认模型。
	ResolveModel(ctx context.Context, providerKey, modelKey string) (EffectiveModel, error)
}
