// Package handlers implements each daemon RPC method as a thin function.
// All external dependencies enter via the Port interfaces defined here,
// so handler unit tests can inject mocks generated by `make mock`.
package handlers

import (
	"context"
	"time"

	"github.com/agentre-hub/agentre/internal/daemon/state"
	"github.com/agentre-hub/agentre/internal/model/entity/agent_backend_entity"
	"github.com/agentre-hub/agentre/internal/model/entity/llm_provider_entity"
	"github.com/agentre-hub/agentre/pkg/wire/agentrewire"
)

//go:generate mockgen -source ports.go -destination mock_handlers/mock_ports.go -package mock_handlers

// StatePort is the subset of *state.State consumed by handlers. State itself
// satisfies this — defining the interface here keeps tests mockable without
// coupling the state package to consumer details.
type StatePort interface {
	Mutate(func(*state.State))
	Save() error
	Snapshot() state.State
}

// NotifierPort sends server-initiated notifications and reverse-direction
// requests back to the connected client (e.g. chat.event, approval.request).
//
// Notify 收的是**已经转换好**的 Protobuf 通知,而不是「method + 随便什么 params」:
// 转换要对密封事件做一次 JSON 解码并重建整棵消息树,而这条路径上跑的是 agent 流式
// 输出的每一个 token。让端口收已转换的消息,发送侧就只可能转换一次 —— 落库的字节与
// 推出去的消息是同一条消息,method 名与会话 id 都由它自己解出(见 protowire 的
// NotificationMethod / NotificationSessionID)。
//
// 调用方交出通知之后不得再改它:扇出会把同一条消息交给属主与每个订阅者,各自在自己的
// goroutine 上 marshal(并发只读安全,并发改不安全)。
type NotifierPort interface {
	Notify(notification *agentrewire.RpcNotification) error
	Request(ctx context.Context, method string, params any, result any) error
}

// JournalPort 落库一条「本该发给客户端的通知」,返回库为它分配的 seq。
//
// 它是「先落库，后推送」的接缝：会话通知的发送方先调 Append 拿到 seq，成功后才推送。
// Append 返回 error 时 seq 不推进、该条通知也不推送，因此日志里的 seq 连续无洞 ——
// 客户端拉到的连续 seq 就是完整序列。
//
// 会话身份是 (peerFingerprint, peerSessionID) 的组合:会话 id 是各客户端本地自增的,
// 不同客户端必然重号。payload 是那条通知的 params 原样、且**不含 seq**；seq 是
// 日志行自己的属性,推送时(实时与重连补齐同样)才盖到帧上。
//
// 实现挂在 Daemon 级(一个 daemon 一份库),不是 per-connection —— 断连重连不该重置任何
// 序号,见 daemon.bindConn 的注释。
//
// 「某会话最新的 seq」的唯一真相源是通知日志本身(该会话的 MAX(seq),仓储的原子分配语句
// 读的就是它)。会话表上不存第二份:那样的冗余列一旦与日志对不上,客户端的游标就会指向
// 一个日志里并不存在的位置。
type JournalPort interface {
	Append(ctx context.Context, peerFingerprint, peerSessionID string, payload []byte) (seq int64, err error)
}

// DBStat 是 agentred 自己那个库此刻的落盘事实:文件在哪、占了多少字节。
//
// SizeBytes 是**整个库的体量**(主库文件 + 它的 WAL / SHM 旁文件):WAL 模式下刚写进去
// 的通知先落在 -wal 上,只报主库文件会在最该看见增长的时刻纹丝不动。
type DBStat struct {
	Path      string
	SizeBytes int64
}

// DBStatPort 交出 DBStat。库文件路径与体量必须在 daemon 状态查询里可见，用户据此
// 自行判断何时清理。实现在 daemon 包
// (只有它知道自己开在哪个 DataDir 下),按 DIP 声明在消费方。
//
// Path 只喂给本机 IPC 的状态查询;经 LAN 发给对端的 health.ping 只带体量(见
// HealthPingResult)。
type DBStatPort interface {
	DBStat() DBStat
}

// SessionRecord 是一条会话在 daemon 上的身份与元数据。会话身份是
// (PeerFingerprint, PeerSessionID) 的组合；AgentID / Cwd / BackendType 原样透传
// 客户端起手时报的值,供重连后的清单重建界面。
//
// Title / AgentSyncID 是 R7 的新列:会话标题与所属 Agent 的账号级同步标识,每轮由
// 调用方随 RunParams 携带、幂等覆盖,老会话缺字段时保持空串。ProviderSessionID 是
// 决策 8 的新列:daemon 每轮从 RunAck 路径收回并落库,续话不再需要调用方提供。
//
// 它**不含**「最新 seq」与「是否正在等待输入」:前者的真相源是通知日志的 MAX(seq),
// 后者由实时 waiter 状态叠加计算、永不落库。
type SessionRecord struct {
	PeerFingerprint string
	PeerSessionID   string
	AgentID         int64
	Cwd             string
	BackendType     string
	LifecycleState  string
	Title           string
	AgentSyncID     string
	// ProjectSyncID 是这条会话所属项目的账号级同步标识,与 AgentSyncID 同批:每轮
	// 由调用方随 RunParams 携带、幂等覆盖。空串 = 发起方没报,不是「未知待推导」。
	ProjectSyncID     string
	ProviderSessionID string
	// LastMessageAt 是这条会话最后一次活动的时刻(Unix 毫秒),R5 的「最后活动时间」。
	LastMessageAt int64
	// Createtime 是这条会话建立的时刻(Unix 毫秒)。它在起手那一次落下,此后每轮
	// 幂等覆盖都保留最初的值(session_repo.Upsert),因此是一个**不会变**的事实 ——
	// 活跃统计按它分桶,过去那些天的计数才是终值(activityrollup.Aggregate)。
	Createtime int64
	// ProviderKey / ModelKey 是会话级 ModelTarget 的两格,语义见 wire.SessionSummary
	// 上的说明。**每轮起手的 Upsert 不碰它们** —— 它们由 runtime.setModelTarget 单独
	// 写入,跟着轮次幂等覆盖会把轮中刚选好的模型冲回旧值(桌面端 chat_entity 的
	// ModelKey 注释是同一条纪律的另一半)。
	ProviderKey string
	ModelKey    string
}

// SessionLifecyclePort 记录会话生命周期的推进,由跑一轮执行的一侧调用。
//
// 生命周期依次为 Start（起手，建行并置 running）→ Finish
// (轮结束,置 idle)→ Running(自主续轮开始,回到 running)。daemon 重启导致的
// interrupted 不在这里 —— 那是启动清扫一次性做的,进程内没有触发点。
type SessionLifecyclePort interface {
	Start(ctx context.Context, rec SessionRecord) error
	Running(ctx context.Context, peerFingerprint, peerSessionID string) error
	Finish(ctx context.Context, peerFingerprint, peerSessionID string) error
}

// SessionQueryPort 是会话的读出口,供重连客户端的清单 / 接管查询使用。两个方法都以
// 对端指纹打头：查询一律限定在调用方自己的对端范围内，按会话 id 单独查的入口
// 本层不提供。
type SessionQueryPort interface {
	// List 列出该对端的会话。keyword 非空时再按标题的大小写不敏感子串收窄
	// (空串 / 全空白 = 不收窄)；它下推到存储而不是在内存里过一遍 —— 对端要的
	// 往往只是其中几条,整份取出来再筛既白读一遍库,也没省下任何东西。
	List(ctx context.Context, peerFingerprint, keyword string) ([]SessionRecord, error)
	Find(ctx context.Context, peerFingerprint, peerSessionID string) (*SessionRecord, error)
}

// SessionDeletePort 删掉一条会话的身份行,返回真的删了几行(不存在时 0 行、不报错)。
//
// 它与 SessionQueryPort / SessionLifecyclePort 分开声明是 ISP,也是刻意的读写分离:
// 补齐族只读、跑一轮的一侧只推进生命周期,只有删除会让一条会话整个消失。
type SessionDeletePort interface {
	Delete(ctx context.Context, peerFingerprint, peerSessionID string) (int64, error)
}

// SessionModelTargetPort 改写某会话钉的 LLM ModelTarget,返回受影响行数
// (0 = 这台机器上没有这条会话)。
//
// 与 SessionLifecyclePort.Start 那条**刻意分开**:Start 每轮起手都跑、携带当轮
// RunParams 里的元数据,而 ModelTarget 不在 RunParams 里 —— 让它跟着轮次幂等覆盖,
// 每轮都会拿零值把用户轮中刚选好的模型静默冲回「跟随 Agent 绑定」。
type SessionModelTargetPort interface {
	SetModelTarget(ctx context.Context, peerFingerprint, peerSessionID, providerKey, modelKey string) (int64, error)
}

// JournalPurgePort 清空某会话的**全部**通知日志,返回删除行数。
//
// 它是会话删除的另一半:只删会话行会留下一段没有主人的转录,而会话 id 是各客户端
// 本地自增、会被复用的 —— 那段旧日志下一次就会被当成新会话的历史拉走。
//
// 与 JournalPort(写一条)/ JournalReaderPort(读)三者分开:一条路径只做一件事,
// 而这条是唯一一条会让已落库的通知消失的路径。
type JournalPurgePort interface {
	DeleteAll(ctx context.Context, peerFingerprint, peerSessionID string) (int64, error)
}

// SteerSourceEntry 是一条 mid-turn steer 的提交方信息。Record 时由 Steer RPC
// 从调用连接的对端鉴权状态里取,Consume 时盖回被消费的 steer 上。
type SteerSourceEntry struct {
	Peer string // 提交方设备指纹;空 = 本机/未知
	Name string // 提交方设备名(auth.pair 时上报);空 = 无可用名字
}

// SteerSourcePort 记录并消费「queuedID → 提交方对端」的映射。它是 **Daemon 级**
// 的:Steer RPC 可能落在任意一条连接上(同设备多条连接 / 他端接管别人的会话),而
// SteerConsumed 由发起会话那条连接的 fanout 发出 —— 映射必须在两者之间共享,per-conn
// 存就会在「提交落在连接 B、fanout 跑在连接 A」时查不到。
type SteerSourcePort interface {
	Record(queuedID string, entry SteerSourceEntry)
	// Consume 取走并删除 queuedID 对应的提交方;查不到返回零值 + false。
	Consume(queuedID string) (SteerSourceEntry, bool)
	// Forget 删除一个 queuedID 的映射(steer 被撤回等不再会被消费的场景)。
	Forget(queuedID string)
}

// JournalRow 是通知日志里的一行。Payload 是那条通知的 params 原样、**不含 seq**
// (见 JournalPort)。
type JournalRow struct {
	Seq     int64
	Payload []byte
}

// JournalReaderPort 是通知日志的读出口:增量拉取与「最新 seq」。它与 JournalPort
// (写)分开声明是 ISP —— 跑一轮执行的一侧只写不读,补齐的一侧只读不写。
type JournalReaderPort interface {
	ListSince(ctx context.Context, peerFingerprint, peerSessionID string, cursor int64, limit int) (rows []JournalRow, hasMore bool, err error)
	LatestSeq(ctx context.Context, peerFingerprint, peerSessionID string) (int64, error)
	LatestSeqByPeer(ctx context.Context, peerFingerprint string) (map[string]int64, error)
	// OldestSeq 是该会话现存最老的那一行的 seq(一条都没有时 0)。agentred 已经不回收
	// 通知日志(规格 2026-08-18 决策 8),所以对着当前版本它恒等于第一条;仍然要报,是
	// 因为日志库可能被从外部恢复或截断,而补齐的客户端需要一个下界才分得清「游标之后
	// 那一条还没写」与「它已经不在了」——分不清就只能一直等,会话静默冻住。
	OldestSeq(ctx context.Context, peerFingerprint, peerSessionID string) (int64, error)
}

// GatewayPort daemon-side LLM gateway 端口：给 CLI 子进程签短 token、查 URL、回收 token。
// 当前由 cli.* handler 使用；chat.* 走 Runner 内部直拿 *httpgateway.Gateway 没经此端口。
// 具体实现 *httpgateway.Gateway 自然满足本接口（方法签名一致）。
//
// IssueTokenFor / SetTokenTarget 是会话级 ModelTarget 切换用的两件（spec 决策 3/9/12）：
// 按 wire 传来的 effective target 签发、以及在**不换 token 字符串**的前提下改既有
// token 的路由目标 —— token 首轮就烤进 daemon 本机 spawn 的 CLI 子进程 env，重签会让
// 它立刻 401。
type GatewayPort interface {
	URL() string
	IssueToken(ctx context.Context, b *agent_backend_entity.AgentBackend, ttl time.Duration) (string, error)
	IssueTokenFor(
		ctx context.Context, b *agent_backend_entity.AgentBackend, providerKey, modelKey string, ttl time.Duration,
	) (string, error)
	SetTokenTarget(token, providerKey, modelKey string) (previous string, ok bool)
	RevokeToken(token string)
}

// EffectiveModel 是 daemon 侧解析出的执行模型（决策 11）：固定模型或当前默认模型。
// ModelKey 稳定，ModelID 是实际发给上游的模型 id。
//
// ContextWindow / MaxOutput 是该模型的元数据（目录里没记就是 0），随执行侧配置一路带下去 ——
// 桌面解析口（llm_provider_svc.ResolvedModel）一直有这两项，daemon 这边缺了它们就会让
// 同一套输入在两端构造出不同的 EffectiveLLMConfig。
type EffectiveModel struct {
	ModelKey      string
	ModelID       string
	ContextWindow int
	MaxOutput     int
}

// LLMProviderLookupPort daemon-side LLM provider 查询端口：按稳定 UUID key 解出
// 含 APIKey 的完整 LLMProvider 实体。daemon 内 *ProviderLookup 自然满足本接口。
// 未命中按 (nil, error) 返回，调用方按 error 处理。
//
// 形状有意与 httpgateway.ProviderLookup 重合 —— 在 handlers 这边独立声明
// 是为了保留消费方 ISP，避免 internal/daemon/handlers 反向耦合到
// internal/pkg/httpgateway。
type LLMProviderLookupPort interface {
	FindByKey(ctx context.Context, key string) (*llm_provider_entity.LLMProvider, error)
	// ResolveModel 从 daemon 自家目录解析 Provider 的执行模型（决策 11）：
	//   - modelKey 空 → provider-default：Provider 当前默认模型（DefaultModelKey 精确命中
	//     Models 且启用）。Provider 存在但无合法启用默认模型（无默认 / 默认缺失 / 默认停用）
	//     → error（配置损坏，严格阻止），绝不回落旧单模型字段或空值静默执行；
	//   - modelKey 非空 → fixed-model：精确查 Models 中启用模型。模型缺失或停用 → error，
	//     调用方严格阻止本轮，绝不静默降级为默认模型。
	ResolveModel(ctx context.Context, providerKey, modelKey string) (EffectiveModel, error)
}
