// Code generated by MockGen. DO NOT EDIT.
// Source: label.go
//
// Generated by this command:
//
//	mockgen -source label.go -destination mock_issue_repo/mock_label.go
//

// Package mock_issue_repo is a generated GoMock package.
package mock_issue_repo

import (
	context "context"
	reflect "reflect"

	issue_entity "github.com/agentre-hub/agentre/internal/model/entity/issue_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockLabelRepo is a mock of LabelRepo interface.
type MockLabelRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLabelRepoMockRecorder
	isgomock struct{}
}

// MockLabelRepoMockRecorder is the mock recorder for MockLabelRepo.
type MockLabelRepoMockRecorder struct {
	mock *MockLabelRepo
}

// NewMockLabelRepo creates a new mock instance.
func NewMockLabelRepo(ctrl *gomock.Controller) *MockLabelRepo {
	mock := &MockLabelRepo{ctrl: ctrl}
	mock.recorder = &MockLabelRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLabelRepo) EXPECT() *MockLabelRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLabelRepo) Create(ctx context.Context, l *issue_entity.Label) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, l)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLabelRepoMockRecorder) Create(ctx, l any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLabelRepo)(nil).Create), ctx, l)
}

// Delete mocks base method.
func (m *MockLabelRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLabelRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLabelRepo)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockLabelRepo) Find(ctx context.Context, id int64) (*issue_entity.Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*issue_entity.Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockLabelRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockLabelRepo)(nil).Find), ctx, id)
}

// FindByName mocks base method.
func (m *MockLabelRepo) FindByName(ctx context.Context, name string) (*issue_entity.Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].(*issue_entity.Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockLabelRepoMockRecorder) FindByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockLabelRepo)(nil).FindByName), ctx, name)
}

// List mocks base method.
func (m *MockLabelRepo) List(ctx context.Context) ([]*issue_entity.Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*issue_entity.Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockLabelRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockLabelRepo)(nil).List), ctx)
}

// ListByIDs mocks base method.
func (m *MockLabelRepo) ListByIDs(ctx context.Context, ids []int64) ([]*issue_entity.Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByIDs", ctx, ids)
	ret0, _ := ret[0].([]*issue_entity.Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByIDs indicates an expected call of ListByIDs.
func (mr *MockLabelRepoMockRecorder) ListByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByIDs", reflect.TypeOf((*MockLabelRepo)(nil).ListByIDs), ctx, ids)
}

// Update mocks base method.
func (m *MockLabelRepo) Update(ctx context.Context, l *issue_entity.Label) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, l)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockLabelRepoMockRecorder) Update(ctx, l any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLabelRepo)(nil).Update), ctx, l)
}

// MockIssueLabelRepo is a mock of IssueLabelRepo interface.
type MockIssueLabelRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIssueLabelRepoMockRecorder
	isgomock struct{}
}

// MockIssueLabelRepoMockRecorder is the mock recorder for MockIssueLabelRepo.
type MockIssueLabelRepoMockRecorder struct {
	mock *MockIssueLabelRepo
}

// NewMockIssueLabelRepo creates a new mock instance.
func NewMockIssueLabelRepo(ctrl *gomock.Controller) *MockIssueLabelRepo {
	mock := &MockIssueLabelRepo{ctrl: ctrl}
	mock.recorder = &MockIssueLabelRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIssueLabelRepo) EXPECT() *MockIssueLabelRepoMockRecorder {
	return m.recorder
}

// CountByLabel mocks base method.
func (m *MockIssueLabelRepo) CountByLabel(ctx context.Context) (map[int64]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByLabel", ctx)
	ret0, _ := ret[0].(map[int64]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByLabel indicates an expected call of CountByLabel.
func (mr *MockIssueLabelRepoMockRecorder) CountByLabel(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByLabel", reflect.TypeOf((*MockIssueLabelRepo)(nil).CountByLabel), ctx)
}

// DeleteByLabel mocks base method.
func (m *MockIssueLabelRepo) DeleteByLabel(ctx context.Context, labelID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByLabel", ctx, labelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByLabel indicates an expected call of DeleteByLabel.
func (mr *MockIssueLabelRepoMockRecorder) DeleteByLabel(ctx, labelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByLabel", reflect.TypeOf((*MockIssueLabelRepo)(nil).DeleteByLabel), ctx, labelID)
}

// DeleteBySyncID mocks base method.
func (m *MockIssueLabelRepo) DeleteBySyncID(ctx context.Context, syncID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBySyncID", ctx, syncID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBySyncID indicates an expected call of DeleteBySyncID.
func (mr *MockIssueLabelRepoMockRecorder) DeleteBySyncID(ctx, syncID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBySyncID", reflect.TypeOf((*MockIssueLabelRepo)(nil).DeleteBySyncID), ctx, syncID)
}

// ListByIssue mocks base method.
func (m *MockIssueLabelRepo) ListByIssue(ctx context.Context, issueID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByIssue", ctx, issueID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByIssue indicates an expected call of ListByIssue.
func (mr *MockIssueLabelRepoMockRecorder) ListByIssue(ctx, issueID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByIssue", reflect.TypeOf((*MockIssueLabelRepo)(nil).ListByIssue), ctx, issueID)
}

// ListByIssues mocks base method.
func (m *MockIssueLabelRepo) ListByIssues(ctx context.Context, issueIDs []int64) (map[int64][]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByIssues", ctx, issueIDs)
	ret0, _ := ret[0].(map[int64][]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByIssues indicates an expected call of ListByIssues.
func (mr *MockIssueLabelRepoMockRecorder) ListByIssues(ctx, issueIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByIssues", reflect.TypeOf((*MockIssueLabelRepo)(nil).ListByIssues), ctx, issueIDs)
}

// ListRowsByIssue mocks base method.
func (m *MockIssueLabelRepo) ListRowsByIssue(ctx context.Context, issueID int64) ([]*issue_entity.IssueLabel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRowsByIssue", ctx, issueID)
	ret0, _ := ret[0].([]*issue_entity.IssueLabel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRowsByIssue indicates an expected call of ListRowsByIssue.
func (mr *MockIssueLabelRepoMockRecorder) ListRowsByIssue(ctx, issueID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRowsByIssue", reflect.TypeOf((*MockIssueLabelRepo)(nil).ListRowsByIssue), ctx, issueID)
}

// SetLabels mocks base method.
func (m *MockIssueLabelRepo) SetLabels(ctx context.Context, issueID int64, labelIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLabels", ctx, issueID, labelIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLabels indicates an expected call of SetLabels.
func (mr *MockIssueLabelRepoMockRecorder) SetLabels(ctx, issueID, labelIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLabels", reflect.TypeOf((*MockIssueLabelRepo)(nil).SetLabels), ctx, issueID, labelIDs)
}

// UpsertFromSync mocks base method.
func (m *MockIssueLabelRepo) UpsertFromSync(ctx context.Context, row *issue_entity.IssueLabel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertFromSync", ctx, row)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertFromSync indicates an expected call of UpsertFromSync.
func (mr *MockIssueLabelRepoMockRecorder) UpsertFromSync(ctx, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertFromSync", reflect.TypeOf((*MockIssueLabelRepo)(nil).UpsertFromSync), ctx, row)
}
