// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source deps.go -destination mock_deps/mock_deps.go -package mock_deps
//

// Package mock_deps is a generated GoMock package.
package mock_deps

import (
	context "context"
	reflect "reflect"

	agent_backend_entity "github.com/agentre-hub/agentre/internal/model/entity/agent_backend_entity"
	agent_entity "github.com/agentre-hub/agentre/internal/model/entity/agent_entity"
	chat_entity "github.com/agentre-hub/agentre/internal/model/entity/chat_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionPort is a mock of SessionPort interface.
type MockSessionPort struct {
	ctrl     *gomock.Controller
	recorder *MockSessionPortMockRecorder
	isgomock struct{}
}

// MockSessionPortMockRecorder is the mock recorder for MockSessionPort.
type MockSessionPortMockRecorder struct {
	mock *MockSessionPort
}

// NewMockSessionPort creates a new mock instance.
func NewMockSessionPort(ctrl *gomock.Controller) *MockSessionPort {
	mock := &MockSessionPort{ctrl: ctrl}
	mock.recorder = &MockSessionPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionPort) EXPECT() *MockSessionPortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionPort) Create(ctx context.Context, s *chat_entity.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSessionPortMockRecorder) Create(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionPort)(nil).Create), ctx, s)
}

// ListIDsByProviderSessions mocks base method.
func (m *MockSessionPort) ListIDsByProviderSessions(ctx context.Context, providerSessionIDs []string) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIDsByProviderSessions", ctx, providerSessionIDs)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIDsByProviderSessions indicates an expected call of ListIDsByProviderSessions.
func (mr *MockSessionPortMockRecorder) ListIDsByProviderSessions(ctx, providerSessionIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIDsByProviderSessions", reflect.TypeOf((*MockSessionPort)(nil).ListIDsByProviderSessions), ctx, providerSessionIDs)
}

// Update mocks base method.
func (m *MockSessionPort) Update(ctx context.Context, s *chat_entity.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSessionPortMockRecorder) Update(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSessionPort)(nil).Update), ctx, s)
}

// MockMessagePort is a mock of MessagePort interface.
type MockMessagePort struct {
	ctrl     *gomock.Controller
	recorder *MockMessagePortMockRecorder
	isgomock struct{}
}

// MockMessagePortMockRecorder is the mock recorder for MockMessagePort.
type MockMessagePortMockRecorder struct {
	mock *MockMessagePort
}

// NewMockMessagePort creates a new mock instance.
func NewMockMessagePort(ctrl *gomock.Controller) *MockMessagePort {
	mock := &MockMessagePort{ctrl: ctrl}
	mock.recorder = &MockMessagePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessagePort) EXPECT() *MockMessagePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m_2 *MockMessagePort) Create(ctx context.Context, m *chat_entity.Message) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMessagePortMockRecorder) Create(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMessagePort)(nil).Create), ctx, m)
}

// MockAgentPort is a mock of AgentPort interface.
type MockAgentPort struct {
	ctrl     *gomock.Controller
	recorder *MockAgentPortMockRecorder
	isgomock struct{}
}

// MockAgentPortMockRecorder is the mock recorder for MockAgentPort.
type MockAgentPortMockRecorder struct {
	mock *MockAgentPort
}

// NewMockAgentPort creates a new mock instance.
func NewMockAgentPort(ctrl *gomock.Controller) *MockAgentPort {
	mock := &MockAgentPort{ctrl: ctrl}
	mock.recorder = &MockAgentPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentPort) EXPECT() *MockAgentPortMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockAgentPort) Find(ctx context.Context, id int64) (*agent_entity.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*agent_entity.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockAgentPortMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAgentPort)(nil).Find), ctx, id)
}

// MockAgentBackendPort is a mock of AgentBackendPort interface.
type MockAgentBackendPort struct {
	ctrl     *gomock.Controller
	recorder *MockAgentBackendPortMockRecorder
	isgomock struct{}
}

// MockAgentBackendPortMockRecorder is the mock recorder for MockAgentBackendPort.
type MockAgentBackendPortMockRecorder struct {
	mock *MockAgentBackendPort
}

// NewMockAgentBackendPort creates a new mock instance.
func NewMockAgentBackendPort(ctrl *gomock.Controller) *MockAgentBackendPort {
	mock := &MockAgentBackendPort{ctrl: ctrl}
	mock.recorder = &MockAgentBackendPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentBackendPort) EXPECT() *MockAgentBackendPortMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockAgentBackendPort) Find(ctx context.Context, id int64) (*agent_backend_entity.AgentBackend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*agent_backend_entity.AgentBackend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockAgentBackendPortMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAgentBackendPort)(nil).Find), ctx, id)
}
