// Code generated by MockGen. DO NOT EDIT.
// Source: session.go
//
// Generated by this command:
//
//	mockgen -source session.go -destination mock_session_repo/mock_session.go
//

// Package mock_session_repo is a generated GoMock package.
package mock_session_repo

import (
	context "context"
	reflect "reflect"

	session_repo "github.com/agentre-hub/agentre/internal/daemon/repository/session_repo"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionRepo is a mock of SessionRepo interface.
type MockSessionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepoMockRecorder
	isgomock struct{}
}

// MockSessionRepoMockRecorder is the mock recorder for MockSessionRepo.
type MockSessionRepoMockRecorder struct {
	mock *MockSessionRepo
}

// NewMockSessionRepo creates a new mock instance.
func NewMockSessionRepo(ctrl *gomock.Controller) *MockSessionRepo {
	mock := &MockSessionRepo{ctrl: ctrl}
	mock.recorder = &MockSessionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepo) EXPECT() *MockSessionRepoMockRecorder {
	return m.recorder
}

// CountByLifecycle mocks base method.
func (m *MockSessionRepo) CountByLifecycle(ctx context.Context, state string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByLifecycle", ctx, state)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByLifecycle indicates an expected call of CountByLifecycle.
func (mr *MockSessionRepoMockRecorder) CountByLifecycle(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByLifecycle", reflect.TypeOf((*MockSessionRepo)(nil).CountByLifecycle), ctx, state)
}

// Delete mocks base method.
func (m *MockSessionRepo) Delete(ctx context.Context, peerFingerprint, conversationID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, peerFingerprint, conversationID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockSessionRepoMockRecorder) Delete(ctx, peerFingerprint, conversationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionRepo)(nil).Delete), ctx, peerFingerprint, conversationID)
}

// Find mocks base method.
func (m *MockSessionRepo) Find(ctx context.Context, peerFingerprint, conversationID string) (*session_repo.DaemonSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, peerFingerprint, conversationID)
	ret0, _ := ret[0].(*session_repo.DaemonSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockSessionRepoMockRecorder) Find(ctx, peerFingerprint, conversationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockSessionRepo)(nil).Find), ctx, peerFingerprint, conversationID)
}

// InterruptAll mocks base method.
func (m *MockSessionRepo) InterruptAll(ctx context.Context, interruptedState string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InterruptAll", ctx, interruptedState)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InterruptAll indicates an expected call of InterruptAll.
func (mr *MockSessionRepoMockRecorder) InterruptAll(ctx, interruptedState any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InterruptAll", reflect.TypeOf((*MockSessionRepo)(nil).InterruptAll), ctx, interruptedState)
}

// ListAll mocks base method.
func (m *MockSessionRepo) ListAll(ctx context.Context, keyword string) ([]*session_repo.DaemonSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx, keyword)
	ret0, _ := ret[0].([]*session_repo.DaemonSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockSessionRepoMockRecorder) ListAll(ctx, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockSessionRepo)(nil).ListAll), ctx, keyword)
}

// ListByPeer mocks base method.
func (m *MockSessionRepo) ListByPeer(ctx context.Context, peerFingerprint, keyword string) ([]*session_repo.DaemonSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByPeer", ctx, peerFingerprint, keyword)
	ret0, _ := ret[0].([]*session_repo.DaemonSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByPeer indicates an expected call of ListByPeer.
func (mr *MockSessionRepoMockRecorder) ListByPeer(ctx, peerFingerprint, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByPeer", reflect.TypeOf((*MockSessionRepo)(nil).ListByPeer), ctx, peerFingerprint, keyword)
}

// SetModelTarget mocks base method.
func (m *MockSessionRepo) SetModelTarget(ctx context.Context, peerFingerprint, conversationID, providerKey, modelKey string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetModelTarget", ctx, peerFingerprint, conversationID, providerKey, modelKey)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetModelTarget indicates an expected call of SetModelTarget.
func (mr *MockSessionRepoMockRecorder) SetModelTarget(ctx, peerFingerprint, conversationID, providerKey, modelKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetModelTarget", reflect.TypeOf((*MockSessionRepo)(nil).SetModelTarget), ctx, peerFingerprint, conversationID, providerKey, modelKey)
}

// SetReasoningEffort mocks base method.
func (m *MockSessionRepo) SetReasoningEffort(ctx context.Context, peerFingerprint, conversationID, reasoningEffort string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetReasoningEffort", ctx, peerFingerprint, conversationID, reasoningEffort)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetReasoningEffort indicates an expected call of SetReasoningEffort.
func (mr *MockSessionRepoMockRecorder) SetReasoningEffort(ctx, peerFingerprint, conversationID, reasoningEffort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReasoningEffort", reflect.TypeOf((*MockSessionRepo)(nil).SetReasoningEffort), ctx, peerFingerprint, conversationID, reasoningEffort)
}

// UpdateLifecycle mocks base method.
func (m *MockSessionRepo) UpdateLifecycle(ctx context.Context, peerFingerprint, conversationID, state string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLifecycle", ctx, peerFingerprint, conversationID, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLifecycle indicates an expected call of UpdateLifecycle.
func (mr *MockSessionRepoMockRecorder) UpdateLifecycle(ctx, peerFingerprint, conversationID, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLifecycle", reflect.TypeOf((*MockSessionRepo)(nil).UpdateLifecycle), ctx, peerFingerprint, conversationID, state)
}

// Upsert mocks base method.
func (m *MockSessionRepo) Upsert(ctx context.Context, s *session_repo.DaemonSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockSessionRepoMockRecorder) Upsert(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockSessionRepo)(nil).Upsert), ctx, s)
}
