// Code generated by MockGen. DO NOT EDIT.
// Source: syncstate.go
//
// Generated by this command:
//
//	mockgen -source syncstate.go -destination mock_syncstate_repo/mock_syncstate.go
//

// Package mock_syncstate_repo is a generated GoMock package.
package mock_syncstate_repo

import (
	context "context"
	reflect "reflect"

	syncmeta_entity "github.com/agentre-hub/agentre/internal/model/entity/syncmeta_entity"
	syncstate_repo "github.com/agentre-hub/agentre/internal/repository/syncstate_repo"
	gomock "go.uber.org/mock/gomock"
)

// MockSyncStateRepo is a mock of SyncStateRepo interface.
type MockSyncStateRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSyncStateRepoMockRecorder
	isgomock struct{}
}

// MockSyncStateRepoMockRecorder is the mock recorder for MockSyncStateRepo.
type MockSyncStateRepoMockRecorder struct {
	mock *MockSyncStateRepo
}

// NewMockSyncStateRepo creates a new mock instance.
func NewMockSyncStateRepo(ctrl *gomock.Controller) *MockSyncStateRepo {
	mock := &MockSyncStateRepo{ctrl: ctrl}
	mock.recorder = &MockSyncStateRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncStateRepo) EXPECT() *MockSyncStateRepoMockRecorder {
	return m.recorder
}

// ClaimUnowned mocks base method.
func (m *MockSyncStateRepo) ClaimUnowned(ctx context.Context, kind string, accountID int64) ([]syncstate_repo.ClaimedRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimUnowned", ctx, kind, accountID)
	ret0, _ := ret[0].([]syncstate_repo.ClaimedRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimUnowned indicates an expected call of ClaimUnowned.
func (mr *MockSyncStateRepoMockRecorder) ClaimUnowned(ctx, kind, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimUnowned", reflect.TypeOf((*MockSyncStateRepo)(nil).ClaimUnowned), ctx, kind, accountID)
}

// FindLocalID mocks base method.
func (m *MockSyncStateRepo) FindLocalID(ctx context.Context, kind, syncID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLocalID", ctx, kind, syncID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLocalID indicates an expected call of FindLocalID.
func (mr *MockSyncStateRepoMockRecorder) FindLocalID(ctx, kind, syncID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLocalID", reflect.TypeOf((*MockSyncStateRepo)(nil).FindLocalID), ctx, kind, syncID)
}

// FindRow mocks base method.
func (m *MockSyncStateRepo) FindRow(ctx context.Context, kind, syncID string, dest any) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRow", ctx, kind, syncID, dest)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRow indicates an expected call of FindRow.
func (mr *MockSyncStateRepoMockRecorder) FindRow(ctx, kind, syncID, dest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRow", reflect.TypeOf((*MockSyncStateRepo)(nil).FindRow), ctx, kind, syncID, dest)
}

// FindVersion mocks base method.
func (m *MockSyncStateRepo) FindVersion(ctx context.Context, kind, syncID string) (int64, bool, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindVersion", ctx, kind, syncID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// FindVersion indicates an expected call of FindVersion.
func (mr *MockSyncStateRepoMockRecorder) FindVersion(ctx, kind, syncID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindVersion", reflect.TypeOf((*MockSyncStateRepo)(nil).FindVersion), ctx, kind, syncID)
}

// ListUnversioned mocks base method.
func (m *MockSyncStateRepo) ListUnversioned(ctx context.Context, kind string, accountID int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnversioned", ctx, kind, accountID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnversioned indicates an expected call of ListUnversioned.
func (mr *MockSyncStateRepoMockRecorder) ListUnversioned(ctx, kind, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnversioned", reflect.TypeOf((*MockSyncStateRepo)(nil).ListUnversioned), ctx, kind, accountID)
}

// ResetVersions mocks base method.
func (m *MockSyncStateRepo) ResetVersions(ctx context.Context, kind string, accountID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetVersions", ctx, kind, accountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetVersions indicates an expected call of ResetVersions.
func (mr *MockSyncStateRepoMockRecorder) ResetVersions(ctx, kind, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetVersions", reflect.TypeOf((*MockSyncStateRepo)(nil).ResetVersions), ctx, kind, accountID)
}

// SaveMeta mocks base method.
func (m *MockSyncStateRepo) SaveMeta(ctx context.Context, kind, syncID string, meta syncmeta_entity.SyncMeta) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMeta", ctx, kind, syncID, meta)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMeta indicates an expected call of SaveMeta.
func (mr *MockSyncStateRepoMockRecorder) SaveMeta(ctx, kind, syncID, meta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMeta", reflect.TypeOf((*MockSyncStateRepo)(nil).SaveMeta), ctx, kind, syncID, meta)
}
