// Code generated by MockGen. DO NOT EDIT.
// Source: frame_seq.go
//
// Generated by this command:
//
//	mockgen -source frame_seq.go -destination mock_transcript_repo/mock_frame_seq.go
//

// Package mock_transcript_repo is a generated GoMock package.
package mock_transcript_repo

import (
	context "context"
	reflect "reflect"

	transcript_repo "github.com/agentre-hub/agentre/internal/repository/transcript_repo"
	gomock "go.uber.org/mock/gomock"
)

// MockFrameSeqRepo is a mock of FrameSeqRepo interface.
type MockFrameSeqRepo struct {
	ctrl     *gomock.Controller
	recorder *MockFrameSeqRepoMockRecorder
}

// MockFrameSeqRepoMockRecorder is the mock recorder for MockFrameSeqRepo.
type MockFrameSeqRepoMockRecorder struct {
	mock *MockFrameSeqRepo
}

// NewMockFrameSeqRepo creates a new mock instance.
func NewMockFrameSeqRepo(ctrl *gomock.Controller) *MockFrameSeqRepo {
	mock := &MockFrameSeqRepo{ctrl: ctrl}
	mock.recorder = &MockFrameSeqRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFrameSeqRepo) EXPECT() *MockFrameSeqRepoMockRecorder {
	return m.recorder
}

// Allocate mocks base method.
func (m *MockFrameSeqRepo) Allocate(ctx context.Context, sessionID int64, keys []transcript_repo.FrameKey) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allocate", ctx, sessionID, keys)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Allocate indicates an expected call of Allocate.
func (mr *MockFrameSeqRepoMockRecorder) Allocate(ctx, sessionID, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allocate", reflect.TypeOf((*MockFrameSeqRepo)(nil).Allocate), ctx, sessionID, keys)
}

// DeleteBySession mocks base method.
func (m *MockFrameSeqRepo) DeleteBySession(ctx context.Context, sessionID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBySession", ctx, sessionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBySession indicates an expected call of DeleteBySession.
func (mr *MockFrameSeqRepoMockRecorder) DeleteBySession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBySession", reflect.TypeOf((*MockFrameSeqRepo)(nil).DeleteBySession), ctx, sessionID)
}

// Load mocks base method.
func (m *MockFrameSeqRepo) Load(ctx context.Context, sessionID int64) (map[transcript_repo.FrameKey]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, sessionID)
	ret0, _ := ret[0].(map[transcript_repo.FrameKey]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockFrameSeqRepoMockRecorder) Load(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockFrameSeqRepo)(nil).Load), ctx, sessionID)
}
