// Code generated by MockGen. DO NOT EDIT.
// Source: svc.go
//
// Generated by this command:
//
//	mockgen -source svc.go -destination mock_workspace_fs_svc/mock_svc.go
//

// Package mock_workspace_fs_svc is a generated GoMock package.
package mock_workspace_fs_svc

import (
	context "context"
	reflect "reflect"

	workspace_fs_svc "github.com/agentre-hub/agentre/internal/service/workspace_fs_svc"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkspaceFsSvc is a mock of WorkspaceFsSvc interface.
type MockWorkspaceFsSvc struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceFsSvcMockRecorder
	isgomock struct{}
}

// MockWorkspaceFsSvcMockRecorder is the mock recorder for MockWorkspaceFsSvc.
type MockWorkspaceFsSvcMockRecorder struct {
	mock *MockWorkspaceFsSvc
}

// NewMockWorkspaceFsSvc creates a new mock instance.
func NewMockWorkspaceFsSvc(ctrl *gomock.Controller) *MockWorkspaceFsSvc {
	mock := &MockWorkspaceFsSvc{ctrl: ctrl}
	mock.recorder = &MockWorkspaceFsSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspaceFsSvc) EXPECT() *MockWorkspaceFsSvcMockRecorder {
	return m.recorder
}

// GitBranches mocks base method.
func (m *MockWorkspaceFsSvc) GitBranches(ctx context.Context, sessionID int64) (*workspace_fs_svc.GitBranchesView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GitBranches", ctx, sessionID)
	ret0, _ := ret[0].(*workspace_fs_svc.GitBranchesView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GitBranches indicates an expected call of GitBranches.
func (mr *MockWorkspaceFsSvcMockRecorder) GitBranches(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GitBranches", reflect.TypeOf((*MockWorkspaceFsSvc)(nil).GitBranches), ctx, sessionID)
}

// GitChanges mocks base method.
func (m *MockWorkspaceFsSvc) GitChanges(ctx context.Context, sessionID int64, root, scope, baseRef string) (*workspace_fs_svc.GitChangesView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GitChanges", ctx, sessionID, root, scope, baseRef)
	ret0, _ := ret[0].(*workspace_fs_svc.GitChangesView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GitChanges indicates an expected call of GitChanges.
func (mr *MockWorkspaceFsSvcMockRecorder) GitChanges(ctx, sessionID, root, scope, baseRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GitChanges", reflect.TypeOf((*MockWorkspaceFsSvc)(nil).GitChanges), ctx, sessionID, root, scope, baseRef)
}

// GitFileContent mocks base method.
func (m *MockWorkspaceFsSvc) GitFileContent(ctx context.Context, sessionID int64, root, relPath string) (*workspace_fs_svc.GitFileContentView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GitFileContent", ctx, sessionID, root, relPath)
	ret0, _ := ret[0].(*workspace_fs_svc.GitFileContentView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GitFileContent indicates an expected call of GitFileContent.
func (mr *MockWorkspaceFsSvcMockRecorder) GitFileContent(ctx, sessionID, root, relPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GitFileContent", reflect.TypeOf((*MockWorkspaceFsSvc)(nil).GitFileContent), ctx, sessionID, root, relPath)
}

// GitState mocks base method.
func (m *MockWorkspaceFsSvc) GitState(ctx context.Context, sessionID int64, root string) (*workspace_fs_svc.GitStateView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GitState", ctx, sessionID, root)
	ret0, _ := ret[0].(*workspace_fs_svc.GitStateView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GitState indicates an expected call of GitState.
func (mr *MockWorkspaceFsSvcMockRecorder) GitState(ctx, sessionID, root any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GitState", reflect.TypeOf((*MockWorkspaceFsSvc)(nil).GitState), ctx, sessionID, root)
}

// ListDir mocks base method.
func (m *MockWorkspaceFsSvc) ListDir(ctx context.Context, sessionID int64, root, relPath string, includeIgnored bool) (*workspace_fs_svc.ListDirView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDir", ctx, sessionID, root, relPath, includeIgnored)
	ret0, _ := ret[0].(*workspace_fs_svc.ListDirView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDir indicates an expected call of ListDir.
func (mr *MockWorkspaceFsSvcMockRecorder) ListDir(ctx, sessionID, root, relPath, includeIgnored any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDir", reflect.TypeOf((*MockWorkspaceFsSvc)(nil).ListDir), ctx, sessionID, root, relPath, includeIgnored)
}

// ReadFile mocks base method.
func (m *MockWorkspaceFsSvc) ReadFile(ctx context.Context, sessionID int64, root, relPath string) (*workspace_fs_svc.ReadFileView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", ctx, sessionID, root, relPath)
	ret0, _ := ret[0].(*workspace_fs_svc.ReadFileView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockWorkspaceFsSvcMockRecorder) ReadFile(ctx, sessionID, root, relPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockWorkspaceFsSvc)(nil).ReadFile), ctx, sessionID, root, relPath)
}

// SearchFiles mocks base method.
func (m *MockWorkspaceFsSvc) SearchFiles(ctx context.Context, sessionID int64, root, query string, includeIgnored bool) (*workspace_fs_svc.SearchFilesView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchFiles", ctx, sessionID, root, query, includeIgnored)
	ret0, _ := ret[0].(*workspace_fs_svc.SearchFilesView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchFiles indicates an expected call of SearchFiles.
func (mr *MockWorkspaceFsSvcMockRecorder) SearchFiles(ctx, sessionID, root, query, includeIgnored any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchFiles", reflect.TypeOf((*MockWorkspaceFsSvc)(nil).SearchFiles), ctx, sessionID, root, query, includeIgnored)
}

// WorkRoots mocks base method.
func (m *MockWorkspaceFsSvc) WorkRoots(ctx context.Context, sessionID int64) ([]workspace_fs_svc.WorkRootView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkRoots", ctx, sessionID)
	ret0, _ := ret[0].([]workspace_fs_svc.WorkRootView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WorkRoots indicates an expected call of WorkRoots.
func (mr *MockWorkspaceFsSvcMockRecorder) WorkRoots(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkRoots", reflect.TypeOf((*MockWorkspaceFsSvc)(nil).WorkRoots), ctx, sessionID)
}
