// Code generated by MockGen. DO NOT EDIT.
// Source: gateway.go
//
// Generated by this command:
//
//	mockgen -source gateway.go -destination mock_subagent_svc/mock_gateway.go
//

// Package mock_subagent_svc is a generated GoMock package.
package mock_subagent_svc

import (
	context "context"
	reflect "reflect"

	agent_entity "github.com/agentre-hub/agentre/internal/model/entity/agent_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentGateway is a mock of AgentGateway interface.
type MockAgentGateway struct {
	ctrl     *gomock.Controller
	recorder *MockAgentGatewayMockRecorder
	isgomock struct{}
}

// MockAgentGatewayMockRecorder is the mock recorder for MockAgentGateway.
type MockAgentGatewayMockRecorder struct {
	mock *MockAgentGateway
}

// NewMockAgentGateway creates a new mock instance.
func NewMockAgentGateway(ctrl *gomock.Controller) *MockAgentGateway {
	mock := &MockAgentGateway{ctrl: ctrl}
	mock.recorder = &MockAgentGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentGateway) EXPECT() *MockAgentGatewayMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockAgentGateway) Find(ctx context.Context, id int64) (*agent_entity.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*agent_entity.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockAgentGatewayMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAgentGateway)(nil).Find), ctx, id)
}

// FindByName mocks base method.
func (m *MockAgentGateway) FindByName(ctx context.Context, name string) (*agent_entity.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].(*agent_entity.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockAgentGatewayMockRecorder) FindByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockAgentGateway)(nil).FindByName), ctx, name)
}

// List mocks base method.
func (m *MockAgentGateway) List(ctx context.Context) ([]*agent_entity.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*agent_entity.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAgentGatewayMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAgentGateway)(nil).List), ctx)
}
